// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <memory>
#include <servicelib/datasource/cron/libcron.hpp>

namespace example::analytics_service::app {
struct ConsumeOrderProcessedKafkaConsumerOwner;
struct ServiceConnectors final {
  ServiceConnectors();
  ~ServiceConnectors();
  ServiceConnectors(ServiceConnectors&&) noexcept;
  ServiceConnectors& operator=(ServiceConnectors&&) noexcept;
  std::unique_ptr<ConsumeOrderProcessedKafkaConsumerOwner> consume_order_processed_consumer;
  std::shared_ptr<servicelib::datasource::cron::LibcronDataSource> local_cron_cron_source;
};

}  // namespace example::analytics_service::app