// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/makers.generated.hpp"
#include <stdexcept>
#include <userver/utils/async.hpp>
#include <utility>
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>

namespace example::analytics_service::app {
void ServiceMakers::initMakers(const userver::components::ComponentContext& components) {
  auto& makers_ = *this;
  (void)makers_; (void)components;
  advance_cycle_analytics = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeAdvanceCycleAnalytics(std::move(context), environment);
  };
  analytics_orders_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeAnalyticsOrdersSource(std::move(context), environment);
  };
  analytics_payments_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeAnalyticsPaymentsSource(std::move(context), environment);
  };
  analytics_schedule_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeAnalyticsScheduleSource(std::move(context), environment);
  };
  analytics_shipments_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeAnalyticsShipmentsSource(std::move(context), environment);
  };
  build_substream_analytics_result = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeBuildSubstreamAnalyticsResult(std::move(context), environment);
  };
  complete_cycle_analytics = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeCompleteCycleAnalytics(std::move(context), environment);
  };
  continue_cycle_analytics = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeContinueCycleAnalytics(std::move(context), environment);
  };
  count_order_processed = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeCountOrderProcessed(std::move(context), environment);
  };
  cycle_analytics_input_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeCycleAnalyticsInputSource(std::move(context), environment);
  };
  cycle_analytics_result_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeCycleAnalyticsResultSink(std::move(context), environment);
  };
  high_value_analytics_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeHighValueAnalyticsSink(std::move(context), environment);
  };
  invoke_analytics_substream = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeInvokeAnalyticsSubstream(std::move(context), environment);
  };
  join_order_payment_analytics = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeJoinOrderPaymentAnalytics(std::move(context), environment);
  };
  joined_analytics_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeJoinedAnalyticsSink(std::move(context), environment);
  };
  key_orders_for_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyOrdersForJoin(std::move(context), environment);
  };
  key_orders_for_multi_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyOrdersForMultiJoin(std::move(context), environment);
  };
  key_payments_for_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyPaymentsForJoin(std::move(context), environment);
  };
  key_payments_for_multi_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyPaymentsForMultiJoin(std::move(context), environment);
  };
  key_shipments_for_multi_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyShipmentsForMultiJoin(std::move(context), environment);
  };
  multi_join_analytics_events = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeMultiJoinAnalyticsEvents(std::move(context), environment);
  };
  order_processed_endpoint_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeOrderProcessedEndpointSource(std::move(context), environment);
  };
  route_analytics_result = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeRouteAnalyticsResult(std::move(context), environment);
  };
  standard_analytics_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeStandardAnalyticsSink(std::move(context), environment);
  };
  substream_analytics_input_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeSubstreamAnalyticsInputSource(std::move(context), environment);
  };
  substream_analytics_result_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeSubstreamAnalyticsResultSink(std::move(context), environment);
  };

}


}  // namespace example::analytics_service::app