// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <userver/components/component_context.hpp>
#include <functional>
#include <memory>
#include <userver/engine/task/task_with_result.hpp>
#include <servicelib/runtime/context.hpp>
#include <servicelib/runtime/environment/environment.hpp>
#include <servicelib/runtime/config/config.hpp>
#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <example/model/types/automation_job.hpp>
#include <example/model/types/order_processed.hpp>

namespace example::analytics_service::functions {
class AdvanceCycleAnalytics;
class AnalyticsOrdersSource;
class AnalyticsPaymentsSource;
class AnalyticsScheduleSource;
class AnalyticsShipmentsSource;
class BuildSubstreamAnalyticsResult;
class CompleteCycleAnalytics;
class ContinueCycleAnalytics;
class CountOrderProcessed;
class CycleAnalyticsInputSource;
class CycleAnalyticsResultSink;
class HighValueAnalyticsSink;
class InvokeAnalyticsSubstream;
class JoinOrderPaymentAnalytics;
class JoinedAnalyticsSink;
class KeyOrdersForJoin;
class KeyOrdersForMultiJoin;
class KeyPaymentsForJoin;
class KeyPaymentsForMultiJoin;
class KeyShipmentsForMultiJoin;
class MultiJoinAnalyticsEvents;
class OrderProcessedEndpointSource;
class RouteAnalyticsResult;
class StandardAnalyticsSink;
class SubstreamAnalyticsInputSource;
class SubstreamAnalyticsResultSink;
}
namespace example::analytics_service::app {
struct ServiceMakers final {
  void initMakers(const userver::components::ComponentContext& components);
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::AdvanceCycleAnalytics>>(servicelib::Context, servicelib::IServiceEnvironment&)> advance_cycle_analytics;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::AnalyticsOrdersSource>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> analytics_orders_source;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::AnalyticsPaymentsSource>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> analytics_payments_source;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::AnalyticsScheduleSource>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CronEndpointConfig&)> analytics_schedule_source;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::AnalyticsShipmentsSource>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> analytics_shipments_source;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::BuildSubstreamAnalyticsResult>>(servicelib::Context, servicelib::IServiceEnvironment&)> build_substream_analytics_result;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::CompleteCycleAnalytics>>(servicelib::Context, servicelib::IServiceEnvironment&)> complete_cycle_analytics;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::ContinueCycleAnalytics>>(servicelib::Context, servicelib::IServiceEnvironment&)> continue_cycle_analytics;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::CountOrderProcessed>>(servicelib::Context, servicelib::IServiceEnvironment&)> count_order_processed;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::CycleAnalyticsInputSource>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> cycle_analytics_input_source;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::CycleAnalyticsResultSink>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> cycle_analytics_result_sink;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::HighValueAnalyticsSink>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> high_value_analytics_sink;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::InvokeAnalyticsSubstream>>(servicelib::Context, servicelib::IServiceEnvironment&)> invoke_analytics_substream;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::JoinOrderPaymentAnalytics>>(servicelib::Context, servicelib::IServiceEnvironment&)> join_order_payment_analytics;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::JoinedAnalyticsSink>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> joined_analytics_sink;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::KeyOrdersForJoin>>(servicelib::Context, servicelib::IServiceEnvironment&)> key_orders_for_join;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::KeyOrdersForMultiJoin>>(servicelib::Context, servicelib::IServiceEnvironment&)> key_orders_for_multi_join;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::KeyPaymentsForJoin>>(servicelib::Context, servicelib::IServiceEnvironment&)> key_payments_for_join;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::KeyPaymentsForMultiJoin>>(servicelib::Context, servicelib::IServiceEnvironment&)> key_payments_for_multi_join;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::KeyShipmentsForMultiJoin>>(servicelib::Context, servicelib::IServiceEnvironment&)> key_shipments_for_multi_join;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::MultiJoinAnalyticsEvents>>(servicelib::Context, servicelib::IServiceEnvironment&)> multi_join_analytics_events;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::OrderProcessedEndpointSource>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::KafkaEndpointConfig&)> order_processed_endpoint_source;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::RouteAnalyticsResult>>(servicelib::Context, servicelib::IServiceEnvironment&)> route_analytics_result;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::StandardAnalyticsSink>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> standard_analytics_sink;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::SubstreamAnalyticsInputSource>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> substream_analytics_input_source;
  std::function<userver::engine::TaskWithResult<std::unique_ptr<functions::SubstreamAnalyticsResultSink>>(servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> substream_analytics_result_sink;
  
};

}  // namespace example::analytics_service::app