// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include "analyticsservice/internal/app/substreams.generated.hpp"

#include "analyticsservice/internal/app/servers.generated.hpp"

#include "analyticsservice/internal/app/connectors.generated.hpp"

#include "analyticsservice/internal/app/clients.generated.hpp"

#include "analyticsservice/internal/app/endpoints.generated.hpp"


#include "analyticsservice/internal/app/makers.generated.hpp"
#include "analyticsservice/internal/app/functions.generated.hpp"
#include "analyticsservice/internal/app/streams.generated.hpp"
#include "analyticsservice/internal/app/bindings.generated.hpp"


#include <memory>
#include <atomic>

#include <functional>
#include <exception>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/components/statistics_storage.hpp>
#include <userver/engine/task/task_with_result.hpp>
#include <userver/engine/mutex.hpp>


#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/component.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/runtime/telemetry/userver/log.hpp>
#include <servicelib/runtime/telemetry/userver/metrics.hpp>
#include <servicelib/runtime/telemetry/userver/tracing.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/kafka/userver.hpp>
#include <userver/kafka/consumer_component.hpp>
#include <servicelib/datasource/localsource/custom.hpp>
#include <servicelib/datasource/cron/libcron.hpp>
#include <servicelib/datasink/localsink/custom.hpp>

#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <example/model/types/automation_job.hpp>
#include <example/model/types/order_processed.hpp>



namespace example::analytics_service::app {

// Business functions may retain handles without retaining the graph itself.



struct DataTypes final {
  template <typename>
  struct DataType {};
};

using RuntimeConfigComponent =
    servicelib::config::ServicelibRuntimeComponent<config::Config>;

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  explicit ServiceGenerated(
      userver::utils::statistics::Storage& statistics_storage,
      const userver::components::ComponentContext& component_context);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

  std::shared_ptr<servicelib::ISubStream<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult>>
  getAnalyzeAnalyticsSubstreamSubStream() const noexcept {
    return substreams_.getAnalyzeAnalyticsSubstreamSubStream();
  }


 protected:
  ServiceMakers makers_;
  ServiceFunctions functions_;

  virtual void customMakersInit(servicelib::Context) {}
  virtual void customFunctionsInit(servicelib::Context) {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  friend struct ServiceEndpoints;
  void initMakers();
  void initInfrastructure(servicelib::Context context,
                          const config::Config& config);
  void initFunctions(servicelib::Context context, const config::Config& config);
  void initRuntime(servicelib::Context context);
  void initStreams(const config::Config& config);
  void initDataSinks(const config::Config& config);
  void initDataSources(const config::Config& config);
  void releaseRuntime() noexcept;




  ServiceStreams streams_;

  ServiceBindings bindings_;

 public:


 private:
  ServiceEndpoints endpoints_;

  ServiceConnectors connectors_;
  ServiceClients clients_;
  ServiceServers servers_;
  ServiceSubStreams substreams_;

  [[maybe_unused]] const userver::components::ComponentContext& component_context_;
  servicelib::telemetry::userver_adapter::UserverMetrics metrics_;
  bool use_noop_logs_{false};
  bool use_noop_metrics_{false};
  bool use_noop_tracing_{false};
  bool user_lifecycle_started_{false};
  int shutdown_exit_code_{};
};

class Service;

class AnalyticsServiceComponent final : public userver::components::ComponentBase {
 public:
  static constexpr std::string_view kName = "service-analytics-service";

  AnalyticsServiceComponent(
      const userver::components::ComponentConfig& config,
      const userver::components::ComponentContext& context);
  ~AnalyticsServiceComponent() override;

  void OnAllComponentsAreStopping() override;

  Service& service() noexcept { return *service_; }


  static userver::yaml_config::Schema GetStaticConfigSchema();

 private:
  std::unique_ptr<Service> service_;
};

}  // namespace example::analytics_service::app