// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/service.generated.hpp"

#include <chrono>
#include <cstdlib>
#include <exception>
#include <mutex>
#include <vector>
#include <stdexcept>
#include <string>
#include <string_view>

#include <userver/yaml_config/merge_schemas.hpp>
#include <userver/engine/mutex.hpp>
#include <userver/utils/async.hpp>

#include <servicelib/runtime/environment_variable.hpp>

#include "analyticsservice/internal/app/service.hpp"

namespace example::analytics_service::app {

ServiceGenerated::ServiceGenerated(
    userver::utils::statistics::Storage& statistics_storage,
    const userver::components::ComponentContext& component_context)
    : component_context_(component_context),
      metrics_(statistics_storage),
      use_noop_logs_(servicelib::EnvironmentFlagEnabled("SERVICELIB_NOOP_LOGS")),
      use_noop_metrics_(servicelib::EnvironmentFlagEnabled("SERVICELIB_NOOP_METRICS")),
      use_noop_tracing_(servicelib::EnvironmentFlagEnabled("SERVICELIB_NOOP_TRACING")) {}

ServiceGenerated::~ServiceGenerated() { stop(); }

void ServiceGenerated::start() {
  try {
    const servicelib::Context context;
    serviceInit();
    initMakers();
    customMakersInit(context);
    initRuntime(context);
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    user_lifecycle_started_ = true;
    serviceStarted();
  } catch (...) {
    stop();
    releaseRuntime();
    throw;
  }
}

void ServiceGenerated::initMakers() {
  makers_.advance_cycle_analytics = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::MapStreamConfig& config) {
    return functions::MakeAdvanceCycleAnalytics(
        std::move(context), environment, config);
  };
  makers_.analytics_orders_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeAnalyticsOrdersSource(
        std::move(context), environment, config);
  };
  makers_.analytics_payments_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeAnalyticsPaymentsSource(
        std::move(context), environment, config);
  };
  makers_.analytics_schedule_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CronEndpointConfig& config) {
    return functions::MakeAnalyticsScheduleSource(
        std::move(context), environment, config);
  };
  makers_.analytics_shipments_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeAnalyticsShipmentsSource(
        std::move(context), environment, config);
  };
  makers_.complete_cycle_analytics = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::FilterStreamConfig& config) {
    return functions::MakeCompleteCycleAnalytics(
        std::move(context), environment, config);
  };
  makers_.continue_cycle_analytics = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::FilterStreamConfig& config) {
    return functions::MakeContinueCycleAnalytics(
        std::move(context), environment, config);
  };
  makers_.count_order_processed = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ProcessStreamConfig& config) {
    return functions::MakeCountOrderProcessed(
        std::move(context), environment, config);
  };
  makers_.cycle_analytics_input_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeCycleAnalyticsInputSource(
        std::move(context), environment, config);
  };
  makers_.cycle_analytics_result_sink = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeCycleAnalyticsResultSink(
        std::move(context), environment, config);
  };
  makers_.high_value_analytics_sink = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeHighValueAnalyticsSink(
        std::move(context), environment, config);
  };
  makers_.join_order_payment_analytics = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::JoinStreamConfig& config) {
    return functions::MakeJoinOrderPaymentAnalytics(
        std::move(context), environment, config);
  };
  makers_.joined_analytics_sink = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeJoinedAnalyticsSink(
        std::move(context), environment, config);
  };
  makers_.key_orders_for_join = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KeyByStreamConfig& config) {
    return functions::MakeKeyOrdersForJoin(
        std::move(context), environment, config);
  };
  makers_.key_orders_for_multi_join = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KeyByStreamConfig& config) {
    return functions::MakeKeyOrdersForMultiJoin(
        std::move(context), environment, config);
  };
  makers_.key_payments_for_join = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KeyByStreamConfig& config) {
    return functions::MakeKeyPaymentsForJoin(
        std::move(context), environment, config);
  };
  makers_.key_payments_for_multi_join = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KeyByStreamConfig& config) {
    return functions::MakeKeyPaymentsForMultiJoin(
        std::move(context), environment, config);
  };
  makers_.key_shipments_for_multi_join = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KeyByStreamConfig& config) {
    return functions::MakeKeyShipmentsForMultiJoin(
        std::move(context), environment, config);
  };
  makers_.multi_join_analytics_events = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::MultiJoinStreamConfig& config) {
    return functions::MakeMultiJoinAnalyticsEvents(
        std::move(context), environment, config);
  };
  makers_.order_processed_endpoint_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KafkaEndpointConfig& config) {
    return functions::MakeOrderProcessedEndpointSource(
        std::move(context), environment, config);
  };
  makers_.route_analytics_result = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CaseStreamConfig& config) {
    return functions::MakeRouteAnalyticsResult(
        std::move(context), environment, config);
  };
  makers_.standard_analytics_sink = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeStandardAnalyticsSink(
        std::move(context), environment, config);
  };
}

void ServiceGenerated::initInfrastructure(
    servicelib::Context context, const config::Config& cfg) {
  (void)context;
  (void)cfg;
}

void ServiceGenerated::initFunctions(
    servicelib::Context context, const config::Config& cfg) {
  if (!makers_.advance_cycle_analytics) {
    throw std::logic_error("function maker AdvanceCycleAnalytics is not configured");
  }
  if (!makers_.analytics_orders_source) {
    throw std::logic_error("function maker AnalyticsOrdersSource is not configured");
  }
  if (!makers_.analytics_payments_source) {
    throw std::logic_error("function maker AnalyticsPaymentsSource is not configured");
  }
  if (!makers_.analytics_schedule_source) {
    throw std::logic_error("function maker AnalyticsScheduleSource is not configured");
  }
  if (!makers_.analytics_shipments_source) {
    throw std::logic_error("function maker AnalyticsShipmentsSource is not configured");
  }
  if (!makers_.complete_cycle_analytics) {
    throw std::logic_error("function maker CompleteCycleAnalytics is not configured");
  }
  if (!makers_.continue_cycle_analytics) {
    throw std::logic_error("function maker ContinueCycleAnalytics is not configured");
  }
  if (!makers_.count_order_processed) {
    throw std::logic_error("function maker CountOrderProcessed is not configured");
  }
  if (!makers_.cycle_analytics_input_source) {
    throw std::logic_error("function maker CycleAnalyticsInputSource is not configured");
  }
  if (!makers_.cycle_analytics_result_sink) {
    throw std::logic_error("function maker CycleAnalyticsResultSink is not configured");
  }
  if (!makers_.high_value_analytics_sink) {
    throw std::logic_error("function maker HighValueAnalyticsSink is not configured");
  }
  if (!makers_.join_order_payment_analytics) {
    throw std::logic_error("function maker JoinOrderPaymentAnalytics is not configured");
  }
  if (!makers_.joined_analytics_sink) {
    throw std::logic_error("function maker JoinedAnalyticsSink is not configured");
  }
  if (!makers_.key_orders_for_join) {
    throw std::logic_error("function maker KeyOrdersForJoin is not configured");
  }
  if (!makers_.key_orders_for_multi_join) {
    throw std::logic_error("function maker KeyOrdersForMultiJoin is not configured");
  }
  if (!makers_.key_payments_for_join) {
    throw std::logic_error("function maker KeyPaymentsForJoin is not configured");
  }
  if (!makers_.key_payments_for_multi_join) {
    throw std::logic_error("function maker KeyPaymentsForMultiJoin is not configured");
  }
  if (!makers_.key_shipments_for_multi_join) {
    throw std::logic_error("function maker KeyShipmentsForMultiJoin is not configured");
  }
  if (!makers_.multi_join_analytics_events) {
    throw std::logic_error("function maker MultiJoinAnalyticsEvents is not configured");
  }
  if (!makers_.order_processed_endpoint_source) {
    throw std::logic_error("function maker OrderProcessedEndpointSource is not configured");
  }
  if (!makers_.route_analytics_result) {
    throw std::logic_error("function maker RouteAnalyticsResult is not configured");
  }
  if (!makers_.standard_analytics_sink) {
    throw std::logic_error("function maker StandardAnalyticsSink is not configured");
  }
  std::stop_source maker_cancellation;
  userver::engine::Mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<userver::engine::TaskWithResult<void>> maker_tasks;
  maker_tasks.reserve(22);
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-advance_cycle_analytics", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.advance_cycle_analytics(
              maker_context, *this, cfg.streams.advanceCycleAnalytics);
          functions_.advance_cycle_analytics = maker_task.Get();
          if (!functions_.advance_cycle_analytics) {
            throw std::logic_error("function maker AdvanceCycleAnalytics returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-analytics_orders_source", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.analytics_orders_source(
              maker_context, *this, cfg.endpoints.analyticsOrders);
          functions_.analytics_orders_source = maker_task.Get();
          if (!functions_.analytics_orders_source) {
            throw std::logic_error("function maker AnalyticsOrdersSource returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-analytics_payments_source", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.analytics_payments_source(
              maker_context, *this, cfg.endpoints.analyticsPayments);
          functions_.analytics_payments_source = maker_task.Get();
          if (!functions_.analytics_payments_source) {
            throw std::logic_error("function maker AnalyticsPaymentsSource returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-analytics_schedule_source", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.analytics_schedule_source(
              maker_context, *this, cfg.endpoints.analyticsSchedule);
          functions_.analytics_schedule_source = maker_task.Get();
          if (!functions_.analytics_schedule_source) {
            throw std::logic_error("function maker AnalyticsScheduleSource returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-analytics_shipments_source", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.analytics_shipments_source(
              maker_context, *this, cfg.endpoints.analyticsShipments);
          functions_.analytics_shipments_source = maker_task.Get();
          if (!functions_.analytics_shipments_source) {
            throw std::logic_error("function maker AnalyticsShipmentsSource returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-complete_cycle_analytics", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.complete_cycle_analytics(
              maker_context, *this, cfg.streams.completeCycleAnalytics);
          functions_.complete_cycle_analytics = maker_task.Get();
          if (!functions_.complete_cycle_analytics) {
            throw std::logic_error("function maker CompleteCycleAnalytics returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-continue_cycle_analytics", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.continue_cycle_analytics(
              maker_context, *this, cfg.streams.continueCycleAnalytics);
          functions_.continue_cycle_analytics = maker_task.Get();
          if (!functions_.continue_cycle_analytics) {
            throw std::logic_error("function maker ContinueCycleAnalytics returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-count_order_processed", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.count_order_processed(
              maker_context, *this, cfg.streams.countOrderProcessed);
          functions_.count_order_processed = maker_task.Get();
          if (!functions_.count_order_processed) {
            throw std::logic_error("function maker CountOrderProcessed returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-cycle_analytics_input_source", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.cycle_analytics_input_source(
              maker_context, *this, cfg.endpoints.cycleAnalyticsInput);
          functions_.cycle_analytics_input_source = maker_task.Get();
          if (!functions_.cycle_analytics_input_source) {
            throw std::logic_error("function maker CycleAnalyticsInputSource returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-cycle_analytics_result_sink", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.cycle_analytics_result_sink(
              maker_context, *this, cfg.endpoints.cycleAnalyticsResult);
          functions_.cycle_analytics_result_sink = maker_task.Get();
          if (!functions_.cycle_analytics_result_sink) {
            throw std::logic_error("function maker CycleAnalyticsResultSink returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-high_value_analytics_sink", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.high_value_analytics_sink(
              maker_context, *this, cfg.endpoints.highValueAnalytics);
          functions_.high_value_analytics_sink = maker_task.Get();
          if (!functions_.high_value_analytics_sink) {
            throw std::logic_error("function maker HighValueAnalyticsSink returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-join_order_payment_analytics", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.join_order_payment_analytics(
              maker_context, *this, cfg.streams.joinOrderPaymentAnalytics);
          functions_.join_order_payment_analytics = maker_task.Get();
          if (!functions_.join_order_payment_analytics) {
            throw std::logic_error("function maker JoinOrderPaymentAnalytics returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-joined_analytics_sink", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.joined_analytics_sink(
              maker_context, *this, cfg.endpoints.joinedAnalytics);
          functions_.joined_analytics_sink = maker_task.Get();
          if (!functions_.joined_analytics_sink) {
            throw std::logic_error("function maker JoinedAnalyticsSink returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-key_orders_for_join", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.key_orders_for_join(
              maker_context, *this, cfg.streams.keyOrdersForJoin);
          functions_.key_orders_for_join = maker_task.Get();
          if (!functions_.key_orders_for_join) {
            throw std::logic_error("function maker KeyOrdersForJoin returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-key_orders_for_multi_join", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.key_orders_for_multi_join(
              maker_context, *this, cfg.streams.keyOrdersForMultiJoin);
          functions_.key_orders_for_multi_join = maker_task.Get();
          if (!functions_.key_orders_for_multi_join) {
            throw std::logic_error("function maker KeyOrdersForMultiJoin returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-key_payments_for_join", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.key_payments_for_join(
              maker_context, *this, cfg.streams.keyPaymentsForJoin);
          functions_.key_payments_for_join = maker_task.Get();
          if (!functions_.key_payments_for_join) {
            throw std::logic_error("function maker KeyPaymentsForJoin returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-key_payments_for_multi_join", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.key_payments_for_multi_join(
              maker_context, *this, cfg.streams.keyPaymentsForMultiJoin);
          functions_.key_payments_for_multi_join = maker_task.Get();
          if (!functions_.key_payments_for_multi_join) {
            throw std::logic_error("function maker KeyPaymentsForMultiJoin returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-key_shipments_for_multi_join", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.key_shipments_for_multi_join(
              maker_context, *this, cfg.streams.keyShipmentsForMultiJoin);
          functions_.key_shipments_for_multi_join = maker_task.Get();
          if (!functions_.key_shipments_for_multi_join) {
            throw std::logic_error("function maker KeyShipmentsForMultiJoin returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-multi_join_analytics_events", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.multi_join_analytics_events(
              maker_context, *this, cfg.streams.multiJoinAnalyticsEvents);
          functions_.multi_join_analytics_events = maker_task.Get();
          if (!functions_.multi_join_analytics_events) {
            throw std::logic_error("function maker MultiJoinAnalyticsEvents returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-order_processed_endpoint_source", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.order_processed_endpoint_source(
              maker_context, *this, cfg.endpoints.orderProcessed);
          functions_.order_processed_endpoint_source = maker_task.Get();
          if (!functions_.order_processed_endpoint_source) {
            throw std::logic_error("function maker OrderProcessedEndpointSource returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-route_analytics_result", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.route_analytics_result(
              maker_context, *this, cfg.streams.routeAnalyticsResult);
          functions_.route_analytics_result = maker_task.Get();
          if (!functions_.route_analytics_result) {
            throw std::logic_error("function maker RouteAnalyticsResult returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-standard_analytics_sink", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.standard_analytics_sink(
              maker_context, *this, cfg.endpoints.standardAnalytics);
          functions_.standard_analytics_sink = maker_task.Get();
          if (!functions_.standard_analytics_sink) {
            throw std::logic_error("function maker StandardAnalyticsSink returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));

  for (auto& task : maker_tasks) {
    try {
      task.Get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}

void ServiceGenerated::initRuntime(servicelib::Context context) {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  initInfrastructure(context, *config_snapshot);
  initFunctions(context, *config_snapshot);
  customFunctionsInit(context);
  initStreams(*config_snapshot);
  initDataSinks(*config_snapshot);
  initDataSources(*config_snapshot);

}

void ServiceGenerated::initStreams(const config::Config& cfg) {
  streams_.cycle_analytics_link = &servicelib::makeCycleLinkStreamRef<example::analytics_service::types::AnalyticsEvent, ServiceGenerated>(cfg.streams.cycleAnalyticsLink, nullptr, *this);
  streams_.analytics_schedule = &servicelib::makeInputStreamRef<std::string, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsSchedule, nullptr, *this);
  streams_.consume_order_processed = &servicelib::makeInputStreamRef<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr, ServiceGenerated>(cfg.streams.consumeOrderProcessed, nullptr, *this);
  auto& count_order_processed = (*streams_.consume_order_processed).process(cfg.streams.countOrderProcessed, servicelib::StreamType<example::model::types::OrderProcessed>{}, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(std::ref(*functions_.count_order_processed)));
  streams_.count_order_processed = std::addressof(count_order_processed);
  streams_.analytics_orders = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsOrders, nullptr, *this);
  streams_.analytics_payments = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsPayments, nullptr, *this);
  streams_.analytics_shipments = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsShipments, nullptr, *this);
  auto& split_analytics_orders = (*streams_.analytics_orders).template split<2>(cfg.streams.splitAnalyticsOrders);
  streams_.split_analytics_orders = std::addressof(split_analytics_orders);
  auto& split_analytics_payments = (*streams_.analytics_payments).template split<2>(cfg.streams.splitAnalyticsPayments);
  streams_.split_analytics_payments = std::addressof(split_analytics_payments);
  streams_.cycle_analytics_input = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.cycleAnalyticsInput, nullptr, *this);
  auto& merge_cycle_analytics = (*streams_.cycle_analytics_input).merge(cfg.streams.mergeCycleAnalytics, (*streams_.cycle_analytics_link));
  streams_.merge_cycle_analytics = std::addressof(merge_cycle_analytics);
  auto& advance_cycle_analytics = merge_cycle_analytics.map(cfg.streams.advanceCycleAnalytics, servicelib::StreamType<example::analytics_service::types::AnalyticsEvent>{}, servicelib::StreamFunction(std::ref(*functions_.advance_cycle_analytics)));
  streams_.advance_cycle_analytics = std::addressof(advance_cycle_analytics);
  auto& split_cycle_analytics = advance_cycle_analytics.template split<2>(cfg.streams.splitCycleAnalytics);
  streams_.split_cycle_analytics = std::addressof(split_cycle_analytics);
  auto& complete_cycle_analytics = split_cycle_analytics.template get<0>().filter(cfg.streams.completeCycleAnalytics, servicelib::StreamFunction(std::ref(*functions_.complete_cycle_analytics)));
  streams_.complete_cycle_analytics = std::addressof(complete_cycle_analytics);
  auto& continue_cycle_analytics = split_cycle_analytics.template get<1>().filter(cfg.streams.continueCycleAnalytics, servicelib::StreamFunction(std::ref(*functions_.continue_cycle_analytics)));
  streams_.continue_cycle_analytics = std::addressof(continue_cycle_analytics);
  [[maybe_unused]] auto& write_cycle_analytics = complete_cycle_analytics.sink(cfg.streams.writeCycleAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteCycleAnalyticsSinkBinding::Function{&bindings_.write_cycle_analytics}));
  streams_.write_cycle_analytics = write_cycle_analytics;
  auto& key_orders_for_join = split_analytics_orders.template get<0>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyOrdersForJoin, servicelib::StreamFunction(std::ref(*functions_.key_orders_for_join)));
  streams_.key_orders_for_join = std::addressof(key_orders_for_join);
  auto& key_payments_for_join = split_analytics_payments.template get<0>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyPaymentsForJoin, servicelib::StreamFunction(std::ref(*functions_.key_payments_for_join)));
  streams_.key_payments_for_join = std::addressof(key_payments_for_join);
  auto& join_order_payment_analytics = key_orders_for_join.join(cfg.streams.joinOrderPaymentAnalytics, key_payments_for_join, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::Inner{}, servicelib::InMemory_Strategy{}, servicelib::StreamFunction(std::ref(*functions_.join_order_payment_analytics)));
  streams_.join_order_payment_analytics = std::addressof(join_order_payment_analytics);
  [[maybe_unused]] auto& write_joined_analytics = join_order_payment_analytics.sink(cfg.streams.writeJoinedAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteJoinedAnalyticsSinkBinding::Function{&bindings_.write_joined_analytics}));
  streams_.write_joined_analytics = write_joined_analytics;
  auto& key_orders_for_multi_join = split_analytics_orders.template get<1>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyOrdersForMultiJoin, servicelib::StreamFunction(std::ref(*functions_.key_orders_for_multi_join)));
  streams_.key_orders_for_multi_join = std::addressof(key_orders_for_multi_join);
  auto& key_payments_for_multi_join = split_analytics_payments.template get<1>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyPaymentsForMultiJoin, servicelib::StreamFunction(std::ref(*functions_.key_payments_for_multi_join)));
  streams_.key_payments_for_multi_join = std::addressof(key_payments_for_multi_join);
  auto& key_shipments_for_multi_join = (*streams_.analytics_shipments).template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyShipmentsForMultiJoin, servicelib::StreamFunction(std::ref(*functions_.key_shipments_for_multi_join)));
  streams_.key_shipments_for_multi_join = std::addressof(key_shipments_for_multi_join);
  auto& multi_join_analytics_events = key_orders_for_multi_join.multiJoin(cfg.streams.multiJoinAnalyticsEvents, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::InMemory_Strategy{}, servicelib::StreamFunction(std::ref(*functions_.multi_join_analytics_events)), key_payments_for_multi_join, key_shipments_for_multi_join);
  streams_.multi_join_analytics_events = std::addressof(multi_join_analytics_events);
  auto& route_analytics_result = multi_join_analytics_events.template case_<2>(cfg.streams.routeAnalyticsResult, servicelib::StreamFunction(std::ref(*functions_.route_analytics_result)));
  streams_.route_analytics_result = std::addressof(route_analytics_result);
  route_analytics_result.template get<0>().configure(cfg.streams.highValueAnalytics, nullptr, this);
  streams_.high_value_analytics = std::addressof(route_analytics_result.template get<0>());
  route_analytics_result.template get<1>().configure(cfg.streams.standardAnalytics, nullptr, this);
  streams_.standard_analytics = std::addressof(route_analytics_result.template get<1>());
  [[maybe_unused]] auto& write_high_value_analytics = route_analytics_result.template get<0>().sink(cfg.streams.writeHighValueAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteHighValueAnalyticsSinkBinding::Function{&bindings_.write_high_value_analytics}));
  streams_.write_high_value_analytics = write_high_value_analytics;
  [[maybe_unused]] auto& write_standard_analytics = route_analytics_result.template get<1>().sink(cfg.streams.writeStandardAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteStandardAnalyticsSinkBinding::Function{&bindings_.write_standard_analytics}));
  streams_.write_standard_analytics = write_standard_analytics;
  streams_.consume_order_processed->setSource(count_order_processed);
  streams_.cycle_analytics_link->setSource(continue_cycle_analytics);
}

void ServiceGenerated::initDataSinks(const config::Config& cfg) {
  (void)cfg;



  endpoints_.write_cycle_analytics =
      std::make_shared<WriteCycleAnalyticsCustomSinkEndpoint>(
          streams_.write_cycle_analytics.get(),
          *functions_.cycle_analytics_result_sink);
  bindings_.write_cycle_analytics.consume =
      [endpoint = endpoints_.write_cycle_analytics.get()](
          servicelib::MessageContext context, const example::analytics_service::types::AnalyticsEvent& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::analytics_service::types::AnalyticsEvent>::make(value));
      };
  registerDataSink(endpoints_.write_cycle_analytics);
  endpoints_.write_joined_analytics =
      std::make_shared<WriteJoinedAnalyticsCustomSinkEndpoint>(
          streams_.write_joined_analytics.get(),
          *functions_.joined_analytics_sink);
  bindings_.write_joined_analytics.consume =
      [endpoint = endpoints_.write_joined_analytics.get()](
          servicelib::MessageContext context, const example::analytics_service::types::AnalyticsResult& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      };
  registerDataSink(endpoints_.write_joined_analytics);
  endpoints_.write_high_value_analytics =
      std::make_shared<WriteHighValueAnalyticsCustomSinkEndpoint>(
          streams_.write_high_value_analytics.get(),
          *functions_.high_value_analytics_sink);
  bindings_.write_high_value_analytics.consume =
      [endpoint = endpoints_.write_high_value_analytics.get()](
          servicelib::MessageContext context, const example::analytics_service::types::AnalyticsResult& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      };
  registerDataSink(endpoints_.write_high_value_analytics);
  endpoints_.write_standard_analytics =
      std::make_shared<WriteStandardAnalyticsCustomSinkEndpoint>(
          streams_.write_standard_analytics.get(),
          *functions_.standard_analytics_sink);
  bindings_.write_standard_analytics.consume =
      [endpoint = endpoints_.write_standard_analytics.get()](
          servicelib::MessageContext context, const example::analytics_service::types::AnalyticsResult& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      };
  registerDataSink(endpoints_.write_standard_analytics);
}

void ServiceGenerated::initDataSources(
    const config::Config& cfg) {
  (void)cfg;


  connectors_.consume_order_processed_consumer =
      std::make_unique<ConsumeOrderProcessedKafkaConsumerOwner>(
          component_context_
              .FindComponent<userver::kafka::ConsumerComponent>(
                  "kafka-consumer-order-events"),
          cfg.endpoints.orderProcessed.topic);
  endpoints_.consume_order_processed = ConsumeOrderProcessedKafkaSourceEndpoint::make(
      *this, *streams_.consume_order_processed, connectors_.consume_order_processed_consumer->client,
      *functions_.order_processed_endpoint_source);
  registerDataSource(endpoints_.consume_order_processed);

  endpoints_.analytics_orders = AnalyticsOrdersCustomSourceEndpoint::make(
      *this, *streams_.analytics_orders,
      *functions_.analytics_orders_source,
      *functions_.analytics_orders_source);
  registerDataSource(endpoints_.analytics_orders);
  endpoints_.analytics_payments = AnalyticsPaymentsCustomSourceEndpoint::make(
      *this, *streams_.analytics_payments,
      *functions_.analytics_payments_source,
      *functions_.analytics_payments_source);
  registerDataSource(endpoints_.analytics_payments);
  endpoints_.analytics_shipments = AnalyticsShipmentsCustomSourceEndpoint::make(
      *this, *streams_.analytics_shipments,
      *functions_.analytics_shipments_source,
      *functions_.analytics_shipments_source);
  registerDataSource(endpoints_.analytics_shipments);
  endpoints_.cycle_analytics_input = CycleAnalyticsInputCustomSourceEndpoint::make(
      *this, *streams_.cycle_analytics_input,
      *functions_.cycle_analytics_input_source,
      *functions_.cycle_analytics_input_source);
  registerDataSource(endpoints_.cycle_analytics_input);
  connectors_.local_cron_cron_source =
      servicelib::datasource::cron::LibcronDataSource::make(
          *this, cfg.dataConnectors.localCron.id);
  endpoints_.analytics_schedule =
      servicelib::datasource::cron::Endpoint::make(
          *this, *streams_.analytics_schedule, *functions_.analytics_schedule_source);
  connectors_.local_cron_cron_source->addEndpoint(endpoints_.analytics_schedule);
  registerDataSource(connectors_.local_cron_cron_source);
}


void ServiceGenerated::stop() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (user_lifecycle_started_) {
      user_lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop();
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
  releaseRuntime();
}

void ServiceGenerated::releaseRuntime() noexcept {
  // ServiceApp::stop() has already stopped and released the runtime-owned
  // graph. Generated fields are only typed construction/runtime views.
  connectors_ = {};
  endpoints_ = {};
  bindings_ = {};
  streams_ = {};
  functions_ = {};
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return use_noop_logs_
             ? servicelib::log::NoopLogger::instance()
             : servicelib::telemetry::userver_adapter::UserverLogger::instance();
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return use_noop_metrics_ ? servicelib::metrics::NoopMetrics::instance()
                           : metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return use_noop_tracing_
             ? nullptr
             : &servicelib::telemetry::userver_adapter::UserverTracing::instance();
}

AnalyticsServiceComponent::AnalyticsServiceComponent(
    const userver::components::ComponentConfig& component_config,
    const userver::components::ComponentContext& context)
    : ComponentBase(component_config, context),
      service_(std::make_unique<Service>(
          context.FindComponent<userver::components::StatisticsStorage>()
              .GetStorage(),
          context)) {
  context.FindComponent<RuntimeConfigComponent>();
  service_->start();
}

AnalyticsServiceComponent::~AnalyticsServiceComponent() { service_->stop(); }

void AnalyticsServiceComponent::OnAllComponentsAreStopping() { service_->stop(); }



userver::yaml_config::Schema AnalyticsServiceComponent::GetStaticConfigSchema() {
  return userver::yaml_config::MergeSchemas<
      userver::components::ComponentBase>(R"(
type: object
description: Config-driven servicelib service.
additionalProperties: false
properties: {}
)");
}

}  // namespace example::analytics_service::app