// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <atomic>

#include <functional>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/components/statistics_storage.hpp>
#include <userver/engine/task/task_with_result.hpp>


#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/component.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/runtime/telemetry/userver/log.hpp>
#include <servicelib/runtime/telemetry/userver/metrics.hpp>
#include <servicelib/runtime/telemetry/userver/tracing.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/kafka/userver.hpp>
#include <userver/kafka/consumer_component.hpp>
#include <servicelib/datasource/localsource/custom.hpp>
#include <servicelib/datasource/cron/libcron.hpp>
#include <servicelib/datasink/localsink/custom.hpp>

#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <model_cpp/include/example/model/types/automation_job.hpp>
#include <model_cpp/include/example/model/types/order_processed.hpp>

#include "analyticsservice/internal/app/pipelines/analytics.generated.hpp"
#include "analyticsservice/internal/app/pipelines/analytics_sources.generated.hpp"
#include "analyticsservice/internal/app/pipelines/cycle_analytics.generated.hpp"
#include "analyticsservice/internal/app/pipelines/join_analytics.generated.hpp"
#include "analyticsservice/internal/app/pipelines/multi_join_analytics.generated.hpp"
#include "analyticsservice/internal/app/pipelines/substream_analytics.generated.hpp"


namespace example::analytics_service::app {

// Business functions may retain handles without retaining the graph itself.
template <typename T, typename R>
class SubStreamHandle final : public servicelib::ISubStream<T, R> {
 public:
  void bind(const std::shared_ptr<servicelib::ISubStream<T, R>>& stream) {
    stream_.store(stream, std::memory_order_release);
  }
  void consume(servicelib::MessageContext context, servicelib::Payload<T> value,
               std::shared_ptr<servicelib::SubStreamCollector<R>> collector) override {
    auto stream = stream_.load(std::memory_order_acquire).lock();
    if (!stream) {
      throw std::logic_error("SubStream is not available: service is not running");
    }
    stream->consume(std::move(context), std::move(value), std::move(collector));
  }
 private:
  std::atomic<std::weak_ptr<servicelib::ISubStream<T, R>>> stream_;
};


struct DataTypes final {
  template <typename>
  struct DataType {};
};

using RuntimeConfigComponent =
    servicelib::config::ServicelibRuntimeComponent<config::Config>;

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  explicit ServiceGenerated(
      userver::utils::statistics::Storage& statistics_storage,
      const userver::components::ComponentContext& component_context);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

  std::shared_ptr<servicelib::ISubStream<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult>>
  getAnalyzeAnalyticsSubstreamSubStream() const noexcept {
    return analyze_analytics_substream_substream_;
  }


 protected:
  struct ServiceMakers final : AnalyticsPipelineMakers, AnalyticsSourcesPipelineMakers, CycleAnalyticsPipelineMakers, JoinAnalyticsPipelineMakers, MultiJoinAnalyticsPipelineMakers, SubstreamAnalyticsPipelineMakers {
  };
  struct ServiceFunctions final : AnalyticsPipelineFunctions, AnalyticsSourcesPipelineFunctions, CycleAnalyticsPipelineFunctions, JoinAnalyticsPipelineFunctions, MultiJoinAnalyticsPipelineFunctions, SubstreamAnalyticsPipelineFunctions {};

  ServiceMakers makers_;
  ServiceFunctions functions_;

  virtual void customMakersInit(servicelib::Context) {}
  virtual void customFunctionsInit(servicelib::Context) {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  void initMakers();
  void initInfrastructure(servicelib::Context context,
                          const config::Config& config);
  void initFunctions(servicelib::Context context, const config::Config& config);
  void initRuntime(servicelib::Context context);
  void initStreams(const config::Config& config);
  void initDataSinks(const config::Config& config);
  void initDataSources(const config::Config& config);
  void releaseRuntime() noexcept;

  using AnalyzeAnalyticsSubstreamSubStream =
      servicelib::SubStream<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult, ServiceGenerated>;
  std::shared_ptr<SubStreamHandle<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult>>
      analyze_analytics_substream_substream_ =
          std::make_shared<SubStreamHandle<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult>>();

  using AnalyticsScheduleInput =
      servicelib::InputStream<std::string, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using ConsumeOrderProcessedInput =
      servicelib::InputStream<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr,
                              ServiceGenerated>;
  using AnalyticsOrdersInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using AnalyticsPaymentsInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using AnalyticsShipmentsInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using CycleAnalyticsInputInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using SubstreamAnalyticsInputInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;

  using CycleAnalyticsLinkCycle =
      servicelib::CycleLinkStream<example::analytics_service::types::AnalyticsEvent, ServiceGenerated>;

  struct ServiceStreams final : AnalyticsPipelineStreams, AnalyticsSourcesPipelineStreams, CycleAnalyticsPipelineStreams, JoinAnalyticsPipelineStreams, MultiJoinAnalyticsPipelineStreams, SubstreamAnalyticsPipelineStreams {};
  ServiceStreams streams_;

  struct WriteCycleAnalyticsSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::analytics_service::types::AnalyticsEvent&)>
        consume;
    struct Function final {
      WriteCycleAnalyticsSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsEvent& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct WriteJoinedAnalyticsSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::analytics_service::types::AnalyticsResult&)>
        consume;
    struct Function final {
      WriteJoinedAnalyticsSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct WriteHighValueAnalyticsSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::analytics_service::types::AnalyticsResult&)>
        consume;
    struct Function final {
      WriteHighValueAnalyticsSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct WriteStandardAnalyticsSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::analytics_service::types::AnalyticsResult&)>
        consume;
    struct Function final {
      WriteStandardAnalyticsSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct WriteSubstreamAnalyticsSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::analytics_service::types::AnalyticsResult&)>
        consume;
    struct Function final {
      WriteSubstreamAnalyticsSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };

  struct ServiceBindings final {
    WriteCycleAnalyticsSinkBinding write_cycle_analytics;
    WriteJoinedAnalyticsSinkBinding write_joined_analytics;
    WriteHighValueAnalyticsSinkBinding write_high_value_analytics;
    WriteStandardAnalyticsSinkBinding write_standard_analytics;
    WriteSubstreamAnalyticsSinkBinding write_substream_analytics;
  };
  ServiceBindings bindings_;







  using ConsumeOrderProcessedKafkaSourceEndpoint =
      servicelib::datasource::kafka::Endpoint<
          example::model::types::OrderProcessed, example::model::types::OrderProcessed, functions::OrderProcessedEndpointSource, std::exception_ptr>;
  struct ConsumeOrderProcessedKafkaConsumerOwner final {
    ConsumeOrderProcessedKafkaConsumerOwner(
        userver::kafka::ConsumerComponent& component, std::string topic)
        : scope(component.GetConsumer()),
          client(scope, std::move(topic)) {}

    userver::kafka::ConsumerScope scope;
    servicelib::datasource::kafka::UserverConsumerClient client;
  };


  using AnalyticsOrdersCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::AnalyticsOrdersSource, std::exception_ptr>;
  using AnalyticsPaymentsCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::AnalyticsPaymentsSource, std::exception_ptr>;
  using AnalyticsShipmentsCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::AnalyticsShipmentsSource, std::exception_ptr>;
  using CycleAnalyticsInputCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::CycleAnalyticsInputSource, std::exception_ptr>;
  using SubstreamAnalyticsInputCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::SubstreamAnalyticsInputSource, std::exception_ptr>;

  using WriteCycleAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::CycleAnalyticsResultSink, std::exception_ptr>;
  using WriteJoinedAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::JoinedAnalyticsSink, std::exception_ptr>;
  using WriteHighValueAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::HighValueAnalyticsSink, std::exception_ptr>;
  using WriteStandardAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::StandardAnalyticsSink, std::exception_ptr>;
  using WriteSubstreamAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::SubstreamAnalyticsResultSink, std::exception_ptr>;


  struct ServiceEndpoints final {
    std::shared_ptr<ConsumeOrderProcessedKafkaSourceEndpoint> consume_order_processed;
    std::shared_ptr<AnalyticsOrdersCustomSourceEndpoint> analytics_orders;
    std::shared_ptr<AnalyticsPaymentsCustomSourceEndpoint> analytics_payments;
    std::shared_ptr<AnalyticsShipmentsCustomSourceEndpoint> analytics_shipments;
    std::shared_ptr<CycleAnalyticsInputCustomSourceEndpoint> cycle_analytics_input;
    std::shared_ptr<SubstreamAnalyticsInputCustomSourceEndpoint> substream_analytics_input;
    std::shared_ptr<servicelib::datasource::cron::Endpoint> analytics_schedule;
    std::shared_ptr<WriteCycleAnalyticsCustomSinkEndpoint> write_cycle_analytics;
    std::shared_ptr<WriteJoinedAnalyticsCustomSinkEndpoint> write_joined_analytics;
    std::shared_ptr<WriteHighValueAnalyticsCustomSinkEndpoint> write_high_value_analytics;
    std::shared_ptr<WriteStandardAnalyticsCustomSinkEndpoint> write_standard_analytics;
    std::shared_ptr<WriteSubstreamAnalyticsCustomSinkEndpoint> write_substream_analytics;
  };
  ServiceEndpoints endpoints_;

  struct ServiceConnectors final {
    std::unique_ptr<ConsumeOrderProcessedKafkaConsumerOwner> consume_order_processed_consumer;
    std::shared_ptr<
        servicelib::datasource::cron::LibcronDataSource> local_cron_cron_source;
  };
  ServiceConnectors connectors_;

  [[maybe_unused]] const userver::components::ComponentContext& component_context_;
  servicelib::telemetry::userver_adapter::UserverMetrics metrics_;
  bool use_noop_logs_{false};
  bool use_noop_metrics_{false};
  bool use_noop_tracing_{false};
  bool user_lifecycle_started_{false};
};

class Service;

class AnalyticsServiceComponent final : public userver::components::ComponentBase {
 public:
  static constexpr std::string_view kName = "analytics-service";

  AnalyticsServiceComponent(
      const userver::components::ComponentConfig& config,
      const userver::components::ComponentContext& context);
  ~AnalyticsServiceComponent() override;

  void OnAllComponentsAreStopping() override;

  Service& service() noexcept { return *service_; }


  static userver::yaml_config::Schema GetStaticConfigSchema();

 private:
  std::unique_ptr<Service> service_;
};

}  // namespace example::analytics_service::app