// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/service.generated.hpp"

#include <chrono>
#include <cstdlib>
#include <exception>
#include <stdexcept>
#include <string>
#include <string_view>

#include <userver/yaml_config/merge_schemas.hpp>

#include "analyticsservice/internal/app/service.hpp"

namespace example::analytics_service::app {

ServiceGenerated::ServiceGenerated(
    userver::utils::statistics::Storage& statistics_storage,
    const userver::components::ComponentContext& component_context)
    : component_context_(component_context),
      metrics_(statistics_storage),
      use_noop_metrics_(std::getenv("SERVICELIB_NOOP_METRICS") != nullptr),
      use_noop_tracing_(std::getenv("SERVICELIB_NOOP_TRACING") != nullptr) {}

ServiceGenerated::~ServiceGenerated() { stop(); }

void ServiceGenerated::start() {
  try {
    serviceInit();
    initMakers();
    customMakersInit();
    initRuntime();
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    user_lifecycle_started_ = true;
    serviceStarted();
  } catch (...) {
    stop();
    releaseRuntime();
    throw;
  }
}

void ServiceGenerated::initMakers() {
  makers_.count_order_processed = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ProcessStreamConfig& config) {
    return functions::MakeCountOrderProcessed(
        std::move(context), environment, config);
  };
  makers_.order_processed_endpoint = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KafkaEndpointConfig& config) {
    return functions::MakeOrderProcessedEndpoint(
        std::move(context), environment, config);
  };
}

void ServiceGenerated::initFunctions(const config::Config& cfg) {
  if (!makers_.count_order_processed) {
    throw std::logic_error("function maker CountOrderProcessed is not configured");
  }
  functions_.count_order_processed = makers_.count_order_processed(
      servicelib::Context{}, *this, cfg.streams.countOrderProcessed);
  if (!functions_.count_order_processed) {
    throw std::logic_error("function maker CountOrderProcessed returned null");
  }
  if (!makers_.order_processed_endpoint) {
    throw std::logic_error("function maker OrderProcessedEndpoint is not configured");
  }
  functions_.order_processed_endpoint = makers_.order_processed_endpoint(
      servicelib::Context{}, *this, cfg.endpoints.orderProcessed);
  if (!functions_.order_processed_endpoint) {
    throw std::logic_error("function maker OrderProcessedEndpoint returned null");
  }
}

void ServiceGenerated::initRuntime() {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  initFunctions(*config_snapshot);
  customFunctionsInit();
  initStreams(*config_snapshot);
  initDataSources(*config_snapshot);

}

void ServiceGenerated::initStreams(const config::Config& cfg) {
  streams_.consume_order_processed = &servicelib::makeInputStreamRef<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr, ServiceGenerated>(cfg.streams.consumeOrderProcessed, nullptr, *this);
  auto& count_order_processed = (*streams_.consume_order_processed).process(cfg.streams.countOrderProcessed, servicelib::StreamType<example::model::types::OrderProcessed>{}, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(std::ref(*functions_.count_order_processed)));
  streams_.count_order_processed = std::addressof(count_order_processed);
  streams_.consume_order_processed->setSource(count_order_processed);
}

void ServiceGenerated::initDataSources(
    const config::Config& cfg) {
  (void)cfg;


  connectors_.consume_order_processed_consumer =
      std::make_unique<ConsumeOrderProcessedKafkaConsumerOwner>(
          component_context_
              .FindComponent<userver::kafka::ConsumerComponent>(
                  "kafka-consumer-order-events"),
          cfg.endpoints.orderProcessed.topic);
  endpoints_.consume_order_processed = ConsumeOrderProcessedKafkaSourceEndpoint::make(
      *this, *streams_.consume_order_processed, connectors_.consume_order_processed_consumer->client,
      *functions_.order_processed_endpoint);
  registerDataSource(endpoints_.consume_order_processed);

}


void ServiceGenerated::stop() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (user_lifecycle_started_) {
      user_lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop();
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
  releaseRuntime();
}

void ServiceGenerated::releaseRuntime() noexcept {
  // ServiceApp::stop() has already stopped and released the runtime-owned
  // graph. Generated fields are only typed construction/runtime views.
  connectors_ = {};
  endpoints_ = {};
  bindings_ = {};
  streams_ = {};
  functions_ = {};
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return servicelib::telemetry::userver_adapter::UserverLogger::instance();
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return use_noop_metrics_ ? servicelib::metrics::NoopMetrics::instance()
                           : metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return use_noop_tracing_
             ? nullptr
             : &servicelib::telemetry::userver_adapter::UserverTracing::instance();
}

AnalyticsServiceComponent::AnalyticsServiceComponent(
    const userver::components::ComponentConfig& component_config,
    const userver::components::ComponentContext& context)
    : ComponentBase(component_config, context),
      service_(std::make_unique<Service>(
          context.FindComponent<userver::components::StatisticsStorage>()
              .GetStorage(),
          context)) {
  context.FindComponent<RuntimeConfigComponent>();
  service_->start();
}

AnalyticsServiceComponent::~AnalyticsServiceComponent() { service_->stop(); }



userver::yaml_config::Schema AnalyticsServiceComponent::GetStaticConfigSchema() {
  return userver::yaml_config::MergeSchemas<
      userver::components::ComponentBase>(R"(
type: object
description: Config-driven servicelib service.
additionalProperties: false
properties: {}
)");
}

}  // namespace example::analytics_service::app