// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/streams.generated.hpp"
#include "analyticsservice/internal/app/service.generated.hpp"
#include "analyticsservice/internal/app/functions.generated.hpp"
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>

namespace example::analytics_service::app {
void ServiceStreams::initStreams(const config::Config& cfg, ServiceGenerated& service) {
  auto& streams_ = *this;
  (void)streams_; (void)cfg; (void)service;
  streams_.cycle_analytics_link = &servicelib::makeCycleLinkStreamRef<example::analytics_service::types::AnalyticsEvent, ServiceGenerated>(cfg.streams.cycleAnalyticsLink, nullptr, service);
  streams_.analytics_schedule = &servicelib::makeInputStreamRef<std::string, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsSchedule, nullptr, service);
  streams_.consume_order_processed = &servicelib::makeInputStreamRef<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr, ServiceGenerated>(cfg.streams.consumeOrderProcessed, nullptr, service);
  streams_.analytics_orders = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsOrders, nullptr, service);
  streams_.analytics_payments = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsPayments, nullptr, service);
  streams_.analytics_shipments = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsShipments, nullptr, service);
  streams_.cycle_analytics_input = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.cycleAnalyticsInput, nullptr, service);
  streams_.analyze_analytics_substream = servicelib::makeSubStream<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult, ServiceGenerated>(cfg.streams.analyzeAnalyticsSubstream, service);
  streams_.substream_analytics_input = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.substreamAnalyticsInput, nullptr, service);

}

void ServiceStreams::build(const config::Config& cfg, ServiceGenerated& service, ServiceFunctions& functions, ServiceBindings& bindings) {
  auto& streams_ = *this;
  auto& functions_ = functions;
  auto& bindings_ = bindings;
  (void)streams_; (void)functions_; (void)bindings_; (void)cfg; (void)service;

  auto& count_order_processed = (*streams_.consume_order_processed).process(cfg.streams.countOrderProcessed, servicelib::StreamType<example::model::types::OrderProcessed>{}, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(std::ref(*functions_.count_order_processed)));
  streams_.count_order_processed = std::addressof(count_order_processed);
  auto& split_analytics_orders = (*streams_.analytics_orders).template split<2>(cfg.streams.splitAnalyticsOrders);
  streams_.split_analytics_orders = std::addressof(split_analytics_orders);
  auto& split_analytics_payments = (*streams_.analytics_payments).template split<2>(cfg.streams.splitAnalyticsPayments);
  streams_.split_analytics_payments = std::addressof(split_analytics_payments);
  auto& merge_cycle_analytics = (*streams_.cycle_analytics_input).merge(cfg.streams.mergeCycleAnalytics, (*streams_.cycle_analytics_link));
  streams_.merge_cycle_analytics = std::addressof(merge_cycle_analytics);
  auto& advance_cycle_analytics = merge_cycle_analytics.map(cfg.streams.advanceCycleAnalytics, servicelib::StreamType<example::analytics_service::types::AnalyticsEvent>{}, servicelib::StreamFunction(std::ref(*functions_.advance_cycle_analytics)));
  streams_.advance_cycle_analytics = std::addressof(advance_cycle_analytics);
  auto& split_cycle_analytics = advance_cycle_analytics.template split<2>(cfg.streams.splitCycleAnalytics);
  streams_.split_cycle_analytics = std::addressof(split_cycle_analytics);
  auto& complete_cycle_analytics = split_cycle_analytics.template get<0>().filter(cfg.streams.completeCycleAnalytics, servicelib::StreamFunction(std::ref(*functions_.complete_cycle_analytics)));
  streams_.complete_cycle_analytics = std::addressof(complete_cycle_analytics);
  auto& continue_cycle_analytics = split_cycle_analytics.template get<1>().filter(cfg.streams.continueCycleAnalytics, servicelib::StreamFunction(std::ref(*functions_.continue_cycle_analytics)));
  streams_.continue_cycle_analytics = std::addressof(continue_cycle_analytics);
  [[maybe_unused]] auto& write_cycle_analytics = complete_cycle_analytics.sink(cfg.streams.writeCycleAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteCycleAnalyticsSinkBinding::Function{&bindings_.write_cycle_analytics}));
  streams_.write_cycle_analytics = write_cycle_analytics;
  auto& key_orders_for_join = split_analytics_orders.template get<0>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyOrdersForJoin, servicelib::StreamFunction(std::ref(*functions_.key_orders_for_join)));
  streams_.key_orders_for_join = std::addressof(key_orders_for_join);
  auto& key_payments_for_join = split_analytics_payments.template get<0>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyPaymentsForJoin, servicelib::StreamFunction(std::ref(*functions_.key_payments_for_join)));
  streams_.key_payments_for_join = std::addressof(key_payments_for_join);
  auto& join_order_payment_analytics = key_orders_for_join.join(cfg.streams.joinOrderPaymentAnalytics, key_payments_for_join, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::Inner{}, servicelib::InMemory_Strategy{}, servicelib::StreamFunction(std::ref(*functions_.join_order_payment_analytics)));
  streams_.join_order_payment_analytics = std::addressof(join_order_payment_analytics);
  [[maybe_unused]] auto& write_joined_analytics = join_order_payment_analytics.sink(cfg.streams.writeJoinedAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteJoinedAnalyticsSinkBinding::Function{&bindings_.write_joined_analytics}));
  streams_.write_joined_analytics = write_joined_analytics;
  auto& key_orders_for_multi_join = split_analytics_orders.template get<1>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyOrdersForMultiJoin, servicelib::StreamFunction(std::ref(*functions_.key_orders_for_multi_join)));
  streams_.key_orders_for_multi_join = std::addressof(key_orders_for_multi_join);
  auto& key_payments_for_multi_join = split_analytics_payments.template get<1>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyPaymentsForMultiJoin, servicelib::StreamFunction(std::ref(*functions_.key_payments_for_multi_join)));
  streams_.key_payments_for_multi_join = std::addressof(key_payments_for_multi_join);
  auto& key_shipments_for_multi_join = (*streams_.analytics_shipments).template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyShipmentsForMultiJoin, servicelib::StreamFunction(std::ref(*functions_.key_shipments_for_multi_join)));
  streams_.key_shipments_for_multi_join = std::addressof(key_shipments_for_multi_join);
  auto& multi_join_analytics_events = key_orders_for_multi_join.multiJoin(cfg.streams.multiJoinAnalyticsEvents, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::InMemory_Strategy{}, servicelib::StreamFunction(std::ref(*functions_.multi_join_analytics_events)), key_payments_for_multi_join, key_shipments_for_multi_join);
  streams_.multi_join_analytics_events = std::addressof(multi_join_analytics_events);
  auto& route_analytics_result = multi_join_analytics_events.template case_<2>(cfg.streams.routeAnalyticsResult, servicelib::StreamFunction(std::ref(*functions_.route_analytics_result)));
  streams_.route_analytics_result = std::addressof(route_analytics_result);
  route_analytics_result.template get<0>().configure(cfg.streams.highValueAnalytics, nullptr, &service);
  streams_.high_value_analytics = std::addressof(route_analytics_result.template get<0>());
  route_analytics_result.template get<1>().configure(cfg.streams.standardAnalytics, nullptr, &service);
  streams_.standard_analytics = std::addressof(route_analytics_result.template get<1>());
  [[maybe_unused]] auto& write_high_value_analytics = route_analytics_result.template get<0>().sink(cfg.streams.writeHighValueAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteHighValueAnalyticsSinkBinding::Function{&bindings_.write_high_value_analytics}));
  streams_.write_high_value_analytics = write_high_value_analytics;
  [[maybe_unused]] auto& write_standard_analytics = route_analytics_result.template get<1>().sink(cfg.streams.writeStandardAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteStandardAnalyticsSinkBinding::Function{&bindings_.write_standard_analytics}));
  streams_.write_standard_analytics = write_standard_analytics;
  auto& build_substream_analytics_result = (*streams_.analyze_analytics_substream).map(cfg.streams.buildSubstreamAnalyticsResult, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::StreamFunction(std::ref(*functions_.build_substream_analytics_result)));
  streams_.build_substream_analytics_result = std::addressof(build_substream_analytics_result);
  auto& invoke_analytics_substream = (*streams_.substream_analytics_input).map(cfg.streams.invokeAnalyticsSubstream, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::StreamFunction(std::ref(*functions_.invoke_analytics_substream)));
  streams_.invoke_analytics_substream = std::addressof(invoke_analytics_substream);
  [[maybe_unused]] auto& write_substream_analytics = invoke_analytics_substream.sink(cfg.streams.writeSubstreamAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteSubstreamAnalyticsSinkBinding::Function{&bindings_.write_substream_analytics}));
  streams_.write_substream_analytics = write_substream_analytics;
  streams_.consume_order_processed->setSource(count_order_processed);
  streams_.cycle_analytics_link->setSource(continue_cycle_analytics);
  streams_.analyze_analytics_substream->setSource(build_substream_analytics_result);

}

}  // namespace example::analytics_service::app