// Code generated by servicegen. DO NOT EDIT.
#include <tuple>
#include <functional>

#include "analyticsservice/internal/app/streams.generated.hpp"
#include "analyticsservice/internal/app/service.generated.hpp"
#include "analyticsservice/internal/app/functions.generated.hpp"
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>

namespace example::analytics_service::app {
void ServiceStreams::initStreams(const config::Config& cfg, ServiceGenerated& service) {
  auto& streams_ = *this;
  (void)streams_; (void)cfg; (void)service;
  streams_.cycle_analytics_link = &servicelib::makeCycleLinkStreamRef<example::analytics_service::types::AnalyticsEvent, ServiceGenerated>(cfg.streams.cycleAnalyticsLink, nullptr, service);
  streams_.analytics_schedule = &servicelib::makeInputStreamRef<std::string, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsSchedule, nullptr, service);
  streams_.consume_order_processed = &servicelib::makeInputStreamRef<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr, ServiceGenerated>(cfg.streams.consumeOrderProcessed, nullptr, service);
  streams_.analytics_orders = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsOrders, nullptr, service);
  streams_.analytics_payments = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsPayments, nullptr, service);
  streams_.analytics_shipments = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsShipments, nullptr, service);
  streams_.cycle_analytics_input = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.cycleAnalyticsInput, nullptr, service);
  streams_.analyze_analytics_substream = servicelib::makeSubStream<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult, ServiceGenerated>(cfg.streams.analyzeAnalyticsSubstream, service);
  streams_.substream_analytics_input = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.substreamAnalyticsInput, nullptr, service);

}

void ServiceStreams::build(const config::Config& cfg, ServiceGenerated& service, ServiceFunctions& functions, ServiceBindings& bindings) {
  auto& streams_ = *this;
  auto& functions_ = functions;
  auto& bindings_ = bindings;
  (void)streams_; (void)functions_; (void)bindings_; (void)cfg; (void)service;

  using key_orders_for_join_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::KeyByImpl<std::string, example::analytics_service::types::AnalyticsEvent, decltype(std::ref(*functions_.key_orders_for_join)), servicelib::StreamConsumer<servicelib::StreamKeyValue<std::string, example::analytics_service::types::AnalyticsEvent>>>;
  using split_analytics_orders_branch_0 = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::SplitLinkImpl<example::analytics_service::types::AnalyticsEvent, key_orders_for_join_stream, ServiceGenerated>;
  using key_orders_for_multi_join_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::KeyByImpl<std::string, example::analytics_service::types::AnalyticsEvent, decltype(std::ref(*functions_.key_orders_for_multi_join)), servicelib::StreamConsumer<servicelib::StreamKeyValue<std::string, example::analytics_service::types::AnalyticsEvent>>>;
  using split_analytics_orders_branch_1 = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::SplitLinkImpl<example::analytics_service::types::AnalyticsEvent, key_orders_for_multi_join_stream, ServiceGenerated>;
  using split_analytics_orders_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::SplitImpl<std::tuple<split_analytics_orders_branch_0&, split_analytics_orders_branch_1&>>;
  using key_payments_for_join_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::KeyByImpl<std::string, example::analytics_service::types::AnalyticsEvent, decltype(std::ref(*functions_.key_payments_for_join)), servicelib::StreamConsumer<servicelib::StreamKeyValue<std::string, example::analytics_service::types::AnalyticsEvent>>>;
  using split_analytics_payments_branch_0 = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::SplitLinkImpl<example::analytics_service::types::AnalyticsEvent, key_payments_for_join_stream, ServiceGenerated>;
  using key_payments_for_multi_join_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::KeyByImpl<std::string, example::analytics_service::types::AnalyticsEvent, decltype(std::ref(*functions_.key_payments_for_multi_join)), servicelib::StreamConsumer<servicelib::StreamKeyValue<std::string, example::analytics_service::types::AnalyticsEvent>>>;
  using split_analytics_payments_branch_1 = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::SplitLinkImpl<example::analytics_service::types::AnalyticsEvent, key_payments_for_multi_join_stream, ServiceGenerated>;
  using split_analytics_payments_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::SplitImpl<std::tuple<split_analytics_payments_branch_0&, split_analytics_payments_branch_1&>>;
  using complete_cycle_analytics_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::FilterImpl<decltype(std::ref(*functions_.complete_cycle_analytics)), servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>>;
  using split_cycle_analytics_branch_0 = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::SplitLinkImpl<example::analytics_service::types::AnalyticsEvent, complete_cycle_analytics_stream, ServiceGenerated>;
  using continue_cycle_analytics_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::FilterImpl<decltype(std::ref(*functions_.continue_cycle_analytics)), servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>>;
  using split_cycle_analytics_branch_1 = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::SplitLinkImpl<example::analytics_service::types::AnalyticsEvent, continue_cycle_analytics_stream, ServiceGenerated>;
  using split_cycle_analytics_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::SplitImpl<std::tuple<split_cycle_analytics_branch_0&, split_cycle_analytics_branch_1&>>;
  using advance_cycle_analytics_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::MapImpl<example::analytics_service::types::AnalyticsEvent, decltype(std::ref(*functions_.advance_cycle_analytics)), split_cycle_analytics_stream>;
  using merge_cycle_analytics_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::MergeImpl<2, advance_cycle_analytics_stream>;
  using merge_cycle_analytics_owner_link = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::MergeLinkImpl<2, true, merge_cycle_analytics_stream>;
  using merge_cycle_analytics_reference_link = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::MergeLinkImpl<2, false, merge_cycle_analytics_stream>;
  using key_shipments_for_multi_join_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::KeyByImpl<std::string, example::analytics_service::types::AnalyticsEvent, decltype(std::ref(*functions_.key_shipments_for_multi_join)), servicelib::StreamConsumer<servicelib::StreamKeyValue<std::string, example::analytics_service::types::AnalyticsEvent>>>;
  using high_value_analytics_stream = servicelib::Stream<example::analytics_service::types::AnalyticsResult, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsResult>, ServiceGenerated>::WhenLinkImpl<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsResult>, ServiceGenerated>;
  using standard_analytics_stream = servicelib::Stream<example::analytics_service::types::AnalyticsResult, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsResult>, ServiceGenerated>::WhenLinkImpl<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsResult>, ServiceGenerated>;
  using route_analytics_result_stream = servicelib::Stream<example::analytics_service::types::AnalyticsResult, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsResult>, ServiceGenerated>::CaseImpl<std::tuple<high_value_analytics_stream&, standard_analytics_stream&>, decltype(std::ref(*functions_.route_analytics_result))>;
  using build_substream_analytics_result_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::MapImpl<example::analytics_service::types::AnalyticsResult, decltype(std::ref(*functions_.build_substream_analytics_result)), servicelib::StreamConsumer<example::analytics_service::types::AnalyticsResult>>;
  using invoke_analytics_substream_stream = servicelib::Stream<example::analytics_service::types::AnalyticsEvent, servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>, ServiceGenerated>::MapImpl<example::analytics_service::types::AnalyticsResult, decltype(std::ref(*functions_.invoke_analytics_substream)), servicelib::StreamConsumer<example::analytics_service::types::AnalyticsResult>>;
  auto& count_order_processed = (*streams_.consume_order_processed).process(cfg.streams.countOrderProcessed, servicelib::StreamType<example::model::types::OrderProcessed>{}, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(std::ref(*functions_.count_order_processed)));
  streams_.count_order_processed = std::addressof(count_order_processed);
  auto split_analytics_orders_owner = service.makeStream<split_analytics_orders_stream>(cfg.streams.splitAnalyticsOrders, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>((*streams_.analytics_orders)).getSerde(), &service, service.makeStream<split_analytics_orders_branch_0>(), service.makeStream<split_analytics_orders_branch_1>());
  auto& split_analytics_orders = *split_analytics_orders_owner;
  streams_.split_analytics_orders = std::addressof(split_analytics_orders);
  auto split_analytics_payments_owner = service.makeStream<split_analytics_payments_stream>(cfg.streams.splitAnalyticsPayments, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>((*streams_.analytics_payments)).getSerde(), &service, service.makeStream<split_analytics_payments_branch_0>(), service.makeStream<split_analytics_payments_branch_1>());
  auto& split_analytics_payments = *split_analytics_payments_owner;
  streams_.split_analytics_payments = std::addressof(split_analytics_payments);
  auto merge_cycle_analytics_owner = service.makeStream<merge_cycle_analytics_stream>(cfg.streams.mergeCycleAnalytics, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>((*streams_.cycle_analytics_input)).getSerde(), &service);
  auto& merge_cycle_analytics = *merge_cycle_analytics_owner;
  streams_.merge_cycle_analytics = std::addressof(merge_cycle_analytics);
  auto advance_cycle_analytics_owner = service.makeStream<advance_cycle_analytics_stream>(cfg.streams.advanceCycleAnalytics, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>(merge_cycle_analytics).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.advance_cycle_analytics)));
  auto& advance_cycle_analytics = *advance_cycle_analytics_owner;
  streams_.advance_cycle_analytics = std::addressof(advance_cycle_analytics);
  auto split_cycle_analytics_owner = service.makeStream<split_cycle_analytics_stream>(cfg.streams.splitCycleAnalytics, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>(advance_cycle_analytics).getSerde(), &service, service.makeStream<split_cycle_analytics_branch_0>(), service.makeStream<split_cycle_analytics_branch_1>());
  auto& split_cycle_analytics = *split_cycle_analytics_owner;
  streams_.split_cycle_analytics = std::addressof(split_cycle_analytics);
  auto complete_cycle_analytics_owner = service.makeStream<complete_cycle_analytics_stream>(cfg.streams.completeCycleAnalytics, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>(split_cycle_analytics.template get<0>()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.complete_cycle_analytics)));
  auto& complete_cycle_analytics = *complete_cycle_analytics_owner;
  streams_.complete_cycle_analytics = std::addressof(complete_cycle_analytics);
  auto continue_cycle_analytics_owner = service.makeStream<continue_cycle_analytics_stream>(cfg.streams.continueCycleAnalytics, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>(split_cycle_analytics.template get<1>()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.continue_cycle_analytics)));
  auto& continue_cycle_analytics = *continue_cycle_analytics_owner;
  streams_.continue_cycle_analytics = std::addressof(continue_cycle_analytics);
  [[maybe_unused]] auto& write_cycle_analytics = complete_cycle_analytics.sink(cfg.streams.writeCycleAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteCycleAnalyticsSinkBinding::Function{&bindings_.write_cycle_analytics}));
  streams_.write_cycle_analytics = write_cycle_analytics;
  auto key_orders_for_join_owner = service.makeStream<key_orders_for_join_stream>(cfg.streams.keyOrdersForJoin, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>(split_analytics_orders.template get<0>()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.key_orders_for_join)));
  auto& key_orders_for_join = *key_orders_for_join_owner;
  streams_.key_orders_for_join = std::addressof(key_orders_for_join);
  auto key_payments_for_join_owner = service.makeStream<key_payments_for_join_stream>(cfg.streams.keyPaymentsForJoin, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>(split_analytics_payments.template get<0>()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.key_payments_for_join)));
  auto& key_payments_for_join = *key_payments_for_join_owner;
  streams_.key_payments_for_join = std::addressof(key_payments_for_join);
  auto& join_order_payment_analytics = key_orders_for_join.join(cfg.streams.joinOrderPaymentAnalytics, key_payments_for_join, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::Inner{}, servicelib::InMemory_Strategy{}, servicelib::StreamFunction(std::ref(*functions_.join_order_payment_analytics)));
  streams_.join_order_payment_analytics = std::addressof(join_order_payment_analytics);
  [[maybe_unused]] auto& write_joined_analytics = join_order_payment_analytics.sink(cfg.streams.writeJoinedAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteJoinedAnalyticsSinkBinding::Function{&bindings_.write_joined_analytics}));
  streams_.write_joined_analytics = write_joined_analytics;
  auto key_orders_for_multi_join_owner = service.makeStream<key_orders_for_multi_join_stream>(cfg.streams.keyOrdersForMultiJoin, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>(split_analytics_orders.template get<1>()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.key_orders_for_multi_join)));
  auto& key_orders_for_multi_join = *key_orders_for_multi_join_owner;
  streams_.key_orders_for_multi_join = std::addressof(key_orders_for_multi_join);
  auto key_payments_for_multi_join_owner = service.makeStream<key_payments_for_multi_join_stream>(cfg.streams.keyPaymentsForMultiJoin, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>(split_analytics_payments.template get<1>()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.key_payments_for_multi_join)));
  auto& key_payments_for_multi_join = *key_payments_for_multi_join_owner;
  streams_.key_payments_for_multi_join = std::addressof(key_payments_for_multi_join);
  auto key_shipments_for_multi_join_owner = service.makeStream<key_shipments_for_multi_join_stream>(cfg.streams.keyShipmentsForMultiJoin, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>((*streams_.analytics_shipments)).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.key_shipments_for_multi_join)));
  auto& key_shipments_for_multi_join = *key_shipments_for_multi_join_owner;
  streams_.key_shipments_for_multi_join = std::addressof(key_shipments_for_multi_join);
  auto& multi_join_analytics_events = key_orders_for_multi_join.multiJoin(cfg.streams.multiJoinAnalyticsEvents, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::InMemory_Strategy{}, servicelib::StreamFunction(std::ref(*functions_.multi_join_analytics_events)), key_payments_for_multi_join, key_shipments_for_multi_join);
  streams_.multi_join_analytics_events = std::addressof(multi_join_analytics_events);
  auto route_analytics_result_owner = service.makeStream<route_analytics_result_stream>(cfg.streams.routeAnalyticsResult, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsResult>&>(multi_join_analytics_events).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.route_analytics_result)), service.makeStream<high_value_analytics_stream>(), service.makeStream<standard_analytics_stream>());
  auto& route_analytics_result = *route_analytics_result_owner;
  streams_.route_analytics_result = std::addressof(route_analytics_result);
  route_analytics_result.template get<0>().configure(cfg.streams.highValueAnalytics, nullptr, &service);
  streams_.high_value_analytics = std::addressof(route_analytics_result.template get<0>());
  route_analytics_result.template get<1>().configure(cfg.streams.standardAnalytics, nullptr, &service);
  streams_.standard_analytics = std::addressof(route_analytics_result.template get<1>());
  [[maybe_unused]] auto& write_high_value_analytics = route_analytics_result.template get<0>().sink(cfg.streams.writeHighValueAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteHighValueAnalyticsSinkBinding::Function{&bindings_.write_high_value_analytics}));
  streams_.write_high_value_analytics = write_high_value_analytics;
  [[maybe_unused]] auto& write_standard_analytics = route_analytics_result.template get<1>().sink(cfg.streams.writeStandardAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteStandardAnalyticsSinkBinding::Function{&bindings_.write_standard_analytics}));
  streams_.write_standard_analytics = write_standard_analytics;
  auto build_substream_analytics_result_owner = service.makeStream<build_substream_analytics_result_stream>(cfg.streams.buildSubstreamAnalyticsResult, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>((*streams_.analyze_analytics_substream)).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.build_substream_analytics_result)));
  auto& build_substream_analytics_result = *build_substream_analytics_result_owner;
  streams_.build_substream_analytics_result = std::addressof(build_substream_analytics_result);
  auto invoke_analytics_substream_owner = service.makeStream<invoke_analytics_substream_stream>(cfg.streams.invokeAnalyticsSubstream, static_cast<servicelib::StreamConsumer<example::analytics_service::types::AnalyticsEvent>&>((*streams_.substream_analytics_input)).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.invoke_analytics_substream)));
  auto& invoke_analytics_substream = *invoke_analytics_substream_owner;
  streams_.invoke_analytics_substream = std::addressof(invoke_analytics_substream);
  [[maybe_unused]] auto& write_substream_analytics = invoke_analytics_substream.sink(cfg.streams.writeSubstreamAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteSubstreamAnalyticsSinkBinding::Function{&bindings_.write_substream_analytics}));
  streams_.write_substream_analytics = write_substream_analytics;
  (*streams_.substream_analytics_input).connect(std::move(invoke_analytics_substream_owner));
  (*streams_.analyze_analytics_substream).connect(std::move(build_substream_analytics_result_owner));
  multi_join_analytics_events.connect(std::move(route_analytics_result_owner));
  (*streams_.analytics_shipments).connect(std::move(key_shipments_for_multi_join_owner));
  split_analytics_payments.template get<1>().connect(std::move(key_payments_for_multi_join_owner));
  split_analytics_orders.template get<1>().connect(std::move(key_orders_for_multi_join_owner));
  split_analytics_payments.template get<0>().connect(std::move(key_payments_for_join_owner));
  split_analytics_orders.template get<0>().connect(std::move(key_orders_for_join_owner));
  split_cycle_analytics.template get<1>().connect(std::move(continue_cycle_analytics_owner));
  split_cycle_analytics.template get<0>().connect(std::move(complete_cycle_analytics_owner));
  advance_cycle_analytics.connect(std::move(split_cycle_analytics_owner));
  merge_cycle_analytics.connect(std::move(advance_cycle_analytics_owner));
  (*streams_.cycle_analytics_input).connect(service.makeStream<merge_cycle_analytics_owner_link>(std::move(merge_cycle_analytics_owner)));
  (*streams_.cycle_analytics_link).connect(service.makeStream<merge_cycle_analytics_reference_link>(merge_cycle_analytics));
  (*streams_.analytics_payments).connect(std::move(split_analytics_payments_owner));
  (*streams_.analytics_orders).connect(std::move(split_analytics_orders_owner));
  streams_.consume_order_processed->setSource(count_order_processed);
  streams_.cycle_analytics_link->setSource(continue_cycle_analytics);
  streams_.analyze_analytics_substream->setSource(build_substream_analytics_result);

}

}  // namespace example::analytics_service::app