// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/substreams.generated.hpp"
#include "analyticsservice/internal/app/streams.generated.hpp"
#include "analyticsservice/internal/app/service.generated.hpp"

namespace example::analytics_service::app {
void ServiceSubStreams::bind(ServiceStreams& streams) {
  (void)streams;
  analyze_analytics_substream_substream_->bind(streams.analyze_analytics_substream);

}

}  // namespace example::analytics_service::app