# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build
BUILD_DIR ?= build

.PHONY: configure build test clean help

configure: ## Configure this standalone C++ module
	@cmake -S . -B "$(BUILD_DIR)" -G Ninja -DCMAKE_BUILD_TYPE=Debug

build: configure ## Build this standalone C++ module
	@cmake --build "$(BUILD_DIR)" --parallel

test: build ## Run module tests when present
	@ctest --test-dir "$(BUILD_DIR)" --output-on-failure

clean: ## Remove CMake build artifacts
	@cmake -E remove_directory "$(BUILD_DIR)"

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'