inventoryServiceApiAddress: dns:///localhost:9202
inventoryServiceConfigOverridePath: config/overrides.yaml
inventoryServiceEnvironment: ""
inventoryServiceGrpcHost: 0.0.0.0
inventoryServiceGrpcPort: 9202
inventoryServiceHttpHost: 0.0.0.0
inventoryServiceHttpPort: 9092