inventoryServiceApiAddress: dns:///inventoryservice:9202
inventoryServiceConfigOverridePath: /workspace/inventoryservice/config/overrides.integration.yaml
inventoryServiceEnvironment: ""
inventoryServiceGrpcHost: 0.0.0.0
inventoryServiceGrpcPort: 9202
inventoryServiceHttpHost: 0.0.0.0
inventoryServiceHttpPort: 9092
orderServiceEnvironment: ""
orderServiceConfigOverridePath: /workspace/orderservice/config/overrides.integration.yaml
orderServiceGrpcHost: 0.0.0.0
orderServiceGrpcPort: 9201
orderServiceHttpHost: 0.0.0.0
orderServiceHttpPort: 9091
