# Code generated by servicegen. DO NOT EDIT.

LANG_BUILD_TARGETS += cpp-build
LANG_TEST_TARGETS += cpp-test
LANG_LINT_TARGETS += cpp-lint
LANG_LINT_FIX_TARGETS += cpp-format
LANG_FMT_TARGETS += cpp-format
LANG_GEN_TARGETS += cpp-gen
LANG_CLEAN_TARGETS += cpp-clean
LANG_TOOL_TARGETS += cpp-tools
LANG_DOCKER_BUILD_TARGETS += cpp-docker-build
LANG_DOCKER_DEV_BUILD_TARGETS += cpp-docker-dev-build
LANG_INTEGRATION_TARGETS += cpp-integration-test
DOCKER_COMPOSE_RUNTIME_FILES += docker-compose.cpp-runtime.generated.yml

.PHONY: cpp-build cpp-test cpp-release-build cpp-release-test cpp-asan-test cpp-tsan-test \
	cpp-release-up cpp-lint cpp-format cpp-gen cpp-clean cpp-tools \
	cpp-docker-build cpp-docker-dev-build cpp-integration-test cpp-package

CPP_SERVICE_DIRS := analyticsservice inventoryservice orderservice

cpp-tools: ## Verify Docker is available for the canonical C++ toolchain
	@docker version >/dev/null
	@docker compose version >/dev/null

cpp-build: cpp-tools ## Build all C++ services in Docker
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done

cpp-test: cpp-tools ## Run all C++ unit tests in Docker
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" test USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done

cpp-release-build: cpp-tools ## Build optimized C++ services in Docker
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" release-build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done

cpp-release-test: cpp-tools ## Build and test optimized C++ services in Docker
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" release-test USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done

cpp-asan-test: cpp-tools ## Run C++ tests with ASan and UBSan
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" asan-test USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done
	@SANITIZER_INTEGRATION=1 ./scripts/sanitizer-test.generated.sh asan

cpp-tsan-test: cpp-tools ## Run C++ tests with TSan
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" tsan-test USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done
	@SANITIZER_INTEGRATION=1 ./scripts/sanitizer-test.generated.sh tsan

cpp-release-up: cpp-release-build ## Start services built with CMake Release
	@docker compose up -d

cpp-lint: cpp-tools ## Run clang-format and clang-tidy checks in Docker
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" lint USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done

cpp-format: cpp-tools ## Format C++ sources in Docker
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" fmt USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done

cpp-gen: cpp-build ## Generate C++ protobuf/OpenAPI code through CMake

cpp-docker-build: cpp-tools ## Build a minimal C++ runtime image
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" docker-build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done

cpp-docker-dev-build: cpp-tools ## Build source-mounted C++ development services
	@for service in $(CPP_SERVICE_DIRS); do $(MAKE) -C "$$service" docker-build-dev USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" || exit $$?; done

cpp-integration-test: cpp-tools ## Run C++ integration tests
	@./scripts/integration-test.generated.sh

cpp-package: ## Package all C++ services as standalone repositories
	@for service in $(CPP_SERVICE_DIRS); do \
	  rm -rf "dist/$$service"; \
	  ./scripts/package-cpp-service.generated.sh "$$service" "dist/$$service"; \
	done

cpp-package-%: ## Package one C++ service (for example: make cpp-package-orderservice)
	@case " $(CPP_SERVICE_DIRS) " in \
	  *" $* "*) ;; \
	  *) echo "unknown C++ service: $*" >&2; exit 2 ;; \
	esac
	@rm -rf "dist/$*"
	@./scripts/package-cpp-service.generated.sh "$*" "dist/$*"

cpp-clean: ## Remove C++ build and ccache volumes
	@docker compose -f docker-compose.cmake.generated.yml down --volumes --remove-orphans
	@rm -rf build