# Code generated by servicegen. DO NOT EDIT.

LANG_BUILD_TARGETS += cpp-build
LANG_TEST_TARGETS += cpp-test
LANG_LINT_TARGETS += cpp-lint
LANG_LINT_FIX_TARGETS += cpp-format
LANG_FMT_TARGETS += cpp-format
LANG_GEN_TARGETS += cpp-gen
LANG_CLEAN_TARGETS += cpp-clean
LANG_TOOL_TARGETS += cpp-tools
LANG_DOCKER_BUILD_TARGETS += cpp-docker-build
LANG_INTEGRATION_TARGETS += cpp-integration-test

.PHONY: cpp-build cpp-test cpp-lint cpp-format cpp-gen cpp-clean cpp-tools \
	cpp-docker-build cpp-integration-test

cpp-tools: ## Verify Docker is available for the canonical C++ toolchain
	@docker version >/dev/null
	@docker compose version >/dev/null

cpp-build: cpp-tools ## Build all C++ services in Docker
	@./scripts/build.sh

cpp-test: cpp-tools ## Run all C++ unit tests in Docker
	@./scripts/test.sh

cpp-lint: cpp-tools ## Run clang-format and clang-tidy checks in Docker
	@./scripts/lint.sh

cpp-format: cpp-tools ## Format C++ sources in Docker
	@./scripts/format.generated.sh

cpp-gen: cpp-build ## Generate C++ protobuf/OpenAPI code through CMake

cpp-docker-build: cpp-build ## Build the C++ build/runtime Docker image
	@docker compose -f docker-compose.cmake.yml build cpp-build

cpp-integration-test: cpp-tools ## Run C++ integration tests
	@./scripts/integration-test.sh

cpp-clean: ## Remove C++ build and ccache volumes
	@docker compose -f docker-compose.cmake.yml down --volumes --remove-orphans
	@rm -rf build
