// Code generated by servicegen. DO NOT EDIT.
// Graph construction owned by the order pipeline.
#pragma once

namespace example::order_service::app {

class ServiceGenerated;

struct OrderPipelineMakers {
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::MapOrderItemResultToOrderState>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::MapStreamConfig&)> map_order_item_result_to_order_state;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::MapToOrderProcessed>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::MapStreamConfig&)> map_to_order_processed;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::MapToOrderState>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::MapStreamConfig&)> map_to_order_state;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::OrderProcessedEndpointSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::KafkaEndpointConfig&)> order_processed_endpoint_sink;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::ProcessOrderItemSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::GrpcEndpointConfig&)> process_order_item_sink;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::ProcessOrderItems>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::FlatMapStreamConfig&)> process_order_items;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::ProcessOrderSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::HttpEndpointConfig&)> process_order_source;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::SoftDeadline>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::DelayStreamConfig&)> soft_deadline;
};

struct OrderPipelineFunctions {
  std::unique_ptr<functions::MapOrderItemResultToOrderState> map_order_item_result_to_order_state;
  std::unique_ptr<functions::MapToOrderProcessed> map_to_order_processed;
  std::unique_ptr<functions::MapToOrderState> map_to_order_state;
  std::unique_ptr<functions::OrderProcessedEndpointSink> order_processed_endpoint_sink;
  std::unique_ptr<functions::ProcessOrderItemSink> process_order_item_sink;
  std::unique_ptr<functions::ProcessOrderItems> process_order_items;
  std::unique_ptr<functions::ProcessOrderSource> process_order_source;
  std::unique_ptr<functions::SoftDeadline> soft_deadline;
};

struct OrderPipelineStreams {
  servicelib::InputStream<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr, ServiceGenerated>* process_order{};
  servicelib::StreamBase* split_pipeline{nullptr};
  servicelib::StreamBase* process_order_items{nullptr};
  servicelib::SinkEndpointStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, example::order_service::types::OrderState> process_order_item;
  servicelib::StreamBase* map_order_item_result_to_order_state{nullptr};
  servicelib::StreamBase* soft_deadline{nullptr};
  servicelib::StreamBase* map_to_order_state{nullptr};
  servicelib::StreamBase* merge_results{nullptr};
  servicelib::StreamBase* split_order_result{nullptr};
  servicelib::StreamBase* map_to_order_processed{nullptr};
  servicelib::SinkEndpointStreamRef<example::model::types::OrderProcessed, std::monostate, std::exception_ptr> publish_order_processed;
};

}  // namespace example::order_service::app

#define SERVICEGEN_INIT_ORDER_PROCESS_ORDER \
  streams_.process_order = &servicelib::makeInputStreamRef<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr, ServiceGenerated>(cfg.streams.processOrder, nullptr, *this);


#define SERVICEGEN_INIT_ORDER_SPLIT_PIPELINE \
  auto& split_pipeline = (*streams_.process_order).template split<2>(cfg.streams.splitPipeline); \
  streams_.split_pipeline = std::addressof(split_pipeline);


#define SERVICEGEN_INIT_ORDER_PROCESS_ORDER_ITEMS \
  auto& process_order_items = split_pipeline.template get<0>().flatMap(cfg.streams.processOrderItems, servicelib::StreamType<example::model::types::OrderItem>{}, servicelib::StreamFunction(std::ref(*functions_.process_order_items))); \
  streams_.process_order_items = std::addressof(process_order_items);


#define SERVICEGEN_INIT_ORDER_PROCESS_ORDER_ITEM \
  auto& process_order_item = process_order_items.sinkWithResult(cfg.streams.processOrderItem, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(ProcessOrderItemSinkBinding::Function{&bindings_.process_order_item})); \
  streams_.process_order_item = process_order_item;


#define SERVICEGEN_INIT_ORDER_MAP_ORDER_ITEM_RESULT_TO_ORDER_STATE \
  auto& map_order_item_result_to_order_state = process_order_item.map(cfg.streams.mapOrderItemResultToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(std::ref(*functions_.map_order_item_result_to_order_state))); \
  streams_.map_order_item_result_to_order_state = std::addressof(map_order_item_result_to_order_state);


#define SERVICEGEN_INIT_ORDER_SOFT_DEADLINE \
  auto& soft_deadline = split_pipeline.template get<1>().delay(cfg.streams.softDeadline, servicelib::StreamFunction(std::ref(*functions_.soft_deadline))); \
  streams_.soft_deadline = std::addressof(soft_deadline);


#define SERVICEGEN_INIT_ORDER_MAP_TO_ORDER_STATE \
  auto& map_to_order_state = soft_deadline.map(cfg.streams.mapToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(std::ref(*functions_.map_to_order_state))); \
  streams_.map_to_order_state = std::addressof(map_to_order_state);


#define SERVICEGEN_INIT_ORDER_MERGE_RESULTS \
  auto& merge_results = map_to_order_state.merge(cfg.streams.mergeResults, map_order_item_result_to_order_state, process_order_item.getErrorStream()); \
  streams_.merge_results = std::addressof(merge_results);


#define SERVICEGEN_INIT_ORDER_SPLIT_ORDER_RESULT \
  auto& split_order_result = merge_results.template split<2>(cfg.streams.splitOrderResult); \
  streams_.split_order_result = std::addressof(split_order_result);


#define SERVICEGEN_INIT_ORDER_MAP_TO_ORDER_PROCESSED \
  auto& map_to_order_processed = split_order_result.template get<0>().map(cfg.streams.mapToOrderProcessed, servicelib::StreamType<example::model::types::OrderProcessed>{}, servicelib::StreamFunction(std::ref(*functions_.map_to_order_processed))); \
  streams_.map_to_order_processed = std::addressof(map_to_order_processed);


#define SERVICEGEN_INIT_ORDER_PUBLISH_ORDER_PROCESSED \
  [[maybe_unused]] auto& publish_order_processed = map_to_order_processed.sink(cfg.streams.publishOrderProcessed, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(PublishOrderProcessedSinkBinding::Function{&bindings_.publish_order_processed})); \
  streams_.publish_order_processed = publish_order_processed;


#define SERVICEGEN_FINALIZE_ORDER_PROCESS_ORDER \
  streams_.process_order->setSource(split_order_result.template get<1>());



#define SERVICEGEN_BUILD_ORDER_STREAMS \
  SERVICEGEN_INIT_ORDER_PROCESS_ORDER \
  SERVICEGEN_INIT_ORDER_SPLIT_PIPELINE \
  SERVICEGEN_INIT_ORDER_PROCESS_ORDER_ITEMS \
  SERVICEGEN_INIT_ORDER_PROCESS_ORDER_ITEM \
  SERVICEGEN_INIT_ORDER_MAP_ORDER_ITEM_RESULT_TO_ORDER_STATE \
  SERVICEGEN_INIT_ORDER_SOFT_DEADLINE \
  SERVICEGEN_INIT_ORDER_MAP_TO_ORDER_STATE \
  SERVICEGEN_INIT_ORDER_MERGE_RESULTS \
  SERVICEGEN_INIT_ORDER_SPLIT_ORDER_RESULT \
  SERVICEGEN_INIT_ORDER_MAP_TO_ORDER_PROCESSED \
  SERVICEGEN_INIT_ORDER_PUBLISH_ORDER_PROCESSED \
  SERVICEGEN_FINALIZE_ORDER_PROCESS_ORDER \
  static_assert(true)

// End generated pipeline.