// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <functional>
#include <stdexcept>
#include <servicelib/runtime/context.hpp>
#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <inventoryservice/internal/types/inventory_failure.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>

namespace example::inventory_service::app {

  struct ServiceBindings final {
  };

}  // namespace example::inventory_service::app