// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <memory>
#include <optional>

#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>

#include <servicelib/runtime/context.hpp>
#include <servicelib/runtime/environment/environment.hpp>

#include "inventoryservice/config/config.generated.hpp"
#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <inventoryservice/internal/types/inventory_failure.hpp>

namespace example::inventory_service::app {
struct ServiceMakers;
struct ServiceClients final {
  void initClients(servicelib::Context context, const config::Config& cfg, servicelib::IServiceEnvironment& environment, ServiceMakers& makers);
};

}  // namespace example::inventory_service::app