// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/clients.generated.hpp"
#include "inventoryservice/internal/app/makers.generated.hpp"
#include <exception>
#include <mutex>
#include <stop_token>
#include <stdexcept>
#include <vector>
#include <userver/engine/mutex.hpp>
#include <userver/utils/async.hpp>

namespace example::inventory_service::app {
void ServiceClients::initClients(servicelib::Context context, const config::Config& cfg, servicelib::IServiceEnvironment& environment, ServiceMakers& makers) {
  auto& clients_ = *this;
  auto& makers_ = makers;
  (void)clients_; (void)makers_; (void)environment;

  (void)context;
  (void)cfg;
}

}  // namespace example::inventory_service::app