// Code generated by servicegen. DO NOT EDIT.
#pragma once




#include <memory>

#include <functional>
#include <exception>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/components/statistics_storage.hpp>
#include <userver/engine/task/task_with_result.hpp>
#include <userver/engine/mutex.hpp>


#include "inventoryservice/config/config.generated.hpp"
#include "inventoryservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/component.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/runtime/telemetry/userver/log.hpp>
#include <servicelib/runtime/telemetry/userver/metrics.hpp>
#include <servicelib/runtime/telemetry/userver/tracing.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/grpc/userver.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <inventoryservice/internal/types/inventory_failure.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>



#include "inventoryservice/internal/app/streams.generated.hpp"
#include <inventoryservice/internal/functions/endpoint/process_order_item_source.hpp>

namespace example::inventory_service::app {
class ServiceGenerated;
  using ProcessInventoryItemGrpcSourceEndpoint =
      servicelib::datasource::grpc::NoStreamingEndpoint<
          ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest, ::inventoryserviceapi::processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItemSource, std::exception_ptr>;
  using ProcessInventoryItemGrpcSourceConsumer =
      servicelib::datasource::grpc::EndpointConsumer<
          ProcessInventoryItemInput, ProcessInventoryItemGrpcSourceEndpoint, functions::ProcessOrderItemSource>;











struct ServiceEndpoints final {
  void initDataSources(const config::Config& cfg, ServiceGenerated& service);
    std::shared_ptr<ProcessInventoryItemGrpcSourceConsumer> process_inventory_item;
  };

}  // namespace example::inventory_service::app