// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/endpoints.generated.hpp"
#include "inventoryservice/internal/app/service.generated.hpp"

namespace example::inventory_service::app {

void ServiceEndpoints::initDataSources(const config::Config& cfg, ServiceGenerated& service) {
  auto& endpoints_ = *this;
  auto& streams_ = service.streams_;
  auto& functions_ = service.functions_;
  auto& bindings_ = service.bindings_;
  auto& connectors_ = service.connectors_;
  auto& clients_ = service.clients_;
  auto& servers_ = service.servers_;
  const auto& component_context_ = service.component_context_;
  (void)endpoints_; (void)streams_; (void)functions_; (void)bindings_;
  (void)connectors_; (void)clients_; (void)servers_; (void)component_context_;

  (void)cfg;
  servers_.inventory_service_api_source =
      servicelib::datasource::grpc::UserverDataSource::make(
          service, *streams_.process_inventory_item);
  endpoints_.process_inventory_item = ProcessInventoryItemGrpcSourceConsumer::make(
      service, *streams_.process_inventory_item,
      *functions_.process_order_item_source);
  servers_.inventory_service_api_source->addEndpoint(endpoints_.process_inventory_item->endpoint());
  service.registerDataSource(servers_.inventory_service_api_source);



}


}  // namespace example::inventory_service::app