// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <memory>
#include <servicelib/runtime/context.hpp>
#include <servicelib/runtime/environment/environment.hpp>

namespace example::inventory_service::functions {
class GetInventoryItemData;
class GetInventoryItemError;
class ProcessOrderItemSource;
}
namespace example::inventory_service::app {
struct ServiceMakers;
struct ServiceFunctions final {
  ServiceFunctions();
  ~ServiceFunctions();
  ServiceFunctions(ServiceFunctions&&) noexcept;
  ServiceFunctions& operator=(ServiceFunctions&&) noexcept;
  void initFunctions(servicelib::Context context, servicelib::IServiceEnvironment& environment, ServiceMakers& makers);
  std::unique_ptr<functions::GetInventoryItemData> get_inventory_item_data;
  std::unique_ptr<functions::GetInventoryItemError> get_inventory_item_error;
  std::unique_ptr<functions::ProcessOrderItemSource> process_order_item_source;
};

}  // namespace example::inventory_service::app