// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/functions.generated.hpp"
#include "inventoryservice/internal/app/makers.generated.hpp"
#include <exception>
#include <mutex>
#include <stop_token>
#include <stdexcept>
#include <vector>
#include <userver/engine/mutex.hpp>
#include <userver/utils/async.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_data.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_error.hpp>
#include <inventoryservice/internal/functions/endpoint/process_order_item_source.hpp>

namespace example::inventory_service::app {
ServiceFunctions::ServiceFunctions() = default;
ServiceFunctions::~ServiceFunctions() = default;
ServiceFunctions::ServiceFunctions(ServiceFunctions&&) noexcept = default;
ServiceFunctions& ServiceFunctions::operator=(ServiceFunctions&&) noexcept = default;

void ServiceFunctions::initFunctions(servicelib::Context context, const config::Config& cfg, servicelib::IServiceEnvironment& environment, ServiceMakers& makers) {
  auto& functions_ = *this;
  auto& makers_ = makers;
  (void)functions_;
  (void)makers_;
  (void)context;
  (void)environment;
  {
  if (!makers_.get_inventory_item_data) {
    throw std::logic_error("function maker GetInventoryItemData is not configured");
  }
  if (!makers_.get_inventory_item_error) {
    throw std::logic_error("function maker GetInventoryItemError is not configured");
  }
  if (!makers_.process_order_item_source) {
    throw std::logic_error("function maker ProcessOrderItemSource is not configured");
  }
  std::stop_source maker_cancellation;
  userver::engine::Mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<userver::engine::TaskWithResult<void>> maker_tasks;
  maker_tasks.reserve(3);
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-get_inventory_item_data",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.get_inventory_item_data(maker_context, environment);
            functions_.get_inventory_item_data = maker_task.Get();
            if (!functions_.get_inventory_item_data) throw std::logic_error("function maker GetInventoryItemData returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-get_inventory_item_error",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.get_inventory_item_error(maker_context, environment);
            functions_.get_inventory_item_error = maker_task.Get();
            if (!functions_.get_inventory_item_error) throw std::logic_error("function maker GetInventoryItemError returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-process_order_item_source",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.process_order_item_source(maker_context, environment, cfg.endpoints.processOrderItem);
            functions_.process_order_item_source = maker_task.Get();
            if (!functions_.process_order_item_source) throw std::logic_error("function maker ProcessOrderItemSource returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));

  for (auto& task : maker_tasks) {
    try {
      task.Get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
  }
}

}  // namespace example::inventory_service::app