// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/grpc_service.generated.hpp"

#include <stdexcept>
#include <utility>

namespace example::inventory_service::app {

InventoryServiceApiGrpcService::InventoryServiceApiGrpcService(
    const userver::components::ComponentConfig& config,
    const userver::components::ComponentContext& context)
    : inventoryserviceapi::InventoryServiceApiBase::Component(config, context),
      service_component_(context.FindComponent<InventoryServiceComponent>()) {}

InventoryServiceApiGrpcService::ProcessOrderItemResult InventoryServiceApiGrpcService::ProcessOrderItem(
    CallContext& context,
    processorderitem::ProcessOrderItemRequest&& request) {
  const auto endpoint = service_component_.service().grpcSourceEndpoint4();
  if (!endpoint) {
    throw std::runtime_error("gRPC datasource endpoint is not started");
  }
  return endpoint->handle(context, std::move(request));
}


}  // namespace example::inventory_service::app