// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <proto/inventoryserviceapi/inventoryserviceapi.generated_service.usrv.pb.hpp>

#include "inventoryservice/internal/app/service.hpp"

namespace example::inventory_service::app {

class InventoryServiceApiGrpcService final
    : public inventoryserviceapi::InventoryServiceApiBase::Component {
 public:
  static constexpr std::string_view kName = "inventory-service-api";

  InventoryServiceApiGrpcService(
      const userver::components::ComponentConfig& config,
      const userver::components::ComponentContext& context);

  ProcessOrderItemResult ProcessOrderItem(
      CallContext& context,
      processorderitem::ProcessOrderItemRequest&& request) override;

 private:
  InventoryServiceComponent& service_component_;
};



}  // namespace example::inventory_service::app