// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include "inventoryservice/config/config.generated.hpp"
#include <servicelib/datasource/http/userver.hpp>
#include "inventoryservice/internal/app/service.hpp"

namespace example::inventory_service::app {



}  // namespace example::inventory_service::app