// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/makers.generated.hpp"
#include <stdexcept>
#include <userver/utils/async.hpp>
#include <utility>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_data.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_error.hpp>
#include <inventoryservice/internal/functions/endpoint/process_order_item_source.hpp>

namespace example::inventory_service::app {
void ServiceMakers::initMakers(const userver::components::ComponentContext& components) {
  auto& makers_ = *this;
  (void)makers_; (void)components;
  get_inventory_item_data = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeGetInventoryItemData(std::move(context), environment);
  };
  get_inventory_item_error = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeGetInventoryItemError(std::move(context), environment);
  };
  process_order_item_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeProcessOrderItemSource(std::move(context), environment);
  };

}


}  // namespace example::inventory_service::app