// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <memory>
#include <servicelib/datasource/grpc/userver.hpp>

namespace example::inventory_service::app {
struct ServiceServers final {
  std::shared_ptr<servicelib::datasource::grpc::UserverDataSource> inventory_service_api_source;
};

}  // namespace example::inventory_service::app