// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/components/statistics_storage.hpp>
#include <userver/engine/task/task_with_result.hpp>


#include "inventoryservice/config/config.generated.hpp"
#include "inventoryservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/component.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/runtime/telemetry/userver/log.hpp>
#include <servicelib/runtime/telemetry/userver/metrics.hpp>
#include <servicelib/runtime/telemetry/userver/tracing.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/grpc/userver.hpp>

#include <inventoryservice/internal/functions/endpoint/process_order_item_source.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_data.hpp>
#include <model_cpp/include/example/model/types/order_item.hpp>
#include <model_cpp/include/example/model/types/order_item_result.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>


namespace example::inventory_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

using RuntimeConfigComponent =
    servicelib::config::ServicelibRuntimeComponent<config::Config>;

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  explicit ServiceGenerated(
      userver::utils::statistics::Storage& statistics_storage,
      const userver::components::ComponentContext& component_context);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

 protected:
  struct ServiceMakers final {
    std::function<userver::engine::TaskWithResult<
        std::unique_ptr<functions::GetInventoryItemData>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ProcessStreamConfig&)> get_inventory_item_data;
    std::function<userver::engine::TaskWithResult<
        std::unique_ptr<functions::ProcessOrderItemSource>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::GrpcEndpointConfig&)> process_order_item_source;
  };
  struct ServiceFunctions final {
    std::unique_ptr<functions::GetInventoryItemData> get_inventory_item_data;
    std::unique_ptr<functions::ProcessOrderItemSource> process_order_item_source;
  };

  ServiceMakers makers_;
  ServiceFunctions functions_;

  virtual void customMakersInit(servicelib::Context) {}
  virtual void customFunctionsInit(servicelib::Context) {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  void initMakers();
  void initInfrastructure(servicelib::Context context,
                          const config::Config& config);
  void initFunctions(servicelib::Context context, const config::Config& config);
  void initRuntime(servicelib::Context context);
  void initStreams(const config::Config& config);
  void initDataSources(const config::Config& config);
  void releaseRuntime() noexcept;

  using ProcessInventoryItemInput =
      servicelib::InputStream<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr,
                              ServiceGenerated>;


  struct ServiceStreams final {
    ProcessInventoryItemInput* process_inventory_item{};
    servicelib::StreamBase* get_inventory_item_data{nullptr};

    servicelib::StreamBase* merge_inventory_result{nullptr};

  };
  ServiceStreams streams_;


  struct ServiceBindings final {
  };
  ServiceBindings bindings_;

  using ProcessInventoryItemGrpcSourceEndpoint =
      servicelib::datasource::grpc::NoStreamingEndpoint<
          processorderitem::ProcessOrderItemRequest, processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItemSource, std::exception_ptr>;
  using ProcessInventoryItemGrpcSourceConsumer =
      servicelib::datasource::grpc::EndpointConsumer<
          ProcessInventoryItemInput, ProcessInventoryItemGrpcSourceEndpoint, functions::ProcessOrderItemSource>;

 public:
  std::shared_ptr<ProcessInventoryItemGrpcSourceEndpoint> grpcSourceEndpointProcessInventoryItem() const noexcept {
    return endpoints_.process_inventory_item ? endpoints_.process_inventory_item->endpoint() : nullptr;
  }

 private:










  struct ServiceEndpoints final {
    std::shared_ptr<ProcessInventoryItemGrpcSourceConsumer> process_inventory_item;
  };
  ServiceEndpoints endpoints_;

  struct ServiceConnectors final {
    std::shared_ptr<
        servicelib::datasource::grpc::UserverDataSource> inventory_service_api_source;
  };
  ServiceConnectors connectors_;

  [[maybe_unused]] const userver::components::ComponentContext& component_context_;
  servicelib::telemetry::userver_adapter::UserverMetrics metrics_;
  bool use_noop_metrics_{false};
  bool use_noop_tracing_{false};
  bool user_lifecycle_started_{false};
};

class Service;

class InventoryServiceComponent final : public userver::components::ComponentBase {
 public:
  static constexpr std::string_view kName = "inventory-service";

  InventoryServiceComponent(
      const userver::components::ComponentConfig& config,
      const userver::components::ComponentContext& context);
  ~InventoryServiceComponent() override;

  void OnAllComponentsAreStopping() override;

  Service& service() noexcept { return *service_; }


  static userver::yaml_config::Schema GetStaticConfigSchema();

 private:
  std::unique_ptr<Service> service_;
};

}  // namespace example::inventory_service::app