// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/service.generated.hpp"

#include <chrono>
#include <exception>
#include <stdexcept>
#include <string>
#include <string_view>

#include <userver/yaml_config/merge_schemas.hpp>

#include "inventoryservice/internal/app/service.hpp"

namespace example::inventory_service::app {

ServiceGenerated::ServiceGenerated(
    userver::utils::statistics::Storage& statistics_storage,
    const userver::components::ComponentContext& component_context)
    : component_context_(component_context), metrics_(statistics_storage) {}

ServiceGenerated::~ServiceGenerated() { stop(); }

void ServiceGenerated::start() {
  try {
    serviceInit();
    customMakersInit();
    initRuntime();
    customFunctionsInit();
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    user_lifecycle_started_ = true;
    serviceStarted();
  } catch (...) {
    stop();
    releaseRuntime();
    throw;
  }
}

void ServiceGenerated::initRuntime() {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  initStreams(*config_snapshot);
  initDataSources(*config_snapshot);

}

void ServiceGenerated::initStreams(const config::Config& cfg) {
  input_4_ = servicelib::makeInputStream<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr, ServiceGenerated>(cfg.streams.processInventoryItem, nullptr, *this);
  detached_2_ = servicelib::makeDetachedStream<example::model::types::OrderItemResult, ServiceGenerated>(2, "Get Inventory Item Error", nullptr, *this);
  auto& stream_1 = (*input_4_).process(cfg.streams.getInventoryItemData, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamFunction(functions::GetInventoryItemData{}));
  auto& stream_3 = stream_1.merge(cfg.streams.mergeInventoryResult, (*detached_2_));
  stream_1.setErrorConsumer(*detached_2_);
  input_4_->setSource(stream_3);
}

void ServiceGenerated::initDataSources(
    const config::Config& cfg) {
  grpc_source_1_ =
      std::make_shared<servicelib::datasource::grpc::UserverDataSource>(
          *this, cfg.dataConnectors.inventoryServiceApi.id);
  grpc_source_consumer_4_ = GrpcSourceConsumer4::make(
      *this, input_4_, functions::ProcessOrderItem{});
  grpc_source_1_->addEndpoint(grpc_source_consumer_4_->endpoint());
  registerDataSource(grpc_source_1_);



}


void ServiceGenerated::stop() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (user_lifecycle_started_) {
      user_lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop();
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
  releaseRuntime();
}

void ServiceGenerated::releaseRuntime() noexcept {
  grpc_source_1_.reset();



  grpc_source_consumer_4_.reset();



  detached_2_.reset();


  input_4_.reset();

}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return servicelib::telemetry::userver_adapter::UserverLogger::instance();
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return &servicelib::telemetry::userver_adapter::UserverTracing::instance();
}

InventoryServiceComponent::InventoryServiceComponent(
    const userver::components::ComponentConfig& component_config,
    const userver::components::ComponentContext& context)
    : ComponentBase(component_config, context),
      service_(std::make_unique<Service>(
          context.FindComponent<userver::components::StatisticsStorage>()
              .GetStorage(),
          context)) {
  context.FindComponent<RuntimeConfigComponent>();
  service_->start();
}

InventoryServiceComponent::~InventoryServiceComponent() { service_->stop(); }



userver::yaml_config::Schema InventoryServiceComponent::GetStaticConfigSchema() {
  return userver::yaml_config::MergeSchemas<
      userver::components::ComponentBase>(R"(
type: object
description: Config-driven servicelib service.
additionalProperties: false
properties: {}
)");
}

}  // namespace example::inventory_service::app