// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/components/statistics_storage.hpp>


#include "inventoryservice/config/config.generated.hpp"
#include "runtime/config/component.hpp"
#include "runtime/serviceapp.hpp"
#include "runtime/telemetry/userver/log.hpp"
#include "runtime/telemetry/userver/metrics.hpp"
#include "runtime/telemetry/userver/tracing.hpp"
#include "transformation/streams.hpp"
#include "datasource/grpc/userver.hpp"

#include <inventoryservice/internal/functions/get_inventory_item_data.hpp>
#include <inventoryservice/internal/functions/process_order_item.hpp>
#include <model/include/example/model/types/order_item.hpp>
#include <model/include/example/model/types/order_item_result.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>


namespace example::inventory_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

using RuntimeConfigComponent =
    servicelib::config::ServicelibRuntimeComponent<config::Config>;

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  explicit ServiceGenerated(
      userver::utils::statistics::Storage& statistics_storage,
      const userver::components::ComponentContext& component_context);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

 protected:
  virtual void customMakersInit() {}
  virtual void customFunctionsInit() {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  void initRuntime();
  void initStreams(const config::Config& config);
  void initDataSources(const config::Config& config);
  void releaseRuntime() noexcept;

  using Input4 =
      servicelib::InputStream<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr,
                              ServiceGenerated>;
  std::shared_ptr<Input4> input_4_;

  using Detached2 =
      servicelib::DetachedStream<example::model::types::OrderItemResult, ServiceGenerated>;
  std::shared_ptr<Detached2> detached_2_;



  using GrpcSourceEndpoint4 =
      servicelib::datasource::grpc::NoStreamingEndpoint<
          processorderitem::ProcessOrderItemRequest, processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItem, std::exception_ptr>;
  using GrpcSourceConsumer4 =
      servicelib::datasource::grpc::EndpointConsumer<
          Input4, GrpcSourceEndpoint4, functions::ProcessOrderItem>;
  std::shared_ptr<GrpcSourceConsumer4> grpc_source_consumer_4_;

 public:
  std::shared_ptr<GrpcSourceEndpoint4> grpcSourceEndpoint4() const noexcept {
    return grpc_source_consumer_4_ ? grpc_source_consumer_4_->endpoint() : nullptr;
  }

 private:


  std::shared_ptr<
      servicelib::datasource::grpc::UserverDataSource> grpc_source_1_;










  const userver::components::ComponentContext& component_context_;
  servicelib::telemetry::userver_adapter::UserverMetrics metrics_;
  bool user_lifecycle_started_{false};
};

class Service;

class InventoryServiceComponent final : public userver::components::ComponentBase {
 public:
  static constexpr std::string_view kName = "inventory-service";

  InventoryServiceComponent(
      const userver::components::ComponentConfig& config,
      const userver::components::ComponentContext& context);
  ~InventoryServiceComponent() override;

  Service& service() noexcept { return *service_; }


  static userver::yaml_config::Schema GetStaticConfigSchema();

 private:
  std::unique_ptr<Service> service_;
};

}  // namespace example::inventory_service::app