// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/service.generated.hpp"

#include <chrono>
#include <cstdlib>
#include <exception>
#include <mutex>
#include <vector>
#include <stdexcept>
#include <string>
#include <string_view>

#include <userver/yaml_config/merge_schemas.hpp>
#include <userver/engine/mutex.hpp>
#include <userver/utils/async.hpp>

#include "inventoryservice/internal/app/service.hpp"

namespace example::inventory_service::app {

ServiceGenerated::ServiceGenerated(
    userver::utils::statistics::Storage& statistics_storage,
    const userver::components::ComponentContext& component_context)
    : component_context_(component_context),
      metrics_(statistics_storage),
      use_noop_metrics_(std::getenv("SERVICELIB_NOOP_METRICS") != nullptr),
      use_noop_tracing_(std::getenv("SERVICELIB_NOOP_TRACING") != nullptr) {}

ServiceGenerated::~ServiceGenerated() { stop(); }

void ServiceGenerated::start() {
  try {
    const servicelib::Context context;
    serviceInit();
    initMakers();
    customMakersInit(context);
    initRuntime(context);
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    user_lifecycle_started_ = true;
    serviceStarted();
  } catch (...) {
    stop();
    releaseRuntime();
    throw;
  }
}

void ServiceGenerated::initMakers() {
  makers_.get_inventory_item_data = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ProcessStreamConfig& config) {
    return functions::MakeGetInventoryItemData(
        std::move(context), environment, config);
  };
  makers_.process_order_item_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::GrpcEndpointConfig& config) {
    return functions::MakeProcessOrderItemSource(
        std::move(context), environment, config);
  };
}

void ServiceGenerated::initInfrastructure(
    servicelib::Context context, const config::Config& cfg) {
  (void)context;
  (void)cfg;
}

void ServiceGenerated::initFunctions(
    servicelib::Context context, const config::Config& cfg) {
  if (!makers_.get_inventory_item_data) {
    throw std::logic_error("function maker GetInventoryItemData is not configured");
  }
  if (!makers_.process_order_item_source) {
    throw std::logic_error("function maker ProcessOrderItemSource is not configured");
  }
  std::stop_source maker_cancellation;
  userver::engine::Mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<userver::engine::TaskWithResult<void>> maker_tasks;
  maker_tasks.reserve(2);
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-get_inventory_item_data", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.get_inventory_item_data(
              maker_context, *this, cfg.streams.getInventoryItemData);
          functions_.get_inventory_item_data = maker_task.Get();
          if (!functions_.get_inventory_item_data) {
            throw std::logic_error("function maker GetInventoryItemData returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-process_order_item_source", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.process_order_item_source(
              maker_context, *this, cfg.endpoints.processOrderItem);
          functions_.process_order_item_source = maker_task.Get();
          if (!functions_.process_order_item_source) {
            throw std::logic_error("function maker ProcessOrderItemSource returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));

  for (auto& task : maker_tasks) {
    try {
      task.Get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}

void ServiceGenerated::initRuntime(servicelib::Context context) {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  initInfrastructure(context, *config_snapshot);
  initFunctions(context, *config_snapshot);
  customFunctionsInit(context);
  initStreams(*config_snapshot);
  initDataSources(*config_snapshot);

}

void ServiceGenerated::initStreams(const config::Config& cfg) {
  streams_.process_inventory_item = &servicelib::makeInputStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr, ServiceGenerated>(cfg.streams.processInventoryItem, nullptr, *this);
  auto& get_inventory_item_data = (*streams_.process_inventory_item).process(cfg.streams.getInventoryItemData, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamFunction(std::ref(*functions_.get_inventory_item_data)));
  streams_.get_inventory_item_data = std::addressof(get_inventory_item_data);
  auto& merge_inventory_result = get_inventory_item_data.merge(cfg.streams.mergeInventoryResult, get_inventory_item_data.getErrorStream());
  streams_.merge_inventory_result = std::addressof(merge_inventory_result);
  streams_.process_inventory_item->setSource(merge_inventory_result);
}

void ServiceGenerated::initDataSources(
    const config::Config& cfg) {
  (void)cfg;
  connectors_.inventory_service_api_source =
      servicelib::datasource::grpc::UserverDataSource::make(
          *this, *streams_.process_inventory_item);
  endpoints_.process_inventory_item = ProcessInventoryItemGrpcSourceConsumer::make(
      *this, *streams_.process_inventory_item,
      *functions_.process_order_item_source);
  connectors_.inventory_service_api_source->addEndpoint(endpoints_.process_inventory_item->endpoint());
  registerDataSource(connectors_.inventory_service_api_source);



}


void ServiceGenerated::stop() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (user_lifecycle_started_) {
      user_lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop();
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
  releaseRuntime();
}

void ServiceGenerated::releaseRuntime() noexcept {
  // ServiceApp::stop() has already stopped and released the runtime-owned
  // graph. Generated fields are only typed construction/runtime views.
  connectors_ = {};
  endpoints_ = {};
  bindings_ = {};
  streams_ = {};
  functions_ = {};
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return servicelib::telemetry::userver_adapter::UserverLogger::instance();
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return use_noop_metrics_ ? servicelib::metrics::NoopMetrics::instance()
                           : metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return use_noop_tracing_
             ? nullptr
             : &servicelib::telemetry::userver_adapter::UserverTracing::instance();
}

InventoryServiceComponent::InventoryServiceComponent(
    const userver::components::ComponentConfig& component_config,
    const userver::components::ComponentContext& context)
    : ComponentBase(component_config, context),
      service_(std::make_unique<Service>(
          context.FindComponent<userver::components::StatisticsStorage>()
              .GetStorage(),
          context)) {
  context.FindComponent<RuntimeConfigComponent>();
  service_->start();
}

InventoryServiceComponent::~InventoryServiceComponent() { service_->stop(); }

void InventoryServiceComponent::OnAllComponentsAreStopping() { service_->stop(); }



userver::yaml_config::Schema InventoryServiceComponent::GetStaticConfigSchema() {
  return userver::yaml_config::MergeSchemas<
      userver::components::ComponentBase>(R"(
type: object
description: Config-driven servicelib service.
additionalProperties: false
properties: {}
)");
}

}  // namespace example::inventory_service::app