// Code generated by servicegen. DO NOT EDIT.
#include <tuple>
#include <functional>

#include "inventoryservice/internal/app/streams.generated.hpp"
#include "inventoryservice/internal/app/service.generated.hpp"
#include "inventoryservice/internal/app/functions.generated.hpp"
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_data.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_error.hpp>
#include <inventoryservice/internal/functions/endpoint/process_order_item_source.hpp>

namespace example::inventory_service::app {
void ServiceStreams::initStreams(const config::Config& cfg, ServiceGenerated& service) {
  auto& streams_ = *this;
  (void)streams_; (void)cfg; (void)service;
  streams_.process_inventory_item = &servicelib::makeInputStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr, ServiceGenerated>(cfg.streams.processInventoryItem, nullptr, service);

}

void ServiceStreams::build(const config::Config& cfg, ServiceGenerated& service, ServiceFunctions& functions, ServiceBindings& bindings) {
  auto& streams_ = *this;
  auto& functions_ = functions;
  auto& bindings_ = bindings;
  (void)streams_; (void)functions_; (void)bindings_; (void)cfg; (void)service;

  using merge_inventory_result_stream = servicelib::Stream<example::model::types::OrderItemResult, servicelib::StreamConsumer<example::model::types::OrderItemResult>, ServiceGenerated>::MergeImpl<2, servicelib::StreamConsumer<example::model::types::OrderItemResult>>;
  using merge_inventory_result_owner_link = servicelib::Stream<example::model::types::OrderItemResult, servicelib::StreamConsumer<example::model::types::OrderItemResult>, ServiceGenerated>::MergeLinkImpl<2, true, merge_inventory_result_stream>;
  using merge_inventory_result_reference_link = servicelib::Stream<example::model::types::OrderItemResult, servicelib::StreamConsumer<example::model::types::OrderItemResult>, ServiceGenerated>::MergeLinkImpl<2, false, merge_inventory_result_stream>;
  using map_inventory_item_error_stream = servicelib::Stream<example::inventory_service::types::InventoryFailure, servicelib::StreamConsumer<example::inventory_service::types::InventoryFailure>, ServiceGenerated>::MapImpl<example::model::types::OrderItemResult, decltype(std::ref(*functions_.get_inventory_item_error)), merge_inventory_result_reference_link>;
  auto& get_inventory_item_data = (*streams_.process_inventory_item).process(cfg.streams.getInventoryItemData, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::inventory_service::types::InventoryFailure>{}, servicelib::StreamFunction(std::ref(*functions_.get_inventory_item_data)));
  streams_.get_inventory_item_data = std::addressof(get_inventory_item_data);
  auto map_inventory_item_error_owner = service.makeStream<map_inventory_item_error_stream>(cfg.streams.mapInventoryItemError, static_cast<servicelib::StreamConsumer<example::inventory_service::types::InventoryFailure>&>(get_inventory_item_data.getErrorStream()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.get_inventory_item_error)));
  auto& map_inventory_item_error = *map_inventory_item_error_owner;
  streams_.map_inventory_item_error = std::addressof(map_inventory_item_error);
  auto merge_inventory_result_owner = service.makeStream<merge_inventory_result_stream>(cfg.streams.mergeInventoryResult, static_cast<servicelib::StreamConsumer<example::model::types::OrderItemResult>&>(get_inventory_item_data).getSerde(), &service);
  auto& merge_inventory_result = *merge_inventory_result_owner;
  streams_.merge_inventory_result = std::addressof(merge_inventory_result);
  get_inventory_item_data.connect(service.makeStream<merge_inventory_result_owner_link>(std::move(merge_inventory_result_owner)));
  map_inventory_item_error.connect(service.makeStream<merge_inventory_result_reference_link>(merge_inventory_result));
  get_inventory_item_data.getErrorStream().connect(std::move(map_inventory_item_error_owner));
  streams_.process_inventory_item->setSource(merge_inventory_result);

}

}  // namespace example::inventory_service::app