// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <atomic>
#include <memory>
#include <stdexcept>
#include <utility>
#include <servicelib/transformation/streams.hpp>
#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <inventoryservice/internal/types/inventory_failure.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>

namespace example::inventory_service::app {
class ServiceGenerated;
struct ServiceStreams;
struct ServiceSubStreams final {

  void bind(ServiceStreams& streams);
 private:
};

}  // namespace example::inventory_service::app