// Code generated by servicegen. DO NOT EDIT.
// Graph construction owned by the cycleAnalytics pipeline.
#pragma once

namespace example::analytics_service::app {

class ServiceGenerated;

struct CycleAnalyticsPipelineMakers {
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::AdvanceCycleAnalytics>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::MapStreamConfig&)> advance_cycle_analytics;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::CompleteCycleAnalytics>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::FilterStreamConfig&)> complete_cycle_analytics;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::ContinueCycleAnalytics>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::FilterStreamConfig&)> continue_cycle_analytics;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::CycleAnalyticsInputSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::CustomEndpointConfig&)> cycle_analytics_input_source;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::CycleAnalyticsResultSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::CustomEndpointConfig&)> cycle_analytics_result_sink;
};

struct CycleAnalyticsPipelineFunctions {
  std::unique_ptr<functions::AdvanceCycleAnalytics> advance_cycle_analytics;
  std::unique_ptr<functions::CompleteCycleAnalytics> complete_cycle_analytics;
  std::unique_ptr<functions::ContinueCycleAnalytics> continue_cycle_analytics;
  std::unique_ptr<functions::CycleAnalyticsInputSource> cycle_analytics_input_source;
  std::unique_ptr<functions::CycleAnalyticsResultSink> cycle_analytics_result_sink;
};

struct CycleAnalyticsPipelineStreams {
  servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>* cycle_analytics_input{};
  servicelib::CycleLinkStream<example::analytics_service::types::AnalyticsEvent, ServiceGenerated>* cycle_analytics_link{};
  servicelib::StreamBase* merge_cycle_analytics{nullptr};
  servicelib::StreamBase* advance_cycle_analytics{nullptr};
  servicelib::StreamBase* split_cycle_analytics{nullptr};
  servicelib::StreamBase* complete_cycle_analytics{nullptr};
  servicelib::StreamBase* continue_cycle_analytics{nullptr};
  servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr> write_cycle_analytics;
};

}  // namespace example::analytics_service::app

#define SERVICEGEN_INIT_CYCLEANALYTICS_CYCLE_ANALYTICS_LINK \
  streams_.cycle_analytics_link = &servicelib::makeCycleLinkStreamRef<example::analytics_service::types::AnalyticsEvent, ServiceGenerated>(cfg.streams.cycleAnalyticsLink, nullptr, *this);


#define SERVICEGEN_INIT_CYCLEANALYTICS_CYCLE_ANALYTICS_INPUT \
  streams_.cycle_analytics_input = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.cycleAnalyticsInput, nullptr, *this);


#define SERVICEGEN_INIT_CYCLEANALYTICS_MERGE_CYCLE_ANALYTICS \
  auto& merge_cycle_analytics = (*streams_.cycle_analytics_input).merge(cfg.streams.mergeCycleAnalytics, (*streams_.cycle_analytics_link)); \
  streams_.merge_cycle_analytics = std::addressof(merge_cycle_analytics);


#define SERVICEGEN_INIT_CYCLEANALYTICS_ADVANCE_CYCLE_ANALYTICS \
  auto& advance_cycle_analytics = merge_cycle_analytics.map(cfg.streams.advanceCycleAnalytics, servicelib::StreamType<example::analytics_service::types::AnalyticsEvent>{}, servicelib::StreamFunction(std::ref(*functions_.advance_cycle_analytics))); \
  streams_.advance_cycle_analytics = std::addressof(advance_cycle_analytics);


#define SERVICEGEN_INIT_CYCLEANALYTICS_SPLIT_CYCLE_ANALYTICS \
  auto& split_cycle_analytics = advance_cycle_analytics.template split<2>(cfg.streams.splitCycleAnalytics); \
  streams_.split_cycle_analytics = std::addressof(split_cycle_analytics);


#define SERVICEGEN_INIT_CYCLEANALYTICS_COMPLETE_CYCLE_ANALYTICS \
  auto& complete_cycle_analytics = split_cycle_analytics.template get<0>().filter(cfg.streams.completeCycleAnalytics, servicelib::StreamFunction(std::ref(*functions_.complete_cycle_analytics))); \
  streams_.complete_cycle_analytics = std::addressof(complete_cycle_analytics);


#define SERVICEGEN_INIT_CYCLEANALYTICS_CONTINUE_CYCLE_ANALYTICS \
  auto& continue_cycle_analytics = split_cycle_analytics.template get<1>().filter(cfg.streams.continueCycleAnalytics, servicelib::StreamFunction(std::ref(*functions_.continue_cycle_analytics))); \
  streams_.continue_cycle_analytics = std::addressof(continue_cycle_analytics);


#define SERVICEGEN_INIT_CYCLEANALYTICS_WRITE_CYCLE_ANALYTICS \
  [[maybe_unused]] auto& write_cycle_analytics = complete_cycle_analytics.sink(cfg.streams.writeCycleAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteCycleAnalyticsSinkBinding::Function{&bindings_.write_cycle_analytics})); \
  streams_.write_cycle_analytics = write_cycle_analytics;


#define SERVICEGEN_FINALIZE_CYCLEANALYTICS_CYCLE_ANALYTICS_LINK \
  streams_.cycle_analytics_link->setSource(continue_cycle_analytics);



#define SERVICEGEN_BUILD_CYCLEANALYTICS_STREAMS \
  SERVICEGEN_INIT_CYCLEANALYTICS_CYCLE_ANALYTICS_LINK \
  SERVICEGEN_INIT_CYCLEANALYTICS_CYCLE_ANALYTICS_INPUT \
  SERVICEGEN_INIT_CYCLEANALYTICS_MERGE_CYCLE_ANALYTICS \
  SERVICEGEN_INIT_CYCLEANALYTICS_ADVANCE_CYCLE_ANALYTICS \
  SERVICEGEN_INIT_CYCLEANALYTICS_SPLIT_CYCLE_ANALYTICS \
  SERVICEGEN_INIT_CYCLEANALYTICS_COMPLETE_CYCLE_ANALYTICS \
  SERVICEGEN_INIT_CYCLEANALYTICS_CONTINUE_CYCLE_ANALYTICS \
  SERVICEGEN_INIT_CYCLEANALYTICS_WRITE_CYCLE_ANALYTICS \
  SERVICEGEN_FINALIZE_CYCLEANALYTICS_CYCLE_ANALYTICS_LINK \
  static_assert(true)

// End generated pipeline.