// Code generated by servicegen. DO NOT EDIT.
// Graph construction owned by the joinAnalytics pipeline.
#pragma once

namespace example::analytics_service::app {

class ServiceGenerated;

struct JoinAnalyticsPipelineMakers {
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::JoinOrderPaymentAnalytics>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::JoinStreamConfig&)> join_order_payment_analytics;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::JoinedAnalyticsSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::CustomEndpointConfig&)> joined_analytics_sink;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::KeyOrdersForJoin>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::KeyByStreamConfig&)> key_orders_for_join;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::KeyPaymentsForJoin>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::KeyByStreamConfig&)> key_payments_for_join;
};

struct JoinAnalyticsPipelineFunctions {
  std::unique_ptr<functions::JoinOrderPaymentAnalytics> join_order_payment_analytics;
  std::unique_ptr<functions::JoinedAnalyticsSink> joined_analytics_sink;
  std::unique_ptr<functions::KeyOrdersForJoin> key_orders_for_join;
  std::unique_ptr<functions::KeyPaymentsForJoin> key_payments_for_join;
};

struct JoinAnalyticsPipelineStreams {
  servicelib::StreamBase* key_orders_for_join{nullptr};
  servicelib::StreamBase* key_payments_for_join{nullptr};
  servicelib::StreamBase* join_order_payment_analytics{nullptr};
  servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsResult, std::monostate, std::exception_ptr> write_joined_analytics;
};

}  // namespace example::analytics_service::app

#define SERVICEGEN_INIT_JOINANALYTICS_KEY_ORDERS_FOR_JOIN \
  auto& key_orders_for_join = split_analytics_orders.template get<0>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyOrdersForJoin, servicelib::StreamFunction(std::ref(*functions_.key_orders_for_join))); \
  streams_.key_orders_for_join = std::addressof(key_orders_for_join);


#define SERVICEGEN_INIT_JOINANALYTICS_KEY_PAYMENTS_FOR_JOIN \
  auto& key_payments_for_join = split_analytics_payments.template get<0>().template keyBy<std::string, example::analytics_service::types::AnalyticsEvent>(cfg.streams.keyPaymentsForJoin, servicelib::StreamFunction(std::ref(*functions_.key_payments_for_join))); \
  streams_.key_payments_for_join = std::addressof(key_payments_for_join);


#define SERVICEGEN_INIT_JOINANALYTICS_JOIN_ORDER_PAYMENT_ANALYTICS \
  auto& join_order_payment_analytics = key_orders_for_join.join(cfg.streams.joinOrderPaymentAnalytics, key_payments_for_join, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::Inner{}, servicelib::InMemory_Strategy{}, servicelib::StreamFunction(std::ref(*functions_.join_order_payment_analytics))); \
  streams_.join_order_payment_analytics = std::addressof(join_order_payment_analytics);


#define SERVICEGEN_INIT_JOINANALYTICS_WRITE_JOINED_ANALYTICS \
  [[maybe_unused]] auto& write_joined_analytics = join_order_payment_analytics.sink(cfg.streams.writeJoinedAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteJoinedAnalyticsSinkBinding::Function{&bindings_.write_joined_analytics})); \
  streams_.write_joined_analytics = write_joined_analytics;




#define SERVICEGEN_BUILD_JOINANALYTICS_STREAMS \
  SERVICEGEN_INIT_JOINANALYTICS_KEY_ORDERS_FOR_JOIN \
  SERVICEGEN_INIT_JOINANALYTICS_KEY_PAYMENTS_FOR_JOIN \
  SERVICEGEN_INIT_JOINANALYTICS_JOIN_ORDER_PAYMENT_ANALYTICS \
  SERVICEGEN_INIT_JOINANALYTICS_WRITE_JOINED_ANALYTICS \
  static_assert(true)

// End generated pipeline.