// Code generated by servicegen. DO NOT EDIT.
// Graph construction owned by the substreamAnalytics pipeline.
#pragma once

namespace example::analytics_service::app {

class ServiceGenerated;

struct SubstreamAnalyticsPipelineMakers {
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::BuildSubstreamAnalyticsResult>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::MapStreamConfig&)> build_substream_analytics_result;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::InvokeAnalyticsSubstream>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::MapStreamConfig&)> invoke_analytics_substream;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::SubstreamAnalyticsInputSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::CustomEndpointConfig&)> substream_analytics_input_source;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::SubstreamAnalyticsResultSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::CustomEndpointConfig&)> substream_analytics_result_sink;
};

struct SubstreamAnalyticsPipelineFunctions {
  std::unique_ptr<functions::BuildSubstreamAnalyticsResult> build_substream_analytics_result;
  std::unique_ptr<functions::InvokeAnalyticsSubstream> invoke_analytics_substream;
  std::unique_ptr<functions::SubstreamAnalyticsInputSource> substream_analytics_input_source;
  std::unique_ptr<functions::SubstreamAnalyticsResultSink> substream_analytics_result_sink;
};

struct SubstreamAnalyticsPipelineStreams {
  std::shared_ptr<servicelib::SubStream<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult, ServiceGenerated>> analyze_analytics_substream;
  servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>* substream_analytics_input{};
  servicelib::StreamBase* build_substream_analytics_result{nullptr};
  servicelib::StreamBase* invoke_analytics_substream{nullptr};
  servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsResult, std::monostate, std::exception_ptr> write_substream_analytics;
};

}  // namespace example::analytics_service::app

#define SERVICEGEN_INIT_SUBSTREAMANALYTICS_ANALYZE_ANALYTICS_SUBSTREAM \
  streams_.analyze_analytics_substream = servicelib::makeSubStream<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult, ServiceGenerated>(cfg.streams.analyzeAnalyticsSubstream, *this);


#define SERVICEGEN_INIT_SUBSTREAMANALYTICS_BUILD_SUBSTREAM_ANALYTICS_RESULT \
  auto& build_substream_analytics_result = (*streams_.analyze_analytics_substream).map(cfg.streams.buildSubstreamAnalyticsResult, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::StreamFunction(std::ref(*functions_.build_substream_analytics_result))); \
  streams_.build_substream_analytics_result = std::addressof(build_substream_analytics_result);


#define SERVICEGEN_INIT_SUBSTREAMANALYTICS_SUBSTREAM_ANALYTICS_INPUT \
  streams_.substream_analytics_input = &servicelib::makeInputStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.substreamAnalyticsInput, nullptr, *this);


#define SERVICEGEN_INIT_SUBSTREAMANALYTICS_INVOKE_ANALYTICS_SUBSTREAM \
  auto& invoke_analytics_substream = (*streams_.substream_analytics_input).map(cfg.streams.invokeAnalyticsSubstream, servicelib::StreamType<example::analytics_service::types::AnalyticsResult>{}, servicelib::StreamFunction(std::ref(*functions_.invoke_analytics_substream))); \
  streams_.invoke_analytics_substream = std::addressof(invoke_analytics_substream);


#define SERVICEGEN_INIT_SUBSTREAMANALYTICS_WRITE_SUBSTREAM_ANALYTICS \
  [[maybe_unused]] auto& write_substream_analytics = invoke_analytics_substream.sink(cfg.streams.writeSubstreamAnalytics, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(WriteSubstreamAnalyticsSinkBinding::Function{&bindings_.write_substream_analytics})); \
  streams_.write_substream_analytics = write_substream_analytics;


#define SERVICEGEN_FINALIZE_SUBSTREAMANALYTICS_ANALYZE_ANALYTICS_SUBSTREAM \
  streams_.analyze_analytics_substream->setSource(build_substream_analytics_result);

#define SERVICEGEN_BIND_SUBSTREAMANALYTICS_ANALYZE_ANALYTICS_SUBSTREAM \
  analyze_analytics_substream_substream_->bind(streams_.analyze_analytics_substream);



#define SERVICEGEN_BUILD_SUBSTREAMANALYTICS_STREAMS \
  SERVICEGEN_INIT_SUBSTREAMANALYTICS_ANALYZE_ANALYTICS_SUBSTREAM \
  SERVICEGEN_INIT_SUBSTREAMANALYTICS_BUILD_SUBSTREAM_ANALYTICS_RESULT \
  SERVICEGEN_INIT_SUBSTREAMANALYTICS_SUBSTREAM_ANALYTICS_INPUT \
  SERVICEGEN_INIT_SUBSTREAMANALYTICS_INVOKE_ANALYTICS_SUBSTREAM \
  SERVICEGEN_INIT_SUBSTREAMANALYTICS_WRITE_SUBSTREAM_ANALYTICS \
  SERVICEGEN_FINALIZE_SUBSTREAMANALYTICS_ANALYZE_ANALYTICS_SUBSTREAM \
  SERVICEGEN_BIND_SUBSTREAMANALYTICS_ANALYZE_ANALYTICS_SUBSTREAM \
  static_assert(true)

// End generated pipeline.