services:
  analyticsservice:
    image: cppexample-analyticsservice
    working_dir: /app
    command:
      - --config
      - /app/static_config.yaml
      - --config_vars
      - /app/config/config_vars.integration.yaml
    stop_grace_period: 30000ms
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-0}
      - ANALYTICS_SERVICE_HTTP_PORT
      - ANALYTICS_SERVICE_GRPC_PORT
      - 'SECDIST_CONFIG=${SECDIST_CONFIG:-{"kafka_settings":{"kafka-consumer-order-events":{"brokers":"redpanda:9092"}}}}'
    ports:
      - "${ANALYTICS_SERVICE_HTTP_PORT:-9093}:${ANALYTICS_SERVICE_HTTP_PORT:-9093}"
      - "${ANALYTICS_SERVICE_GRPC_PORT:-9203}:${ANALYTICS_SERVICE_GRPC_PORT:-9203}"