# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build

export SERVICEGEN_FETCH_CPP_DEPENDENCIES := ON
BUILD_DIR ?= build

.PHONY: build test release-build release-test release-up lint fmt clean \
	docker-build docker-up docker-down docker-clean help

build: ## Build the standalone service with CMake
	@cmake -S . -B "$(BUILD_DIR)" -G Ninja -DCMAKE_BUILD_TYPE=Debug \
		-DSERVICEGEN_FETCH_CPP_DEPENDENCIES="$(SERVICEGEN_FETCH_CPP_DEPENDENCIES)"
	@cmake --build "$(BUILD_DIR)" --parallel

test: ## Build and run all service tests
	@$(MAKE) build
	@ctest --test-dir "$(BUILD_DIR)" --output-on-failure

release-build: ## Build the optimized standalone service with CMake
	@cmake -S . -B "$(BUILD_DIR)-release" -G Ninja -DCMAKE_BUILD_TYPE=Release \
		-DSERVICEGEN_FETCH_CPP_DEPENDENCIES="$(SERVICEGEN_FETCH_CPP_DEPENDENCIES)"
	@cmake --build "$(BUILD_DIR)-release" --parallel

release-test: ## Build and test the optimized standalone service
	@$(MAKE) release-build
	@ctest --test-dir "$(BUILD_DIR)-release" --output-on-failure

release-up: release-build ## Build the optimized service

lint: ## Run generated clang-format and clang-tidy targets
	@cmake --build "$(BUILD_DIR)" --target clang-format-check clang-tidy 2>/dev/null || \
	  { echo "lint targets are not available for this standalone project"; exit 1; }

fmt: ## Format C++ sources
	@find . -type f \( -name '*.cpp' -o -name '*.hpp' \) -not -path './build/*' \
		-exec clang-format -i {} +

clean: ## Remove CMake build artifacts
	@cmake -E remove_directory "$(BUILD_DIR)"
	@cmake -E remove_directory "$(BUILD_DIR)-release"

docker-build: build ## Build the reusable C++ toolchain image and service
	@docker compose -f docker-compose.cmake.generated.yml build cpp-build

docker-up: docker-build ## Start this service through Docker Compose
	@docker compose up -d

docker-down: ## Stop this service
	@docker compose down

docker-clean: docker-down clean ## Stop the service and remove all volumes
	@docker compose down --volumes --remove-orphans

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'