services:
  orderservice:
    image: cppexample-orderservice
    working_dir: /app
    command:
      - --config
      - /app/static_config.yaml
      - --config_vars
      - /app/config/config_vars.integration.yaml
    stop_grace_period: 30000ms
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-0}
      - ORDER_SERVICE_HTTP_PORT
      - ORDER_SERVICE_GRPC_PORT
    ports:
      - "${ORDER_SERVICE_HTTP_PORT:-9091}:${ORDER_SERVICE_HTTP_PORT:-9091}"
      - "${ORDER_SERVICE_GRPC_PORT:-9201}:${ORDER_SERVICE_GRPC_PORT:-9201}"
      - "2345:2345"