services:
  orderservice:
    image: cppexample-orderservice
    working_dir: /app
    command:
      - --config
      - /app/static_config.yaml
      - --config_vars
      - /app/config/config_vars.integration.yaml
    stop_grace_period: 30000ms
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-0}
    ports:
      - "9091:9091"
      - "9201:9201"
      - "2345:2345"