services:
  orderservice:
    image: orderservice-cpp-build
    working_dir: /workspace
    command:
      - /workspace/build/example_order_service
      - --config
      - /workspace/static_config.yaml
      - --config_vars
      - /workspace/config/config_vars.integration.yaml
    volumes:
      - .:/workspace
      - cpp-cmake-build:/workspace/build
    stop_grace_period: 30000ms
    restart: unless-stopped
    environment:
      - DEBUG=${ORDER_SERVICE_DEBUG:-0}
    ports:
      - "9091:9091"
      - "9201:9201"
      - "2345:2345"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

volumes:
  cpp-cmake-build: