# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build

export FETCH_CPP_DEPENDENCIES := ON
BUILD_DIR ?= build
STANDALONE_COMPOSE := $(if $(wildcard docker-compose.yml),docker-compose.yml,docker-compose.generated.yml)
STANDALONE_DEV_COMPOSE := $(if $(wildcard docker-compose.dev.yml),docker-compose.dev.yml,docker-compose.dev.generated.yml)
DEPENDENCY_DOCKER_TARGETS := docker-build docker-up docker-build-dev docker-up-dev debug
include dependency-proxy.generated.mk
LOCAL_MODULE_CMAKE_ARG :=
ifeq ($(strip $(USE_LOCAL_MODULES)),1)
export FETCH_CPP_DEPENDENCIES := OFF
LOCAL_MODULE_CMAKE_ARG := -DMODULES_ROOT="$(abspath ..)"
export MODULE_INVENTORY_SERVICE_API_SOURCE_CONTEXT := ../inventory_service_api
export MODULE_MODEL_SOURCE_CONTEXT := ../model
export MODULE_ORDER_SERVICE_API_SOURCE_CONTEXT := ../order_service_api
endif

ifneq ($(strip $(DEPENDENCY_PROXY_DIR)),)
export SERVICELIB_SOURCE_CONTEXT ?= $(DEPENDENCY_PROXY_DOCKER_BASE)/github-raw/gorundebug/cppservicelib/archive/refs/tags/v0.2.24.tar.gz
export USERVER_SOURCE_CONTEXT ?= $(DEPENDENCY_GIT_MIRROR_DOCKER_BASE)/github.com/userver-framework/userver.git\#c9f77729c0edce7e423def2d4a4450aa7fc9d259
endif

.PHONY: build test release-build release-test asan-test tsan-test release-up lint fmt clean \
	docker-build docker-build-dev docker-up docker-up-dev debug docker-down docker-down-dev docker-clean help

build: ## Build the standalone service with CMake
	@cmake -S . -B "$(BUILD_DIR)" -G Ninja -DCMAKE_BUILD_TYPE=Debug \
		$(LOCAL_MODULE_CMAKE_ARG) \
		-DFETCH_CPP_DEPENDENCIES="$(FETCH_CPP_DEPENDENCIES)"
	@cmake --build "$(BUILD_DIR)" --parallel

test: ## Build and run all service tests
	@$(MAKE) build
	@ctest --test-dir "$(BUILD_DIR)" --output-on-failure

release-build: ## Build the optimized standalone service with CMake
	@cmake -S . -B "$(BUILD_DIR)-release" -G Ninja -DCMAKE_BUILD_TYPE=Release \
		$(LOCAL_MODULE_CMAKE_ARG) \
		-DFETCH_CPP_DEPENDENCIES="$(FETCH_CPP_DEPENDENCIES)"
	@cmake --build "$(BUILD_DIR)-release" --parallel

release-test: ## Build and test the optimized standalone service
	@$(MAKE) release-build
	@ctest --test-dir "$(BUILD_DIR)-release" --output-on-failure

asan-test: ## Run standalone service tests with ASan and UBSan in Docker
	@SERVICEGEN_SANITIZER_INTEGRATION=0 ./scripts/sanitizer-test.generated.sh asan

tsan-test: ## Run standalone service tests with TSan in Docker
	@SERVICEGEN_SANITIZER_INTEGRATION=0 ./scripts/sanitizer-test.generated.sh tsan

release-up: release-build ## Build the optimized service

lint: ## Run generated clang-format and clang-tidy targets
	@cmake --build "$(BUILD_DIR)" --target clang-format-check clang-tidy 2>/dev/null || \
	  { echo "lint targets are not available for this standalone project"; exit 1; }

fmt: ## Format C++ sources
	@find . -type f \( -name '*.cpp' -o -name '*.hpp' \) -not -path './build/*' \
		-exec clang-format -i {} +

clean: ## Remove CMake build artifacts
	@cmake -E remove_directory "$(BUILD_DIR)"
	@cmake -E remove_directory "$(BUILD_DIR)-release"

docker-build: ## Build the autonomous C++ runtime image from copied sources
	@docker compose -f docker-compose.cmake.generated.yml build orderservice-runtime

docker-build-dev: ## Build this service in the source-mounted C++ development image
	@docker compose -f docker-compose.cmake.generated.yml build cpp-build
	@docker compose -f docker-compose.cmake.generated.yml run --rm cpp-build

docker-up: docker-build ## Start this service through Docker Compose
	@docker compose -f "$(STANDALONE_COMPOSE)" up -d --no-build

docker-up-dev: docker-build-dev ## Start this service with its source directory mounted
	@docker compose -f "$(STANDALONE_COMPOSE)" -f "$(STANDALONE_DEV_COMPOSE)" up -d --no-build

debug: docker-build-dev ## Start this service under gdbserver on localhost:2345
	@DEBUG=1 docker compose -f "$(STANDALONE_COMPOSE)" -f "$(STANDALONE_DEV_COMPOSE)" \
		up -d --no-build --force-recreate

docker-down: ## Stop this service
	@docker compose -f "$(STANDALONE_COMPOSE)" down

docker-down-dev: ## Stop the source-mounted standalone service
	@docker compose -f "$(STANDALONE_COMPOSE)" -f "$(STANDALONE_DEV_COMPOSE)" down

docker-clean: docker-down clean ## Stop the service and remove all volumes
	@docker compose -f "$(STANDALONE_COMPOSE)" down --volumes --remove-orphans

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'