# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build

export SERVICEGEN_FETCH_CPP_DEPENDENCIES := ON

.PHONY: build test release-build release-test release-up lint fmt clean \
	docker-build docker-up docker-down docker-clean help

build: ## Build the service in the canonical Docker toolchain
	@./scripts/build.generated.sh

test: ## Build and run all service tests in Docker
	@./scripts/test.generated.sh

release-build: ## Build the optimized service in Docker
	@./scripts/build.generated.sh docker-release

release-test: ## Build and test the optimized service in Docker
	@./scripts/test.generated.sh docker-release

release-up: release-build ## Start the service built with CMake Release
	@docker compose up -d

lint: ## Run clang-format and clang-tidy checks in Docker
	@./scripts/lint.generated.sh

fmt: ## Format C++ sources in Docker
	@./scripts/format.generated.sh

clean: ## Remove CMake build and ccache volumes
	@docker compose -f docker-compose.cmake.yml down --volumes --remove-orphans
	@rm -rf build

docker-build: build ## Build the reusable C++ toolchain image and service
	@docker compose -f docker-compose.cmake.yml build cpp-build

docker-up: docker-build ## Start this service through Docker Compose
	@docker compose up -d

docker-down: ## Stop this service
	@docker compose down

docker-clean: docker-down clean ## Stop the service and remove all volumes
	@docker compose down --volumes --remove-orphans

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'