// Code generated by servicegen. DO NOT EDIT.

#include <string_view>

#include <userver/components/minimal_server_component_list.hpp>
#include <userver/server/middlewares/configuration.hpp>
#include <userver/testsuite/testsuite_support.hpp>
#ifdef ENABLE_OTLP_TRACING
#include <userver/otlp/logs/component.hpp>
#include <userver/ugrpc/client/client_factory_component.hpp>
#include <userver/ugrpc/client/component_list.hpp>
#endif

#include <userver/ugrpc/server/component_list.hpp>

#include <userver/utils/daemon_run.hpp>

#include <servicelib/runtime/telemetry/userver/metrics.hpp>


#include <servicelib/runtime/telemetry/userver/status.hpp>


#include "inventoryservice/internal/app/service.generated.hpp"
#include "inventoryservice/internal/app/grpc_service.generated.hpp"


namespace {

class DisabledServerMiddlewarePipeline final
    : public userver::server::middlewares::PipelineBuilder {
 public:
  static constexpr std::string_view kName =
      "servicelib-disabled-server-middlewares";
  using PipelineBuilder::PipelineBuilder;

  userver::server::middlewares::MiddlewaresList BuildPipeline(
      userver::server::middlewares::MiddlewaresList) const override {
    return {};
  }
};

}  // namespace

int main(int argc, char* argv[]) {
  auto components =
      userver::components::MinimalServerComponentList()
          .Append<DisabledServerMiddlewarePipeline>()
          .Append<userver::components::TestsuiteSupport>()
#ifdef ENABLE_OTLP_TRACING
          .Append<userver::ugrpc::client::ClientFactoryComponent>(
              "grpc-otlp-factory")

          .AppendComponentList(
              userver::ugrpc::client::MinimalComponentList())

          .Append<userver::otlp::LoggerComponent>()
#endif
          .AppendComponentList(
              userver::ugrpc::server::DefaultComponentList())

          .Append<example::inventory_service::app::RuntimeConfigComponent>()
          .Append<example::inventory_service::app::InventoryServiceComponent>()
          .Append<servicelib::telemetry::userver_adapter::MetricsHandler>()

          .Append<servicelib::telemetry::userver_adapter::StatusPageHandler>()
          .Append<servicelib::telemetry::userver_adapter::StatusDataHandler>()
          .Append<servicelib::telemetry::userver_adapter::StatusGraphHandler>()
          .Append<servicelib::telemetry::userver_adapter::StatusJavaScriptHandler>()
          .Append<servicelib::telemetry::userver_adapter::StatusCssHandler>()

          .Append<servicelib::telemetry::userver_adapter::HealthHandler>("servicelib-startup-handler")

          .Append<servicelib::telemetry::userver_adapter::HealthHandler>("servicelib-readiness-handler")

          .Append<servicelib::telemetry::userver_adapter::HealthHandler>("servicelib-liveness-handler")

          .Append<example::inventory_service::app::InventoryServiceApiGrpcService>()
          ;
  return userver::utils::DaemonMain(argc, argv, components);
}