// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>

#include <servicelib/runtime/serde/serde.hpp>
#include <servicelib/runtime/serde/serdeimpl.hpp>
#include <orderservice/internal/serdes/order_serde.hpp>
#include <model/include/example/model/serdes/order_item_serde.hpp>
#include <model/include/example/model/serdes/order_item_result_serde.hpp>
#include <model/include/example/model/serdes/order_processed_serde.hpp>
#include <orderservice/internal/serdes/order_state_serde.hpp>


template <>
struct servicelib::serde::DefaultSerdeFactory<example::order_service::types::Order> final {
  static std::shared_ptr<const servicelib::serde::Serde<example::order_service::types::Order>>
  Make(servicelib::serde::SerdeLimits) {
    return std::make_shared<example::order_service::types::serde::OrderSerde>();
  }
};

template <>
struct servicelib::serde::DefaultSerdeFactory<example::model::types::OrderItem> final {
  static std::shared_ptr<const servicelib::serde::Serde<example::model::types::OrderItem>>
  Make(servicelib::serde::SerdeLimits) {
    return std::make_shared<example::model::types::serde::OrderItemSerde>();
  }
};

template <>
struct servicelib::serde::DefaultSerdeFactory<example::model::types::OrderItemResult> final {
  static std::shared_ptr<const servicelib::serde::Serde<example::model::types::OrderItemResult>>
  Make(servicelib::serde::SerdeLimits) {
    return std::make_shared<example::model::types::serde::OrderItemResultSerde>();
  }
};

template <>
struct servicelib::serde::DefaultSerdeFactory<example::model::types::OrderProcessed> final {
  static std::shared_ptr<const servicelib::serde::Serde<example::model::types::OrderProcessed>>
  Make(servicelib::serde::SerdeLimits) {
    return std::make_shared<example::model::types::serde::OrderProcessedSerde>();
  }
};

template <>
struct servicelib::serde::DefaultSerdeFactory<example::order_service::types::OrderState> final {
  static std::shared_ptr<const servicelib::serde::Serde<example::order_service::types::OrderState>>
  Make(servicelib::serde::SerdeLimits) {
    return std::make_shared<example::order_service::types::serde::OrderStateSerde>();
  }
};