// Code generated by servicegen. DO NOT EDIT.
// Graph construction owned by the inventoryItem pipeline.
#pragma once

namespace example::inventory_service::app {

class ServiceGenerated;

struct InventoryItemPipelineMakers {
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::GetInventoryItemData>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::ProcessStreamConfig&)> get_inventory_item_data;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::GetInventoryItemError>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::MapStreamConfig&)> get_inventory_item_error;
  std::function<userver::engine::TaskWithResult<
      std::unique_ptr<functions::ProcessOrderItemSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&,
      const servicelib::config::GrpcEndpointConfig&)> process_order_item_source;
};

struct InventoryItemPipelineFunctions {
  std::unique_ptr<functions::GetInventoryItemData> get_inventory_item_data;
  std::unique_ptr<functions::GetInventoryItemError> get_inventory_item_error;
  std::unique_ptr<functions::ProcessOrderItemSource> process_order_item_source;
};

struct InventoryItemPipelineStreams {
  servicelib::InputStream<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr, ServiceGenerated>* process_inventory_item{};
  servicelib::StreamBase* get_inventory_item_data{nullptr};
  servicelib::StreamBase* map_inventory_item_error{nullptr};
  servicelib::StreamBase* merge_inventory_result{nullptr};
};

}  // namespace example::inventory_service::app

#define SERVICEGEN_INIT_INVENTORYITEM_PROCESS_INVENTORY_ITEM \
  streams_.process_inventory_item = &servicelib::makeInputStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr, ServiceGenerated>(cfg.streams.processInventoryItem, nullptr, *this);


#define SERVICEGEN_INIT_INVENTORYITEM_GET_INVENTORY_ITEM_DATA \
  auto& get_inventory_item_data = (*streams_.process_inventory_item).process(cfg.streams.getInventoryItemData, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(std::ref(*functions_.get_inventory_item_data))); \
  streams_.get_inventory_item_data = std::addressof(get_inventory_item_data);


#define SERVICEGEN_INIT_INVENTORYITEM_MAP_INVENTORY_ITEM_ERROR \
  auto& map_inventory_item_error = get_inventory_item_data.getErrorStream().map(cfg.streams.mapInventoryItemError, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamFunction(std::ref(*functions_.get_inventory_item_error))); \
  streams_.map_inventory_item_error = std::addressof(map_inventory_item_error);


#define SERVICEGEN_INIT_INVENTORYITEM_MERGE_INVENTORY_RESULT \
  auto& merge_inventory_result = get_inventory_item_data.merge(cfg.streams.mergeInventoryResult, map_inventory_item_error); \
  streams_.merge_inventory_result = std::addressof(merge_inventory_result);


#define SERVICEGEN_FINALIZE_INVENTORYITEM_PROCESS_INVENTORY_ITEM \
  streams_.process_inventory_item->setSource(merge_inventory_result);



#define SERVICEGEN_BUILD_INVENTORYITEM_STREAMS \
  SERVICEGEN_INIT_INVENTORYITEM_PROCESS_INVENTORY_ITEM \
  SERVICEGEN_INIT_INVENTORYITEM_GET_INVENTORY_ITEM_DATA \
  SERVICEGEN_INIT_INVENTORYITEM_MAP_INVENTORY_ITEM_ERROR \
  SERVICEGEN_INIT_INVENTORYITEM_MERGE_INVENTORY_RESULT \
  SERVICEGEN_FINALIZE_INVENTORYITEM_PROCESS_INVENTORY_ITEM \
  static_assert(true)

// End generated pipeline.