// Code generated by servicegen. DO NOT EDIT.


#pragma once

#include <charconv>
#include <cstdlib>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#include <userver/formats/parse/to.hpp>
#include <userver/formats/yaml/serialize.hpp>
#include <userver/formats/yaml/value.hpp>

#include "orderservice/config/custom_config.hpp"
#include <servicelib/runtime/config/config.hpp>

namespace example::order_service::config {

inline constexpr int kOrderServiceServiceId = 4;
inline constexpr int kProcessOrderItemErrorStreamId = 45;
inline constexpr int kMapOrderItemResultToOrderStateStreamId = 46;
inline constexpr int kMapToOrderProcessedStreamId = 47;
inline constexpr int kMapToOrderStateStreamId = 48;
inline constexpr int kMergeResultsStreamId = 49;
inline constexpr int kProcessOrderStreamId = 50;
inline constexpr int kProcessOrderItemStreamId = 51;
inline constexpr int kProcessOrderItemsStreamId = 52;
inline constexpr int kPublishOrderProcessedStreamId = 53;
inline constexpr int kSoftDeadlineStreamId = 54;
inline constexpr int kSplitOrderResultStreamId = 55;
inline constexpr int kSplitPipelineStreamId = 56;
inline constexpr int kOrderProcessedEndpointId = 3;
inline constexpr int kProcessOrderEndpointId = 4;
inline constexpr int kProcessOrderItemEndpointId = 1;
inline constexpr int kInventoryServiceApiConnectorId = 1;
inline constexpr int kOrderEventsConnectorId = 3;
inline constexpr int kOrderServiceApiConnectorId = 4;

class Config final : public servicelib::config::IConfig {
 public:
  struct Services final {
    servicelib::config::ServiceConfig orderService;
  } services;

  struct Streams final {
    servicelib::config::MapStreamConfig mapOrderItemResultToOrderState;
    servicelib::config::MapStreamConfig mapToOrderProcessed;
    servicelib::config::MapStreamConfig mapToOrderState;
    servicelib::config::MergeStreamConfig mergeResults;
    servicelib::config::InputStreamConfig processOrder;
    servicelib::config::SinkStreamConfig processOrderItem;
    servicelib::config::FlatMapStreamConfig processOrderItems;
    servicelib::config::SinkStreamConfig publishOrderProcessed;
    servicelib::config::DelayStreamConfig softDeadline;
    servicelib::config::SplitStreamConfig splitOrderResult;
    servicelib::config::SplitStreamConfig splitPipeline;
  } streams;

  struct DataConnectors final {
    servicelib::config::GrpcDataConnectorConfig inventoryServiceApi;
    servicelib::config::KafkaDataConnectorConfig orderEvents;
    servicelib::config::HttpDataConnectorConfig orderServiceApi;
  } dataConnectors;

  struct Endpoints final {
    servicelib::config::KafkaEndpointConfig orderProcessed;
    servicelib::config::HttpEndpointConfig processOrder;
    servicelib::config::GrpcEndpointConfig processOrderItem;
  } endpoints;

  struct Pools final {
    servicelib::config::PoolConfig defaultPool;
  } pools;

  struct Links final {
    servicelib::config::LinkConfig mergeResultsToSplitOrderResult;
    servicelib::config::LinkConfig processOrderToSplitPipeline;
    servicelib::config::LinkConfig splitPipelineToProcessOrderItems;
    servicelib::config::LinkConfig splitPipelineToSoftDeadline;
  } links;

  struct Modules final {
    servicelib::config::ModuleConfig inventoryServiceApi;
    servicelib::config::ModuleConfig model;
    servicelib::config::ModuleConfig orderServiceApi;
  } modules;

  struct Types final {
    servicelib::config::TypeConfig order;
    servicelib::config::TypeConfig orderItem;
    servicelib::config::TypeConfig orderItemResult;
    servicelib::config::TypeConfig orderProcessed;
    servicelib::config::TypeConfig orderState;
  } types;

  CustomConfig custom;

  std::vector<const servicelib::config::ServiceConfig*> GetServices()
      const override {
    return { &services.orderService,  };
  }

  std::vector<servicelib::config::StreamConfigRef> GetStreams()
      const override {
    return { streams.mapOrderItemResultToOrderState, streams.mapToOrderProcessed, streams.mapToOrderState, streams.mergeResults, streams.processOrder, streams.processOrderItem, streams.processOrderItems, streams.publishOrderProcessed, streams.softDeadline, streams.splitOrderResult, streams.splitPipeline,  };
  }

  std::vector<servicelib::config::DataConnectorConfigRef> GetDataConnectors()
      const override {
    return { dataConnectors.inventoryServiceApi, dataConnectors.orderEvents, dataConnectors.orderServiceApi,  };
  }

  std::vector<servicelib::config::EndpointConfigRef> GetEndpoints()
      const override {
    return { endpoints.orderProcessed, endpoints.processOrder, endpoints.processOrderItem,  };
  }

  std::vector<const servicelib::config::PoolConfig*> GetPools()
      const override {
    return { &pools.defaultPool,  };
  }

  std::vector<const servicelib::config::LinkConfig*> GetLinks()
      const override {
    return { &links.mergeResultsToSplitOrderResult, &links.processOrderToSplitPipeline, &links.splitPipelineToProcessOrderItems, &links.splitPipelineToSoftDeadline,  };
  }

  std::vector<const servicelib::config::ModuleConfig*> GetModules()
      const override {
    return { &modules.inventoryServiceApi, &modules.model, &modules.orderServiceApi,  };
  }

  std::vector<const servicelib::config::TypeConfig*> GetTypes()
      const override {
    return { &types.order, &types.orderItem, &types.orderItemResult, &types.orderProcessed, &types.orderState,  };
  }
};

inline Config MakeConfig() {
  using namespace servicelib::config;
  using namespace servicelib::api;

  Config cfg;
  cfg.services.orderService = [] {
    ServiceConfig value{};
    value.id = kOrderServiceServiceId;
    value.name = "Order Service";
    value.color = "#FF5C00";
    value.defaultCallSemantics = MakeCallSemanticsGroup(CallSemantics::kFunctionCall, "", 0, false);
    value.defaultGrpcTimeout = 0;
    value.environment = Environment::kUndefined;
    value.golangVersion = "1.25.4";
    value.grpcHost = "0.0.0.0";
    value.grpcPort = 9201;
    value.httpHost = "0.0.0.0";
    value.httpPort = 9091;
    value.metricsHandler = "metrics";
    value.startupHandler = "health/startup";
    value.readinessHandler = "health/ready";
    value.livenessHandler = "health/live";
    value.kubernetesWorkloadType = KubernetesWorkloadType::kDeployment;
    value.modulePath = "github.com/gorundebug/cppexample-orderservice";
    value.shutdownTimeout = 30000;
    value.statusHandler = "status";
    return value;
  }();
  cfg.streams.mapOrderItemResultToOrderState = [] {
    MapStreamConfig value{};
    value.id = kMapOrderItemResultToOrderStateStreamId;
    value.name = "Map Order Item Result To Order State";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kProcessOrderItemStreamId;
    value.xPos = 103;
    value.yPos = -52;
    value.valueType = "OrderState";
    value.functionPackage = "order";
    value.functionName = "MapOrderItemResultToOrderState";
    value.functionDescription = "Produce an order result containing one inventory result and preserving its order ID.\nMark it CONFIRMED when the item was reserved; otherwise mark it PARTIALLY_CONFIRMED.\nRecord the time when this result is produced.\n";
    value.functionInitializerGroup = "";
    value.functionModule = "";
    return value;
  }();
  cfg.streams.mapToOrderProcessed = [] {
    MapStreamConfig value{};
    value.id = kMapToOrderProcessedStreamId;
    value.name = "MapToOrderProcessed";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kSplitOrderResultStreamId;
    value.xPos = -821;
    value.yPos = -26;
    value.valueType = "OrderProcessed";
    value.functionPackage = "order";
    value.functionName = "MapToOrderProcessed";
    value.functionDescription = "Create an OrderProcessed event from the final order state.\nPreserve the order ID, status, and processing time. Count all item results and reserved items; for unsuccessful orders use the final status as the failure reason.\n";
    value.functionInitializerGroup = "";
    value.functionModule = "";
    return value;
  }();
  cfg.streams.mapToOrderState = [] {
    MapStreamConfig value{};
    value.id = kMapToOrderStateStreamId;
    value.name = "Map to Order State";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kSoftDeadlineStreamId;
    value.xPos = -368;
    value.yPos = -227;
    value.valueType = "OrderState";
    value.functionPackage = "order";
    value.functionName = "MapToOrderState";
    value.functionDescription = "Produce a TIMED_OUT order result that preserves the order ID and submitted total.\nDo not add item results at this stage; results received before the timeout are included in the final response.\n";
    value.functionInitializerGroup = "";
    value.functionModule = "";
    return value;
  }();
  cfg.streams.mergeResults = [] {
    MergeStreamConfig value{};
    value.id = kMergeResultsStreamId;
    value.name = "Merge Results";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSources = { kMapToOrderStateStreamId, kMapOrderItemResultToOrderStateStreamId, kProcessOrderItemErrorStreamId };
    value.xPos = -228;
    value.yPos = 130;
    return value;
  }();
  cfg.streams.processOrder = [] {
    InputStreamConfig value{};
    value.id = kProcessOrderStreamId;
    value.name = "Process Order";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kSplitOrderResultStreamId;
    value.xPos = -760;
    value.yPos = -367;
    value.valueType = "Order";
    value.idEndpoint = kProcessOrderEndpointId;
    return value;
  }();
  cfg.streams.processOrderItem = [] {
    SinkStreamConfig value{};
    value.id = kProcessOrderItemStreamId;
    value.name = "Process Order Item";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kProcessOrderItemsStreamId;
    value.xPos = -60;
    value.yPos = -375;
    value.idEndpoint = kProcessOrderItemEndpointId;
    value.valueType = "OrderItemResult";
    return value;
  }();
  cfg.streams.processOrderItems = [] {
    FlatMapStreamConfig value{};
    value.id = kProcessOrderItemsStreamId;
    value.name = "Process Order Items";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kSplitPipelineStreamId;
    value.xPos = -198;
    value.yPos = -662;
    value.valueType = "OrderItem";
    value.functionPackage = "order";
    value.functionName = "ProcessOrderItems";
    value.functionDescription = "Emit every order item independently for inventory processing.\nPreserve each item's data and assign the parent order ID.\n";
    value.functionInitializerGroup = "";
    value.functionModule = "";
    return value;
  }();
  cfg.streams.publishOrderProcessed = [] {
    SinkStreamConfig value{};
    value.id = kPublishOrderProcessedStreamId;
    value.name = "Publish Order Processed";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kMapToOrderProcessedStreamId;
    value.xPos = -944;
    value.yPos = -255;
    value.idEndpoint = kOrderProcessedEndpointId;
    value.valueType = "OrderProcessed";
    return value;
  }();
  cfg.streams.softDeadline = [] {
    DelayStreamConfig value{};
    value.id = kSoftDeadlineStreamId;
    value.name = "Soft Deadline";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kSplitPipelineStreamId;
    value.xPos = -477;
    value.yPos = -444;
    value.duration = 0;
    value.functionPackage = "order";
    value.functionName = "SoftDeadline";
    value.functionDescription = "Trigger the timeout branch shortly before the request deadline, leaving the configured duration to assemble a response.\nWhen no request deadline exists, use the configured duration itself. Never wait past an existing deadline.\n";
    value.functionInitializerGroup = "";
    value.functionModule = "";
    return value;
  }();
  cfg.streams.splitOrderResult = [] {
    SplitStreamConfig value{};
    value.id = kSplitOrderResultStreamId;
    value.name = "Split Order Result";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kMergeResultsStreamId;
    value.xPos = -671;
    value.yPos = -129;
    return value;
  }();
  cfg.streams.splitPipeline = [] {
    SplitStreamConfig value{};
    value.id = kSplitPipelineStreamId;
    value.name = "Split Pipeline";
    value.pipeline = "order";
    value.idService = kOrderServiceServiceId;
    value.idSource = kProcessOrderStreamId;
    value.xPos = -640;
    value.yPos = -597;
    return value;
  }();
  cfg.dataConnectors.inventoryServiceApi = [] {
    GrpcDataConnectorConfig value{};
    value.id = kInventoryServiceApiConnectorId;
    value.name = "Inventory Service API";
    value.implementation = DataConnectorImplementation::kUserverGRPC;
    value.module = "inventory_service_api";
    value.address = "dns:///localhost:9202";
    value.connectionsCount = 1;
    return value;
  }();
  cfg.dataConnectors.orderEvents = [] {
    KafkaDataConnectorConfig value{};
    value.id = kOrderEventsConnectorId;
    value.name = "Order Events";
    value.implementation = DataConnectorImplementation::kUserverKafka;
    value.brokers = "redpanda:9092";
    value.version = "2.8.0";
    value.dialTimeout = 5000;
    value.securityProtocol = KafkaSecurityProtocol::kPLAINTEXT;
    value.saslMechanism = KafkaSaslMechanism::kSCRAMSHA512;
    value.username = "";
    value.password = "";
    return value;
  }();
  cfg.dataConnectors.orderServiceApi = [] {
    HttpDataConnectorConfig value{};
    value.id = kOrderServiceApiConnectorId;
    value.name = "Order Service API";
    value.implementation = DataConnectorImplementation::kUserverHTTP;
    value.module = "order_service_api";
    value.useDedicatedListener = false;
    return value;
  }();
  cfg.endpoints.orderProcessed = [] {
    KafkaEndpointConfig value{};
    value.id = kOrderProcessedEndpointId;
    value.name = "Order Processed";
    value.idDataConnector = kOrderEventsConnectorId;
    value.enabled = true;
    value.createTopic = true;
    value.topic = "order-processed";
    value.partitions = 1;
    value.consumerGroup = "analytics-service";
    value.replicationFactor = 1;
    value.functionName = "OrderProcessedEndpoint";
    value.functionPackage = "endpoint";
    value.publicFunction = false;
    value.functionDescription = "Exchange OrderProcessed events keyed by order ID.\nProducers include the final status, processing time, total and confirmed item counts, and a failure reason for unsuccessful orders.\nConsumers decode the event and mark its Kafka message processed only after the pipeline handles it successfully.\n";
    value.functionInitializerGroup = "";
    return value;
  }();
  cfg.endpoints.processOrder = [] {
    HttpEndpointConfig value{};
    value.id = kProcessOrderEndpointId;
    value.name = "Process Order";
    value.idDataConnector = kOrderServiceApiConnectorId;
    value.httpMethodType = HTTPMethodType::kPOST;
    value.path = "/v1/processorder";
    value.functionName = "ProcessOrder";
    value.functionPackage = "endpoint";
    value.publicFunction = false;
    value.functionDescription = "Accept orders with at least one item and positive quantities; reject malformed or invalid requests as client errors.\nReuse X-Request-ID when supplied, otherwise generate an order ID. Preserve customer, item, price, and X-Trace data, and apply the configured timeout of five seconds by default.\nReturn one response per order. When all items finish, use CONFIRMED only if every item was reserved; otherwise use PARTIALLY_CONFIRMED. If the deadline wins, return TIMED_OUT with the item results received so far.\nCalculate the total from processed item prices, falling back to the submitted total when no item result arrived, and include individual item failures in the response.\n";
    value.functionInitializerGroup = "";
    return value;
  }();
  cfg.endpoints.processOrderItem = [] {
    GrpcEndpointConfig value{};
    value.id = kProcessOrderItemEndpointId;
    value.name = "Process Order Item";
    value.idDataConnector = kInventoryServiceApiConnectorId;
    value.grpcMethodType = GrpcMethodType::kNoStreaming;
    value.methodName = "ProcessOrderItem";
    value.functionName = "ProcessOrderItem";
    value.functionPackage = "endpoint";
    value.publicFunction = false;
    value.functionDescription = "Reserve inventory for one order item using its order ID, item ID, SKU, and quantity.\nReturn the available quantity, reservation outcome, and status. The caller combines this response with the original identity, requested quantity, and unit price.\nIf the inventory call fails, the caller returns a non-reserved PROCESSING_ERROR result with the failure message.\n";
    value.functionInitializerGroup = "";
    return value;
  }();
  cfg.pools.defaultPool = [] {
    PoolConfig value{};
    value.name = "Default Pool";
    value.executorsCount = 2;
    return value;
  }();
  cfg.links.mergeResultsToSplitOrderResult = [] {
    LinkConfig value{};
    value.from = kMergeResultsStreamId;
    value.to = kSplitOrderResultStreamId;
    value.callSemantics = MakeCallSemanticsGroup(CallSemantics::kFunctionCall, "", 0, false);
    return value;
  }();
  cfg.links.processOrderToSplitPipeline = [] {
    LinkConfig value{};
    value.from = kProcessOrderStreamId;
    value.to = kSplitPipelineStreamId;
    value.callSemantics = MakeCallSemanticsGroup(CallSemantics::kPriorityTaskPool, "Default Pool", 1, false);
    return value;
  }();
  cfg.links.splitPipelineToProcessOrderItems = [] {
    LinkConfig value{};
    value.from = kSplitPipelineStreamId;
    value.to = kProcessOrderItemsStreamId;
    value.callSemantics = MakeCallSemanticsGroup(CallSemantics::kParallelCall, "", 0, false);
    return value;
  }();
  cfg.links.splitPipelineToSoftDeadline = [] {
    LinkConfig value{};
    value.from = kSplitPipelineStreamId;
    value.to = kSoftDeadlineStreamId;
    value.callSemantics = MakeCallSemanticsGroup(CallSemantics::kParallelCall, "", 0, false);
    return value;
  }();
  cfg.modules.inventoryServiceApi = [] {
    ModuleConfig value{};
    value.name = "inventory_service_api";
    value.path = "github.com/gorundebug/cppexample-inventory-service-api";
    return value;
  }();
  cfg.modules.model = [] {
    ModuleConfig value{};
    value.name = "model";
    value.path = "github.com/gorundebug/cppexample-model";
    return value;
  }();
  cfg.modules.orderServiceApi = [] {
    ModuleConfig value{};
    value.name = "order_service_api";
    value.path = "github.com/gorundebug/cppexample-order-service-api";
    return value;
  }();
  cfg.types.order = [] {
    TypeConfig value{};
    value.name = "Order";
    value.type = DataType::kStruct;
    value.package = "";
    value.definitionFormat = TypeDefinitionFormat::kNative;
    value.publicType = false;
    value.transferByValue = false;
    return value;
  }();
  cfg.types.orderItem = [] {
    TypeConfig value{};
    value.name = "OrderItem";
    value.type = DataType::kStruct;
    value.package = "";
    value.module = "model";
    value.definitionFormat = TypeDefinitionFormat::kNative;
    value.publicType = false;
    value.transferByValue = false;
    return value;
  }();
  cfg.types.orderItemResult = [] {
    TypeConfig value{};
    value.name = "OrderItemResult";
    value.type = DataType::kStruct;
    value.package = "";
    value.module = "model";
    value.definitionFormat = TypeDefinitionFormat::kNative;
    value.publicType = false;
    value.transferByValue = false;
    return value;
  }();
  cfg.types.orderProcessed = [] {
    TypeConfig value{};
    value.name = "OrderProcessed";
    value.type = DataType::kStruct;
    value.package = "";
    value.module = "model";
    value.definitionFormat = TypeDefinitionFormat::kNative;
    value.publicType = false;
    value.transferByValue = false;
    return value;
  }();
  cfg.types.orderState = [] {
    TypeConfig value{};
    value.name = "OrderState";
    value.type = DataType::kStruct;
    value.package = "";
    value.definitionFormat = TypeDefinitionFormat::kNative;
    value.publicType = false;
    value.transferByValue = false;
    return value;
  }();
  return cfg;
}

inline Config MakeConfig(userver::formats::parse::To<Config>) {
  return MakeConfig();
}

template <typename T>
inline void ApplyCustomProperties(
    const userver::formats::yaml::Value& value, T& config) {
  if (!value.IsObject()) return;
  const auto parsed = value.As<T>();
  for (const auto& [name, property] : parsed.properties) {
    config.properties.insert_or_assign(name, property);
  }
}

inline void ApplyConfig(const userver::formats::yaml::Value& value,
                        Config& config) {
  {
    const auto object = value["pools"]["defaultPool"];
    if (const auto field = object["executorsCount"]; !field.IsMissing()) {
      config.pools.defaultPool.executorsCount = field.As<int>();
    }
  }
  {
    const auto object = value["dataConnectors"]["inventoryServiceApi"];
    if (const auto field = object["address"]; !field.IsMissing()) {
      config.dataConnectors.inventoryServiceApi.address = field.As<std::string>();
    }
  }
  {
    const auto object = value["dataConnectors"]["inventoryServiceApi"];
    if (const auto field = object["connectionsCount"]; !field.IsMissing()) {
      config.dataConnectors.inventoryServiceApi.connectionsCount = field.As<int>();
    }
  }
  {
    const auto object = value["dataConnectors"]["orderEvents"];
    if (const auto field = object["brokers"]; !field.IsMissing()) {
      config.dataConnectors.orderEvents.brokers = field.As<std::string>();
    }
  }
  {
    const auto object = value["dataConnectors"]["orderEvents"];
    if (const auto field = object["password"]; !field.IsMissing()) {
      config.dataConnectors.orderEvents.password = field.As<std::string>();
    }
  }
  {
    const auto object = value["dataConnectors"]["orderEvents"];
    if (const auto field = object["saslMechanism"]; !field.IsMissing()) {
      config.dataConnectors.orderEvents.saslMechanism = field.As<servicelib::api::KafkaSaslMechanism>();
    }
  }
  {
    const auto object = value["dataConnectors"]["orderEvents"];
    if (const auto field = object["securityProtocol"]; !field.IsMissing()) {
      config.dataConnectors.orderEvents.securityProtocol = field.As<servicelib::api::KafkaSecurityProtocol>();
    }
  }
  {
    const auto object = value["dataConnectors"]["orderEvents"];
    if (const auto field = object["username"]; !field.IsMissing()) {
      config.dataConnectors.orderEvents.username = field.As<std::string>();
    }
  }
  {
    const auto object = value["endpoints"]["orderProcessed"];
    if (const auto field = object["enabled"]; !field.IsMissing()) {
      config.endpoints.orderProcessed.enabled = field.As<bool>();
    }
  }
  {
    const auto object = value["services"]["orderService"];
    if (const auto field = object["defaultGrpcTimeout"]; !field.IsMissing()) {
      config.services.orderService.defaultGrpcTimeout = field.As<int>();
    }
  }
  {
    const auto object = value["services"]["orderService"];
    if (const auto field = object["environment"]; !field.IsMissing()) {
      config.services.orderService.environment = field.As<servicelib::api::Environment>();
    }
  }
  {
    const auto object = value["services"]["orderService"];
    if (const auto field = object["grpcHost"]; !field.IsMissing()) {
      config.services.orderService.grpcHost = field.As<std::string>();
    }
  }
  {
    const auto object = value["services"]["orderService"];
    if (const auto field = object["grpcPort"]; !field.IsMissing()) {
      config.services.orderService.grpcPort = field.As<int>();
    }
  }
  {
    const auto object = value["services"]["orderService"];
    if (const auto field = object["httpHost"]; !field.IsMissing()) {
      config.services.orderService.httpHost = field.As<std::string>();
    }
  }
  {
    const auto object = value["services"]["orderService"];
    if (const auto field = object["httpPort"]; !field.IsMissing()) {
      config.services.orderService.httpPort = field.As<int>();
    }
  }
  {
    const auto object = value["streams"]["softDeadline"];
    if (const auto field = object["duration"]; !field.IsMissing()) {
      config.streams.softDeadline.duration = field.As<int>();
    }
  }
  ApplyCustomProperties(value["services"]["orderService"], config.services.orderService);
  ApplyCustomProperties(value["streams"]["mapOrderItemResultToOrderState"], config.streams.mapOrderItemResultToOrderState);
  ApplyCustomProperties(value["streams"]["mapToOrderProcessed"], config.streams.mapToOrderProcessed);
  ApplyCustomProperties(value["streams"]["mapToOrderState"], config.streams.mapToOrderState);
  ApplyCustomProperties(value["streams"]["mergeResults"], config.streams.mergeResults);
  ApplyCustomProperties(value["streams"]["processOrder"], config.streams.processOrder);
  ApplyCustomProperties(value["streams"]["processOrderItem"], config.streams.processOrderItem);
  ApplyCustomProperties(value["streams"]["processOrderItems"], config.streams.processOrderItems);
  ApplyCustomProperties(value["streams"]["publishOrderProcessed"], config.streams.publishOrderProcessed);
  ApplyCustomProperties(value["streams"]["softDeadline"], config.streams.softDeadline);
  ApplyCustomProperties(value["streams"]["splitOrderResult"], config.streams.splitOrderResult);
  ApplyCustomProperties(value["streams"]["splitPipeline"], config.streams.splitPipeline);
  ApplyCustomProperties(value["dataConnectors"]["inventoryServiceApi"], config.dataConnectors.inventoryServiceApi);
  ApplyCustomProperties(value["dataConnectors"]["orderEvents"], config.dataConnectors.orderEvents);
  ApplyCustomProperties(value["dataConnectors"]["orderServiceApi"], config.dataConnectors.orderServiceApi);
  ApplyCustomProperties(value["endpoints"]["orderProcessed"], config.endpoints.orderProcessed);
  ApplyCustomProperties(value["endpoints"]["processOrder"], config.endpoints.processOrder);
  ApplyCustomProperties(value["endpoints"]["processOrderItem"], config.endpoints.processOrderItem);
  ApplyCustomProperties(value["pools"]["defaultPool"], config.pools.defaultPool);
  ApplyCustomProperties(value["links"]["mergeResultsToSplitOrderResult"], config.links.mergeResultsToSplitOrderResult);
  ApplyCustomProperties(value["links"]["processOrderToSplitPipeline"], config.links.processOrderToSplitPipeline);
  ApplyCustomProperties(value["links"]["splitPipelineToProcessOrderItems"], config.links.splitPipelineToProcessOrderItems);
  ApplyCustomProperties(value["links"]["splitPipelineToSoftDeadline"], config.links.splitPipelineToSoftDeadline);
  ApplyCustomProperties(value["modules"]["inventoryServiceApi"], config.modules.inventoryServiceApi);
  ApplyCustomProperties(value["modules"]["model"], config.modules.model);
  ApplyCustomProperties(value["modules"]["orderServiceApi"], config.modules.orderServiceApi);
  ApplyCustomProperties(value["types"]["order"], config.types.order);
  ApplyCustomProperties(value["types"]["orderItem"], config.types.orderItem);
  ApplyCustomProperties(value["types"]["orderItemResult"], config.types.orderItemResult);
  ApplyCustomProperties(value["types"]["orderProcessed"], config.types.orderProcessed);
  ApplyCustomProperties(value["types"]["orderState"], config.types.orderState);
  ApplyConfig(value, config.custom);
}

inline servicelib::api::Environment ParseEnvironment(
    std::string_view value) {
  if (value.empty()) return servicelib::api::Environment::kUndefined;
  if (value == "local") return servicelib::api::Environment::kLocal;
  if (value == "debug") return servicelib::api::Environment::kDebug;
  if (value == "staging") return servicelib::api::Environment::kStaging;
  if (value == "production") return servicelib::api::Environment::kProduction;
  throw std::invalid_argument("invalid service environment: " +
                              std::string{value});
}

inline int ParseEnvironmentInt(const char* name, const char* value) {
  int result{};
  const std::string_view text{value};
  const auto [end, error] =
      std::from_chars(text.data(), text.data() + text.size(), result);
  if (error != std::errc{} || end != text.data() + text.size()) {
    throw std::invalid_argument(std::string{"invalid integer in "} + name);
  }
  return result;
}

inline void ApplyEnvironment(Config& config) {
  if (const auto* value = std::getenv("DEFAULT_POOL_EXECUTORS_COUNT")) {
    config.pools.defaultPool.executorsCount =
        ParseEnvironmentInt("DEFAULT_POOL_EXECUTORS_COUNT", value);
  }
  if (const auto* value = std::getenv("INVENTORY_SERVICE_API_ADDRESS")) {
    config.dataConnectors.inventoryServiceApi.address = value;
  }
  if (const auto* value = std::getenv("INVENTORY_SERVICE_API_CONNECTIONS_COUNT")) {
    config.dataConnectors.inventoryServiceApi.connectionsCount =
        ParseEnvironmentInt("INVENTORY_SERVICE_API_CONNECTIONS_COUNT", value);
  }
  if (const auto* value = std::getenv("ORDER_EVENTS_BROKERS")) {
    config.dataConnectors.orderEvents.brokers = value;
  }
  if (const auto* value = std::getenv("ORDER_EVENTS_PASSWORD")) {
    config.dataConnectors.orderEvents.password = value;
  }
  if (const auto* value = std::getenv("ORDER_EVENTS_SASL_MECHANISM")) {
    config.dataConnectors.orderEvents.saslMechanism =
        userver::formats::yaml::FromString(value).As<servicelib::api::KafkaSaslMechanism>();
  }
  if (const auto* value = std::getenv("ORDER_EVENTS_SECURITY_PROTOCOL")) {
    config.dataConnectors.orderEvents.securityProtocol =
        userver::formats::yaml::FromString(value).As<servicelib::api::KafkaSecurityProtocol>();
  }
  if (const auto* value = std::getenv("ORDER_EVENTS_USERNAME")) {
    config.dataConnectors.orderEvents.username = value;
  }
  if (const auto* value = std::getenv("ORDER_PROCESSED_ENABLED")) {
    const std::string_view parsed{value};
    if (parsed != "true" && parsed != "false") {
      throw std::invalid_argument("invalid boolean in ORDER_PROCESSED_ENABLED");
    }
    config.endpoints.orderProcessed.enabled = parsed == "true";
  }
  if (const auto* value = std::getenv("ORDER_SERVICE_DEFAULT_GRPC_TIMEOUT")) {
    config.services.orderService.defaultGrpcTimeout =
        ParseEnvironmentInt("ORDER_SERVICE_DEFAULT_GRPC_TIMEOUT", value);
  }
  if (const auto* value = std::getenv("ORDER_SERVICE_ENVIRONMENT")) {
    config.services.orderService.environment = ParseEnvironment(value);
  }
  if (const auto* value = std::getenv("ORDER_SERVICE_GRPC_HOST")) {
    config.services.orderService.grpcHost = value;
  }
  if (const auto* value = std::getenv("ORDER_SERVICE_GRPC_PORT")) {
    config.services.orderService.grpcPort =
        ParseEnvironmentInt("ORDER_SERVICE_GRPC_PORT", value);
  }
  if (const auto* value = std::getenv("ORDER_SERVICE_HTTP_HOST")) {
    config.services.orderService.httpHost = value;
  }
  if (const auto* value = std::getenv("ORDER_SERVICE_HTTP_PORT")) {
    config.services.orderService.httpPort =
        ParseEnvironmentInt("ORDER_SERVICE_HTTP_PORT", value);
  }
  if (const auto* value = std::getenv("SOFT_DEADLINE_DURATION")) {
    config.streams.softDeadline.duration =
        ParseEnvironmentInt("SOFT_DEADLINE_DURATION", value);
  }
  ApplyEnvironment(config.custom);
}

}  // namespace example::order_service::config