inventoryServiceApiAddress: dns:///inventoryservice:9202
orderServiceConfigOverridePath: config/overrides.integration.yaml
orderServiceEnvironment: ""
orderServiceGrpcHost: 0.0.0.0
orderServiceGrpcPort: 9201
orderServiceHttpHost: 0.0.0.0
orderServiceHttpPort: 9091