// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <functional>
#include <stdexcept>
#include <servicelib/runtime/context.hpp>
#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated_client.usrv.pb.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>

namespace example::order_service::app {
  struct ProcessOrderItemSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::model::types::OrderItem&)>
        consume;
    struct Function final {
      ProcessOrderItemSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::model::types::OrderItem& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct PublishOrderProcessedSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::model::types::OrderProcessed&)>
        consume;
    struct Function final {
      PublishOrderProcessedSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::model::types::OrderProcessed& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };

  struct ServiceBindings final {
    ProcessOrderItemSinkBinding process_order_item;
    PublishOrderProcessedSinkBinding publish_order_processed;
  };

}  // namespace example::order_service::app