// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/clients.generated.hpp"
#include "orderservice/internal/app/makers.generated.hpp"
#include <exception>
#include <mutex>
#include <stop_token>
#include <stdexcept>
#include <vector>
#include <userver/engine/mutex.hpp>
#include <userver/utils/async.hpp>

namespace example::order_service::app {
void ServiceClients::initClients(servicelib::Context context, const config::Config& cfg, servicelib::IServiceEnvironment& environment, ServiceMakers& makers) {
  auto& clients_ = *this;
  auto& makers_ = makers;
  (void)clients_; (void)makers_; (void)environment;

std::stop_source maker_cancellation;
  userver::engine::Mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<userver::engine::TaskWithResult<void>> maker_tasks;
  if (!makers_.inventory_service_api_client) {
    throw std::logic_error("infrastructure maker inventory_service_api_client is not configured");
  }
  maker_tasks.push_back(userver::utils::Async(
      "service-grpc-client-init-inventory_service_api_client",
      [&clients_, &makers_, &environment, &cfg, maker_context, &maker_cancellation, &maker_error_mutex,
       &first_maker_error] {
        try {
          auto task = makers_.inventory_service_api_client(
              maker_context, environment, cfg.dataConnectors.inventoryServiceApi);
          clients_.inventory_service_api_client.emplace(task.Get());
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) first_maker_error = std::current_exception();
          throw;
        }
      }));
  for (auto& task : maker_tasks) {
    try {
      task.Get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}

}  // namespace example::order_service::app