// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/connectors.generated.hpp"
#include "orderservice/internal/app/endpoints.generated.hpp"

namespace example::order_service::app {
ServiceConnectors::ServiceConnectors() = default;
ServiceConnectors::~ServiceConnectors() = default;
ServiceConnectors::ServiceConnectors(ServiceConnectors&&) noexcept = default;
ServiceConnectors& ServiceConnectors::operator=(ServiceConnectors&&) noexcept = default;

}  // namespace example::order_service::app