// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/endpoints.generated.hpp"
#include "orderservice/internal/app/service.generated.hpp"

namespace example::order_service::app {
void ServiceEndpoints::initDataSinks(const config::Config& cfg, ServiceGenerated& service) {
  auto& endpoints_ = *this;
  auto& streams_ = service.streams_;
  auto& functions_ = service.functions_;
  auto& bindings_ = service.bindings_;
  auto& connectors_ = service.connectors_;
  auto& clients_ = service.clients_;
  auto& servers_ = service.servers_;
  const auto& component_context_ = service.component_context_;
  (void)endpoints_; (void)streams_; (void)functions_; (void)bindings_;
  (void)connectors_; (void)clients_; (void)servers_; (void)component_context_;

  (void)cfg;

  connectors_.inventory_service_api_sink =
      servicelib::datasink::grpc::UserverDataSink::make(
          streams_.process_order_item.get());
  endpoints_.process_order_item = std::make_shared<ProcessOrderItemGrpcSinkEndpoint>(
      streams_.process_order_item.get(),
      *functions_.process_order_item_sink,
      ProcessOrderItemGrpcClientFunction{&*clients_.inventory_service_api_client});
  bindings_.process_order_item.consume =
      [endpoint = endpoints_.process_order_item.get()](
          servicelib::MessageContext context, const example::model::types::OrderItem& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::model::types::OrderItem>::make(value));
      };
  connectors_.inventory_service_api_sink->addEndpoint(endpoints_.process_order_item);
  service.registerDataSink(connectors_.inventory_service_api_sink);


  clients_.publish_order_processed_producer =
      std::make_unique<servicelib::datasink::kafka::UserverProducerClient>(
          component_context_, cfg.dataConnectors.orderEvents);
  endpoints_.publish_order_processed = std::make_shared<PublishOrderProcessedKafkaSinkEndpoint>(
      streams_.publish_order_processed.get(), *clients_.publish_order_processed_producer,
      *functions_.order_processed_endpoint_sink);
  bindings_.publish_order_processed.consume =
      [endpoint = endpoints_.publish_order_processed.get()](
          servicelib::MessageContext context, const example::model::types::OrderProcessed& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::model::types::OrderProcessed>::make(value));
      };
  service.registerDataSink(endpoints_.publish_order_processed);

}

void ServiceEndpoints::initDataSources(const config::Config& cfg, ServiceGenerated& service) {
  auto& endpoints_ = *this;
  auto& streams_ = service.streams_;
  auto& functions_ = service.functions_;
  auto& bindings_ = service.bindings_;
  auto& connectors_ = service.connectors_;
  auto& clients_ = service.clients_;
  auto& servers_ = service.servers_;
  const auto& component_context_ = service.component_context_;
  (void)endpoints_; (void)streams_; (void)functions_; (void)bindings_;
  (void)connectors_; (void)clients_; (void)servers_; (void)component_context_;

  (void)cfg;

  servers_.order_service_api_source =
      servicelib::datasource::http::UserverDataSource::make(
          service, *streams_.process_order);
  endpoints_.process_order = ProcessOrderHTTPSourceConsumer::make(
      service, *streams_.process_order,
      *functions_.process_order_source);
  servers_.order_service_api_source->addEndpoint(endpoints_.process_order->endpoint());
  service.registerDataSource(servers_.order_service_api_source);


}


}  // namespace example::order_service::app