// Code generated by servicegen. DO NOT EDIT.
#pragma once




#include <memory>

#include <functional>
#include <exception>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/components/statistics_storage.hpp>
#include <userver/engine/task/task_with_result.hpp>
#include <userver/engine/mutex.hpp>
#include <userver/ugrpc/client/client_factory_component.hpp>
#include <userver/ugrpc/client/client_settings.hpp>


#include "orderservice/config/config.generated.hpp"
#include "orderservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/component.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/runtime/telemetry/userver/log.hpp>
#include <servicelib/runtime/telemetry/userver/metrics.hpp>
#include <servicelib/runtime/telemetry/userver/tracing.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasink/grpc/userver.hpp>
#include <servicelib/datasource/http/userver.hpp>
#include <servicelib/datasink/kafka/userver.hpp>
#include <userver/kafka/producer_component.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated_client.usrv.pb.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>



#include "orderservice/internal/app/streams.generated.hpp"
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>

namespace example::order_service::app {
class ServiceGenerated;


  struct ProcessOrderItemGrpcClientFunction final {
    ::inventoryserviceapi::InventoryServiceApiClient* client;
    decltype(auto) operator()(
        const ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest& request,
        userver::ugrpc::client::CallOptions options) const {
      return client->ProcessOrderItem(request, std::move(options));
    }
  };
  using ProcessOrderItemGrpcSinkEndpoint =
      servicelib::datasink::grpc::NoStreamingEndpoint<
          ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest, ::inventoryserviceapi::processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItemSink, ProcessOrderItemGrpcClientFunction, example::order_service::types::OrderState>;

  using ProcessOrderHTTPSourceConsumer =
      servicelib::datasource::http::UserverEndpointConsumer<
          example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
          ServiceGenerated, functions::ProcessOrderSource>;




  using PublishOrderProcessedKafkaSinkEndpoint =
      servicelib::datasink::kafka::Endpoint<
          example::model::types::OrderProcessed, std::monostate, functions::OrderProcessedEndpointSink, std::exception_ptr>;




struct ServiceEndpoints final {
  void initDataSinks(const config::Config& cfg, ServiceGenerated& service);
  void initDataSources(const config::Config& cfg, ServiceGenerated& service);
    std::shared_ptr<ProcessOrderItemGrpcSinkEndpoint> process_order_item;
    std::shared_ptr<ProcessOrderHTTPSourceConsumer> process_order;
    std::shared_ptr<PublishOrderProcessedKafkaSinkEndpoint> publish_order_processed;
  };

}  // namespace example::order_service::app