// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/functions.generated.hpp"
#include "orderservice/internal/app/makers.generated.hpp"
#include <exception>
#include <mutex>
#include <stop_token>
#include <stdexcept>
#include <vector>
#include <userver/engine/mutex.hpp>
#include <userver/utils/async.hpp>
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>

namespace example::order_service::app {
ServiceFunctions::ServiceFunctions() = default;
ServiceFunctions::~ServiceFunctions() = default;
ServiceFunctions::ServiceFunctions(ServiceFunctions&&) noexcept = default;
ServiceFunctions& ServiceFunctions::operator=(ServiceFunctions&&) noexcept = default;

void ServiceFunctions::initFunctions(servicelib::Context context, const config::Config& cfg, servicelib::IServiceEnvironment& environment, ServiceMakers& makers) {
  auto& functions_ = *this;
  auto& makers_ = makers;
  (void)functions_;
  (void)makers_;
  (void)context;
  (void)environment;
  {
  if (!makers_.map_order_item_result_to_order_state) {
    throw std::logic_error("function maker MapOrderItemResultToOrderState is not configured");
  }
  if (!makers_.map_to_order_processed) {
    throw std::logic_error("function maker MapToOrderProcessed is not configured");
  }
  if (!makers_.map_to_order_state) {
    throw std::logic_error("function maker MapToOrderState is not configured");
  }
  if (!makers_.order_processed_endpoint_sink) {
    throw std::logic_error("function maker OrderProcessedEndpointSink is not configured");
  }
  if (!makers_.process_order_item_sink) {
    throw std::logic_error("function maker ProcessOrderItemSink is not configured");
  }
  if (!makers_.process_order_items) {
    throw std::logic_error("function maker ProcessOrderItems is not configured");
  }
  if (!makers_.process_order_source) {
    throw std::logic_error("function maker ProcessOrderSource is not configured");
  }
  if (!makers_.soft_deadline) {
    throw std::logic_error("function maker SoftDeadline is not configured");
  }
  std::stop_source maker_cancellation;
  userver::engine::Mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<userver::engine::TaskWithResult<void>> maker_tasks;
  maker_tasks.reserve(8);
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-map_order_item_result_to_order_state",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.map_order_item_result_to_order_state(maker_context, environment);
            functions_.map_order_item_result_to_order_state = maker_task.Get();
            if (!functions_.map_order_item_result_to_order_state) throw std::logic_error("function maker MapOrderItemResultToOrderState returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-map_to_order_processed",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.map_to_order_processed(maker_context, environment);
            functions_.map_to_order_processed = maker_task.Get();
            if (!functions_.map_to_order_processed) throw std::logic_error("function maker MapToOrderProcessed returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-map_to_order_state",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.map_to_order_state(maker_context, environment);
            functions_.map_to_order_state = maker_task.Get();
            if (!functions_.map_to_order_state) throw std::logic_error("function maker MapToOrderState returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-order_processed_endpoint_sink",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.order_processed_endpoint_sink(maker_context, environment, cfg.endpoints.orderProcessed);
            functions_.order_processed_endpoint_sink = maker_task.Get();
            if (!functions_.order_processed_endpoint_sink) throw std::logic_error("function maker OrderProcessedEndpointSink returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-process_order_item_sink",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.process_order_item_sink(maker_context, environment, cfg.endpoints.processOrderItem);
            functions_.process_order_item_sink = maker_task.Get();
            if (!functions_.process_order_item_sink) throw std::logic_error("function maker ProcessOrderItemSink returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-process_order_items",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.process_order_items(maker_context, environment);
            functions_.process_order_items = maker_task.Get();
            if (!functions_.process_order_items) throw std::logic_error("function maker ProcessOrderItems returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-process_order_source",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.process_order_source(maker_context, environment, cfg.endpoints.processOrder);
            functions_.process_order_source = maker_task.Get();
            if (!functions_.process_order_source) throw std::logic_error("function maker ProcessOrderSource returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));
    maker_tasks.push_back(userver::utils::Async(
        "service-function-maker-soft_deadline",
        [&makers_, &functions_, &cfg, &environment, maker_context, &maker_cancellation, &maker_error_mutex, &first_maker_error] {
          try {
            auto maker_task = makers_.soft_deadline(maker_context, environment);
            functions_.soft_deadline = maker_task.Get();
            if (!functions_.soft_deadline) throw std::logic_error("function maker SoftDeadline returned null");
          } catch (...) {
            maker_cancellation.request_stop();
            const std::lock_guard lock(maker_error_mutex);
            if (!first_maker_error) first_maker_error = std::current_exception();
            throw;
          }
        }));

  for (auto& task : maker_tasks) {
    try {
      task.Get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
  }
}

}  // namespace example::order_service::app