// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/grpc_service.generated.hpp"

#include <stdexcept>
#include <utility>

namespace example::order_service::app {


}  // namespace example::order_service::app