// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/makers.generated.hpp"
#include <stdexcept>
#include <userver/utils/async.hpp>
#include <userver/ugrpc/client/client_factory_component.hpp>
#include <userver/ugrpc/client/client_settings.hpp>
#include <utility>
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>

namespace example::order_service::app {
void ServiceMakers::initMakers(const userver::components::ComponentContext& components) {
  auto& makers_ = *this;
  (void)makers_; (void)components;
  map_order_item_result_to_order_state = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeMapOrderItemResultToOrderState(std::move(context), environment);
  };
  map_to_order_processed = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeMapToOrderProcessed(std::move(context), environment);
  };
  map_to_order_state = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeMapToOrderState(std::move(context), environment);
  };
  order_processed_endpoint_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::KafkaEndpointConfig& config) {
    return functions::MakeOrderProcessedEndpointSink(std::move(context), environment, config);
  };
  process_order_item_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::GrpcEndpointConfig& config) {
    return functions::MakeProcessOrderItemSink(std::move(context), environment, config);
  };
  process_order_items = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeProcessOrderItems(std::move(context), environment);
  };
  process_order_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::HttpEndpointConfig& config) {
    return functions::MakeProcessOrderSource(std::move(context), environment, config);
  };
  soft_deadline = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeSoftDeadline(std::move(context), environment);
  };

  makers_.inventory_service_api_client = [&components](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::GrpcDataConnectorConfig& config) {
    return userver::utils::Async(
        "service-grpc-client-maker-inventory_service_api_client",
        [&components, context = std::move(context), &environment, config]() mutable {
          (void)context;
          (void)environment;
          userver::ugrpc::client::ClientSettings settings{
              .client_name = config.name,
              .endpoint = config.address,
          };
          if (config.connectionsCount < 1) {
            throw std::invalid_argument(
                "gRPC connector " + config.name +
                " connectionsCount must be at least 1");
          }
          if (config.connectionsCount > 1) {
            settings.dedicated_methods_config.emplace(
                "ProcessOrderItem", config.connectionsCount);
          }
          return components
              .FindComponent<userver::ugrpc::client::ClientFactoryComponent>()
              .GetFactory()
              .MakeClient<::inventoryserviceapi::InventoryServiceApiClient>(std::move(settings));
        });
  };
}


}  // namespace example::order_service::app