// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include "orderservice/internal/app/substreams.generated.hpp"

#include "orderservice/internal/app/servers.generated.hpp"

#include "orderservice/internal/app/connectors.generated.hpp"

#include "orderservice/internal/app/clients.generated.hpp"

#include "orderservice/internal/app/endpoints.generated.hpp"


#include "orderservice/internal/app/makers.generated.hpp"
#include "orderservice/internal/app/functions.generated.hpp"
#include "orderservice/internal/app/streams.generated.hpp"
#include "orderservice/internal/app/bindings.generated.hpp"


#include <memory>

#include <functional>
#include <exception>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/components/statistics_storage.hpp>
#include <userver/engine/task/task_with_result.hpp>
#include <userver/engine/mutex.hpp>
#include <userver/ugrpc/client/client_factory_component.hpp>
#include <userver/ugrpc/client/client_settings.hpp>


#include "orderservice/config/config.generated.hpp"
#include "orderservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/component.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/runtime/telemetry/userver/log.hpp>
#include <servicelib/runtime/telemetry/userver/metrics.hpp>
#include <servicelib/runtime/telemetry/userver/tracing.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasink/grpc/userver.hpp>
#include <servicelib/datasource/http/userver.hpp>
#include <servicelib/datasink/kafka/userver.hpp>
#include <userver/kafka/producer_component.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated_client.usrv.pb.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>



namespace example::order_service::app {


struct DataTypes final {
  template <typename>
  struct DataType {};
};

using RuntimeConfigComponent =
    servicelib::config::ServicelibRuntimeComponent<config::Config>;

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  explicit ServiceGenerated(
      userver::utils::statistics::Storage& statistics_storage,
      const userver::components::ComponentContext& component_context);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;



 protected:
  ServiceMakers makers_;
  ServiceFunctions functions_;

  virtual void customMakersInit(servicelib::Context) {}
  virtual void customFunctionsInit(servicelib::Context) {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  friend struct ServiceEndpoints;
  void initMakers();
  void initInfrastructure(servicelib::Context context,
                          const config::Config& config);
  void initFunctions(servicelib::Context context, const config::Config& config);
  void initRuntime(servicelib::Context context);
  void initStreams(const config::Config& config);
  void initDataSinks(const config::Config& config);
  void initDataSources(const config::Config& config);
  void releaseRuntime() noexcept;




  ServiceStreams streams_;

  ServiceBindings bindings_;

 public:


  std::shared_ptr<servicelib::datasource::http::IUserverEndpoint>
  httpDataSourceEndpoint(int endpoint_id) const;


 private:
  ServiceEndpoints endpoints_;

  ServiceConnectors connectors_;
  ServiceClients clients_;
  ServiceServers servers_;
  ServiceSubStreams substreams_;

  [[maybe_unused]] const userver::components::ComponentContext& component_context_;
  servicelib::telemetry::userver_adapter::UserverMetrics metrics_;
  bool use_noop_logs_{false};
  bool use_noop_metrics_{false};
  bool use_noop_tracing_{false};
  bool user_lifecycle_started_{false};
};

class Service;

class OrderServiceComponent final : public userver::components::ComponentBase {
 public:
  static constexpr std::string_view kName = "service-order-service";

  OrderServiceComponent(
      const userver::components::ComponentConfig& config,
      const userver::components::ComponentContext& context);
  ~OrderServiceComponent() override;

  void OnAllComponentsAreStopping() override;

  Service& service() noexcept { return *service_; }
  std::shared_ptr<
      servicelib::datasource::http::IUserverEndpoint>
  httpDataSourceEndpoint(int endpoint_id) const;


  static userver::yaml_config::Schema GetStaticConfigSchema();

 private:
  std::unique_ptr<Service> service_;
};

}  // namespace example::order_service::app
