// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/service.generated.hpp"

#include <chrono>
#include <cstdlib>
#include <exception>
#include <mutex>
#include <vector>
#include <stdexcept>
#include <string>
#include <string_view>

#include <userver/yaml_config/merge_schemas.hpp>
#include <userver/engine/mutex.hpp>
#include <userver/utils/async.hpp>

#include "orderservice/internal/app/service.hpp"

namespace example::order_service::app {

ServiceGenerated::ServiceGenerated(
    userver::utils::statistics::Storage& statistics_storage,
    const userver::components::ComponentContext& component_context)
    : component_context_(component_context),
      metrics_(statistics_storage),
      use_noop_metrics_(std::getenv("SERVICELIB_NOOP_METRICS") != nullptr),
      use_noop_tracing_(std::getenv("SERVICELIB_NOOP_TRACING") != nullptr) {}

ServiceGenerated::~ServiceGenerated() { stop(); }

void ServiceGenerated::start() {
  try {
    const servicelib::Context context;
    serviceInit();
    initMakers();
    customMakersInit(context);
    initRuntime(context);
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    user_lifecycle_started_ = true;
    serviceStarted();
  } catch (...) {
    stop();
    releaseRuntime();
    throw;
  }
}

void ServiceGenerated::initMakers() {
  makers_.map_order_item_result_to_order_state = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::MapStreamConfig& config) {
    return functions::MakeMapOrderItemResultToOrderState(
        std::move(context), environment, config);
  };
  makers_.map_to_order_processed = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::MapStreamConfig& config) {
    return functions::MakeMapToOrderProcessed(
        std::move(context), environment, config);
  };
  makers_.map_to_order_state = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::MapStreamConfig& config) {
    return functions::MakeMapToOrderState(
        std::move(context), environment, config);
  };
  makers_.order_processed_endpoint_sink = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KafkaEndpointConfig& config) {
    return functions::MakeOrderProcessedEndpointSink(
        std::move(context), environment, config);
  };
  makers_.process_order_item_sink = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::GrpcEndpointConfig& config) {
    return functions::MakeProcessOrderItemSink(
        std::move(context), environment, config);
  };
  makers_.process_order_items = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::FlatMapStreamConfig& config) {
    return functions::MakeProcessOrderItems(
        std::move(context), environment, config);
  };
  makers_.process_order_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::HttpEndpointConfig& config) {
    return functions::MakeProcessOrderSource(
        std::move(context), environment, config);
  };
  makers_.soft_deadline = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::DelayStreamConfig& config) {
    return functions::MakeSoftDeadline(
        std::move(context), environment, config);
  };
  makers_.inventory_service_api_client = [this](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::GrpcDataConnectorConfig& config) {
    return userver::utils::Async(
        "service-grpc-client-maker-inventory_service_api_client",
        [this, context = std::move(context), &environment, config]() mutable {
          (void)context;
          (void)environment;
          userver::ugrpc::client::ClientSettings settings{
              .client_name = config.name,
              .endpoint = config.address,
          };
          if (config.connectionsCount < 1) {
            throw std::invalid_argument(
                "gRPC connector " + config.name +
                " connectionsCount must be at least 1");
          }
          if (config.connectionsCount > 1) {
            settings.dedicated_methods_config.emplace(
                "ProcessOrderItem", config.connectionsCount);
          }
          return component_context_
              .FindComponent<userver::ugrpc::client::ClientFactoryComponent>()
              .GetFactory()
              .MakeClient<inventoryserviceapi::InventoryServiceApiClient>(std::move(settings));
        });
  };
}

void ServiceGenerated::initInfrastructure(
    servicelib::Context context, const config::Config& cfg) {
std::stop_source maker_cancellation;
  userver::engine::Mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<userver::engine::TaskWithResult<void>> maker_tasks;
  if (!makers_.inventory_service_api_client) {
    throw std::logic_error("infrastructure maker inventory_service_api_client is not configured");
  }
  maker_tasks.push_back(userver::utils::Async(
      "service-grpc-client-init-inventory_service_api_client",
      [this, &cfg, maker_context, &maker_cancellation, &maker_error_mutex,
       &first_maker_error] {
        try {
          auto task = makers_.inventory_service_api_client(
              maker_context, *this, cfg.dataConnectors.inventoryServiceApi);
          connectors_.inventory_service_api_client.emplace(task.Get());
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) first_maker_error = std::current_exception();
          throw;
        }
      }));
  for (auto& task : maker_tasks) {
    try {
      task.Get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}

void ServiceGenerated::initFunctions(
    servicelib::Context context, const config::Config& cfg) {
  if (!makers_.map_order_item_result_to_order_state) {
    throw std::logic_error("function maker MapOrderItemResultToOrderState is not configured");
  }
  if (!makers_.map_to_order_processed) {
    throw std::logic_error("function maker MapToOrderProcessed is not configured");
  }
  if (!makers_.map_to_order_state) {
    throw std::logic_error("function maker MapToOrderState is not configured");
  }
  if (!makers_.order_processed_endpoint_sink) {
    throw std::logic_error("function maker OrderProcessedEndpointSink is not configured");
  }
  if (!makers_.process_order_item_sink) {
    throw std::logic_error("function maker ProcessOrderItemSink is not configured");
  }
  if (!makers_.process_order_items) {
    throw std::logic_error("function maker ProcessOrderItems is not configured");
  }
  if (!makers_.process_order_source) {
    throw std::logic_error("function maker ProcessOrderSource is not configured");
  }
  if (!makers_.soft_deadline) {
    throw std::logic_error("function maker SoftDeadline is not configured");
  }
  std::stop_source maker_cancellation;
  userver::engine::Mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<userver::engine::TaskWithResult<void>> maker_tasks;
  maker_tasks.reserve(8);
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-map_order_item_result_to_order_state", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.map_order_item_result_to_order_state(
              maker_context, *this, cfg.streams.mapOrderItemResultToOrderState);
          functions_.map_order_item_result_to_order_state = maker_task.Get();
          if (!functions_.map_order_item_result_to_order_state) {
            throw std::logic_error("function maker MapOrderItemResultToOrderState returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-map_to_order_processed", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.map_to_order_processed(
              maker_context, *this, cfg.streams.mapToOrderProcessed);
          functions_.map_to_order_processed = maker_task.Get();
          if (!functions_.map_to_order_processed) {
            throw std::logic_error("function maker MapToOrderProcessed returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-map_to_order_state", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.map_to_order_state(
              maker_context, *this, cfg.streams.mapToOrderState);
          functions_.map_to_order_state = maker_task.Get();
          if (!functions_.map_to_order_state) {
            throw std::logic_error("function maker MapToOrderState returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-order_processed_endpoint_sink", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.order_processed_endpoint_sink(
              maker_context, *this, cfg.endpoints.orderProcessed);
          functions_.order_processed_endpoint_sink = maker_task.Get();
          if (!functions_.order_processed_endpoint_sink) {
            throw std::logic_error("function maker OrderProcessedEndpointSink returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-process_order_item_sink", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.process_order_item_sink(
              maker_context, *this, cfg.endpoints.processOrderItem);
          functions_.process_order_item_sink = maker_task.Get();
          if (!functions_.process_order_item_sink) {
            throw std::logic_error("function maker ProcessOrderItemSink returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-process_order_items", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.process_order_items(
              maker_context, *this, cfg.streams.processOrderItems);
          functions_.process_order_items = maker_task.Get();
          if (!functions_.process_order_items) {
            throw std::logic_error("function maker ProcessOrderItems returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-process_order_source", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.process_order_source(
              maker_context, *this, cfg.endpoints.processOrder);
          functions_.process_order_source = maker_task.Get();
          if (!functions_.process_order_source) {
            throw std::logic_error("function maker ProcessOrderSource returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));
  maker_tasks.push_back(userver::utils::Async(
      "service-function-maker-soft_deadline", [this, &cfg, maker_context,
                                            &maker_cancellation,
                                            &maker_error_mutex,
                                            &first_maker_error] {
        try {
          auto maker_task = makers_.soft_deadline(
              maker_context, *this, cfg.streams.softDeadline);
          functions_.soft_deadline = maker_task.Get();
          if (!functions_.soft_deadline) {
            throw std::logic_error("function maker SoftDeadline returned null");
          }
        } catch (...) {
          maker_cancellation.request_stop();
          const std::lock_guard lock(maker_error_mutex);
          if (!first_maker_error) {
            first_maker_error = std::current_exception();
          }
          throw;
        }
      }));

  for (auto& task : maker_tasks) {
    try {
      task.Get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}

void ServiceGenerated::initRuntime(servicelib::Context context) {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  initInfrastructure(context, *config_snapshot);
  initFunctions(context, *config_snapshot);
  customFunctionsInit(context);
  initStreams(*config_snapshot);
  initDataSinks(*config_snapshot);
  initDataSources(*config_snapshot);

}

void ServiceGenerated::initStreams(const config::Config& cfg) {
  streams_.process_order = &servicelib::makeInputStreamRef<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr, ServiceGenerated>(cfg.streams.processOrder, nullptr, *this);
  auto& split_pipeline = (*streams_.process_order).template split<2>(cfg.streams.splitPipeline);
  streams_.split_pipeline = std::addressof(split_pipeline);
  auto& process_order_items = split_pipeline.template get<0>().flatMap(cfg.streams.processOrderItems, servicelib::StreamType<example::model::types::OrderItem>{}, servicelib::StreamFunction(std::ref(*functions_.process_order_items)));
  streams_.process_order_items = std::addressof(process_order_items);
  auto& process_order_item = process_order_items.sinkWithResult(cfg.streams.processOrderItem, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(ProcessOrderItemSinkBinding::Function{&bindings_.process_order_item}));
  streams_.process_order_item = process_order_item;
  auto& map_order_item_result_to_order_state = process_order_item.map(cfg.streams.mapOrderItemResultToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(std::ref(*functions_.map_order_item_result_to_order_state)));
  streams_.map_order_item_result_to_order_state = std::addressof(map_order_item_result_to_order_state);
  auto& soft_deadline = split_pipeline.template get<1>().delay(cfg.streams.softDeadline, servicelib::StreamFunction(std::ref(*functions_.soft_deadline)));
  streams_.soft_deadline = std::addressof(soft_deadline);
  auto& map_to_order_state = soft_deadline.map(cfg.streams.mapToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(std::ref(*functions_.map_to_order_state)));
  streams_.map_to_order_state = std::addressof(map_to_order_state);
  auto& merge_results = map_to_order_state.merge(cfg.streams.mergeResults, map_order_item_result_to_order_state, process_order_item.getErrorStream());
  streams_.merge_results = std::addressof(merge_results);
  auto& split_order_result = merge_results.template split<2>(cfg.streams.splitOrderResult);
  streams_.split_order_result = std::addressof(split_order_result);
  auto& map_to_order_processed = split_order_result.template get<0>().map(cfg.streams.mapToOrderProcessed, servicelib::StreamType<example::model::types::OrderProcessed>{}, servicelib::StreamFunction(std::ref(*functions_.map_to_order_processed)));
  streams_.map_to_order_processed = std::addressof(map_to_order_processed);
  [[maybe_unused]] auto& publish_order_processed = map_to_order_processed.sink(cfg.streams.publishOrderProcessed, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(PublishOrderProcessedSinkBinding::Function{&bindings_.publish_order_processed}));
  streams_.publish_order_processed = publish_order_processed;
  streams_.process_order->setSource(split_order_result.template get<1>());
}

void ServiceGenerated::initDataSinks(const config::Config& cfg) {
  (void)cfg;

  connectors_.inventory_service_api_sink =
      servicelib::datasink::grpc::UserverDataSink::make(
          streams_.process_order_item.get());
  endpoints_.process_order_item = std::make_shared<ProcessOrderItemGrpcSinkEndpoint>(
      streams_.process_order_item.get(),
      *functions_.process_order_item_sink,
      ProcessOrderItemGrpcClientFunction{&*connectors_.inventory_service_api_client});
  bindings_.process_order_item.consume =
      [endpoint = endpoints_.process_order_item.get()](
          servicelib::MessageContext context, const example::model::types::OrderItem& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::model::types::OrderItem>::make(value));
      };
  connectors_.inventory_service_api_sink->addEndpoint(endpoints_.process_order_item);
  registerDataSink(connectors_.inventory_service_api_sink);


  connectors_.publish_order_processed_producer =
      std::make_unique<servicelib::datasink::kafka::UserverProducerClient>(
          component_context_, cfg.dataConnectors.orderEvents);
  endpoints_.publish_order_processed = std::make_shared<PublishOrderProcessedKafkaSinkEndpoint>(
      streams_.publish_order_processed.get(), *connectors_.publish_order_processed_producer,
      *functions_.order_processed_endpoint_sink);
  bindings_.publish_order_processed.consume =
      [endpoint = endpoints_.publish_order_processed.get()](
          servicelib::MessageContext context, const example::model::types::OrderProcessed& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::model::types::OrderProcessed>::make(value));
      };
  registerDataSink(endpoints_.publish_order_processed);

}

void ServiceGenerated::initDataSources(
    const config::Config& cfg) {
  (void)cfg;

  connectors_.order_service_api_source =
      servicelib::datasource::http::UserverDataSource::make(
          *this, *streams_.process_order);
  endpoints_.process_order = ProcessOrderHTTPSourceConsumer::make(
      *this, *streams_.process_order,
      *functions_.process_order_source);
  connectors_.order_service_api_source->addEndpoint(endpoints_.process_order->endpoint());
  registerDataSource(connectors_.order_service_api_source);


}


void ServiceGenerated::stop() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (user_lifecycle_started_) {
      user_lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop();
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
  releaseRuntime();
}

void ServiceGenerated::releaseRuntime() noexcept {
  // ServiceApp::stop() has already stopped and released the runtime-owned
  // graph. Generated fields are only typed construction/runtime views.
  connectors_ = {};
  endpoints_ = {};
  bindings_ = {};
  streams_ = {};
  functions_ = {};
}

std::shared_ptr<
    servicelib::datasource::http::IUserverEndpoint>
ServiceGenerated::httpDataSourceEndpoint(int endpoint_id) const {
  if (auto endpoint = connectors_.order_service_api_source
          ? connectors_.order_service_api_source->endpoint(endpoint_id) : nullptr) {
    return endpoint;
  }
  throw std::invalid_argument(
      "HTTP datasource endpoint not found: " + std::to_string(endpoint_id));
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return servicelib::telemetry::userver_adapter::UserverLogger::instance();
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return use_noop_metrics_ ? servicelib::metrics::NoopMetrics::instance()
                           : metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return use_noop_tracing_
             ? nullptr
             : &servicelib::telemetry::userver_adapter::UserverTracing::instance();
}

OrderServiceComponent::OrderServiceComponent(
    const userver::components::ComponentConfig& component_config,
    const userver::components::ComponentContext& context)
    : ComponentBase(component_config, context),
      service_(std::make_unique<Service>(
          context.FindComponent<userver::components::StatisticsStorage>()
              .GetStorage(),
          context)) {
  context.FindComponent<RuntimeConfigComponent>();
  service_->start();
}

OrderServiceComponent::~OrderServiceComponent() { service_->stop(); }

void OrderServiceComponent::OnAllComponentsAreStopping() { service_->stop(); }

std::shared_ptr<
    servicelib::datasource::http::IUserverEndpoint>
OrderServiceComponent::httpDataSourceEndpoint(int endpoint_id) const {
  return service_->httpDataSourceEndpoint(endpoint_id);
}



userver::yaml_config::Schema OrderServiceComponent::GetStaticConfigSchema() {
  return userver::yaml_config::MergeSchemas<
      userver::components::ComponentBase>(R"(
type: object
description: Config-driven servicelib service.
additionalProperties: false
properties: {}
)");
}

}  // namespace example::order_service::app