// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/components/statistics_storage.hpp>
#include <userver/ugrpc/client/client_factory_component.hpp>
#include <userver/ugrpc/client/client_settings.hpp>


#include "orderservice/config/config.generated.hpp"
#include "orderservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/component.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/runtime/telemetry/userver/log.hpp>
#include <servicelib/runtime/telemetry/userver/metrics.hpp>
#include <servicelib/runtime/telemetry/userver/tracing.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasink/grpc/userver.hpp>
#include <servicelib/datasource/http/userver.hpp>
#include <servicelib/datasink/kafka/userver.hpp>
#include <userver/kafka/producer_component.hpp>

#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <model_cpp/include/example/model/types/order_item.hpp>
#include <model_cpp/include/example/model/types/order_item_result.hpp>
#include <model_cpp/include/example/model/types/order_processed.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated_client.usrv.pb.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>


namespace example::order_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

using RuntimeConfigComponent =
    servicelib::config::ServicelibRuntimeComponent<config::Config>;

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  explicit ServiceGenerated(
      userver::utils::statistics::Storage& statistics_storage,
      const userver::components::ComponentContext& component_context);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

 protected:
  struct ServiceMakers final {
    std::function<std::unique_ptr<functions::MapOrderItemResultToOrderState>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::MapStreamConfig&)> map_order_item_result_to_order_state;
    std::function<std::unique_ptr<functions::MapToOrderProcessed>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::MapStreamConfig&)> map_to_order_processed;
    std::function<std::unique_ptr<functions::MapToOrderState>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::MapStreamConfig&)> map_to_order_state;
    std::function<std::unique_ptr<functions::OrderProcessedEndpointSink>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::KafkaEndpointConfig&)> order_processed_endpoint_sink;
    std::function<std::unique_ptr<functions::ProcessOrderItemSink>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::GrpcEndpointConfig&)> process_order_item_sink;
    std::function<std::unique_ptr<functions::ProcessOrderItems>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::FlatMapStreamConfig&)> process_order_items;
    std::function<std::unique_ptr<functions::ProcessOrderSource>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::HttpEndpointConfig&)> process_order_source;
    std::function<std::unique_ptr<functions::SoftDeadline>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::DelayStreamConfig&)> soft_deadline;
  };
  struct ServiceFunctions final {
    std::unique_ptr<functions::MapOrderItemResultToOrderState> map_order_item_result_to_order_state;
    std::unique_ptr<functions::MapToOrderProcessed> map_to_order_processed;
    std::unique_ptr<functions::MapToOrderState> map_to_order_state;
    std::unique_ptr<functions::OrderProcessedEndpointSink> order_processed_endpoint_sink;
    std::unique_ptr<functions::ProcessOrderItemSink> process_order_item_sink;
    std::unique_ptr<functions::ProcessOrderItems> process_order_items;
    std::unique_ptr<functions::ProcessOrderSource> process_order_source;
    std::unique_ptr<functions::SoftDeadline> soft_deadline;
  };

  ServiceMakers makers_;
  ServiceFunctions functions_;

  virtual void customMakersInit() {}
  virtual void customFunctionsInit() {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  void initMakers();
  void initFunctions(const config::Config& config);
  void initRuntime();
  void initStreams(const config::Config& config);
  void initDataSinks(const config::Config& config);
  void initDataSources(const config::Config& config);
  void releaseRuntime() noexcept;

  using ProcessOrderInput =
      servicelib::InputStream<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
                              ServiceGenerated>;


  struct ServiceStreams final {
    ProcessOrderInput* process_order{};
    servicelib::StreamBase* split_pipeline{nullptr};

    servicelib::StreamBase* process_order_items{nullptr};

    servicelib::SinkEndpointStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, example::order_service::types::OrderState> process_order_item;

    servicelib::StreamBase* map_order_item_result_to_order_state{nullptr};

    servicelib::StreamBase* soft_deadline{nullptr};

    servicelib::StreamBase* map_to_order_state{nullptr};

    servicelib::StreamBase* merge_results{nullptr};

    servicelib::StreamBase* split_order_result{nullptr};

    servicelib::StreamBase* map_to_order_processed{nullptr};

    servicelib::SinkEndpointStreamRef<example::model::types::OrderProcessed, std::monostate, std::exception_ptr> publish_order_processed;

  };
  ServiceStreams streams_;

  struct ProcessOrderItemSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::model::types::OrderItem&)>
        consume;
    struct Function final {
      ProcessOrderItemSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::model::types::OrderItem& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct PublishOrderProcessedSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::model::types::OrderProcessed&)>
        consume;
    struct Function final {
      PublishOrderProcessedSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::model::types::OrderProcessed& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };

  struct ServiceBindings final {
    ProcessOrderItemSinkBinding process_order_item;
    PublishOrderProcessedSinkBinding publish_order_processed;
  };
  ServiceBindings bindings_;



  struct ProcessOrderItemGrpcClientFunction final {
    inventoryserviceapi::InventoryServiceApiClient* client;
    decltype(auto) operator()(
        const processorderitem::ProcessOrderItemRequest& request,
        userver::ugrpc::client::CallOptions options) const {
      return client->ProcessOrderItem(request, std::move(options));
    }
  };
  using ProcessOrderItemGrpcSinkEndpoint =
      servicelib::datasink::grpc::NoStreamingEndpoint<
          processorderitem::ProcessOrderItemRequest, processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItemSink, ProcessOrderItemGrpcClientFunction, example::order_service::types::OrderState>;

  using ProcessOrderHTTPSourceConsumer =
      servicelib::datasource::http::UserverEndpointConsumer<
          example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
          ServiceGenerated, functions::ProcessOrderSource>;

 public:
  std::shared_ptr<servicelib::datasource::http::IUserverEndpoint>
  httpDataSourceEndpoint(int endpoint_id) const;
 private:



  using PublishOrderProcessedKafkaSinkEndpoint =
      servicelib::datasink::kafka::Endpoint<
          example::model::types::OrderProcessed, std::monostate, functions::OrderProcessedEndpointSink, std::exception_ptr>;




  struct ServiceEndpoints final {
    std::shared_ptr<ProcessOrderItemGrpcSinkEndpoint> process_order_item;
    std::shared_ptr<ProcessOrderHTTPSourceConsumer> process_order;
    std::shared_ptr<PublishOrderProcessedKafkaSinkEndpoint> publish_order_processed;
  };
  ServiceEndpoints endpoints_;

  struct ServiceConnectors final {
    std::optional<inventoryserviceapi::InventoryServiceApiClient> inventory_service_api_client;
    std::shared_ptr<
        servicelib::datasink::grpc::UserverDataSink> inventory_service_api_sink;
    std::shared_ptr<
        servicelib::datasource::http::UserverDataSource> order_service_api_source;
    std::unique_ptr<
        servicelib::datasink::kafka::UserverProducerClient> publish_order_processed_producer;
  };
  ServiceConnectors connectors_;

  [[maybe_unused]] const userver::components::ComponentContext& component_context_;
  servicelib::telemetry::userver_adapter::UserverMetrics metrics_;
  bool use_noop_metrics_{false};
  bool use_noop_tracing_{false};
  bool user_lifecycle_started_{false};
};

class Service;

class OrderServiceComponent final : public userver::components::ComponentBase {
 public:
  static constexpr std::string_view kName = "order-service";

  OrderServiceComponent(
      const userver::components::ComponentConfig& config,
      const userver::components::ComponentContext& context);
  ~OrderServiceComponent() override;

  void OnAllComponentsAreStopping() override;

  Service& service() noexcept { return *service_; }
  std::shared_ptr<
      servicelib::datasource::http::IUserverEndpoint>
  httpDataSourceEndpoint(int endpoint_id) const;


  static userver::yaml_config::Schema GetStaticConfigSchema();

 private:
  std::unique_ptr<Service> service_;
};

}  // namespace example::order_service::app