// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/service.generated.hpp"

#include <chrono>
#include <exception>
#include <stdexcept>
#include <string>
#include <string_view>

#include <userver/yaml_config/merge_schemas.hpp>

#include "orderservice/internal/app/service.hpp"

namespace example::order_service::app {

ServiceGenerated::ServiceGenerated(
    userver::utils::statistics::Storage& statistics_storage,
    const userver::components::ComponentContext& component_context)
    : component_context_(component_context), metrics_(statistics_storage) {}

ServiceGenerated::~ServiceGenerated() { stop(); }

void ServiceGenerated::start() {
  try {
    serviceInit();
    customMakersInit();
    initRuntime();
    customFunctionsInit();
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    user_lifecycle_started_ = true;
    serviceStarted();
  } catch (...) {
    stop();
    releaseRuntime();
    throw;
  }
}

void ServiceGenerated::initRuntime() {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  initStreams(*config_snapshot);
  initDataSinks(*config_snapshot);
  initDataSources(*config_snapshot);

}

void ServiceGenerated::initStreams(const config::Config& cfg) {
  input_8_ = servicelib::makeInputStream<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr, ServiceGenerated>(cfg.streams.processOrder, nullptr, *this);
  auto& stream_12 = (*input_8_).template split<2>(cfg.streams.splitPipeline);
  auto& stream_10 = stream_12.template get<0>().flatMap(cfg.streams.processOrderItems, servicelib::StreamType<example::model::types::OrderItem>{}, servicelib::StreamFunction(functions::ProcessOrderItems{}));
  sink_binding_9_ = std::make_shared<SinkBinding9>();
  auto& stream_9 = stream_10.sinkWithResult(cfg.streams.processOrderItem, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamFunction(SinkBinding9::Function{sink_binding_9_}));
  sink_binding_9_->consumeResult = [&stream_9](servicelib::MessageContext context, servicelib::Payload<example::model::types::OrderItemResult> payload) { stream_9.consumeResult(std::move(context), std::move(payload)); };
  auto& stream_5 = stream_9.map(cfg.streams.mapOrderItemResultToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(functions::MapOrderItemResultToOrderState{}));
  auto& stream_11 = stream_12.template get<1>().delay(cfg.streams.softDeadline, servicelib::StreamFunction(functions::SoftDeadline{std::chrono::milliseconds{cfg.streams.softDeadline.duration}}));
  auto& stream_6 = stream_11.map(cfg.streams.mapToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(functions::MapToOrderState{}));
  auto& stream_7 = stream_6.merge(cfg.streams.mergeResults, stream_5);
  input_8_->setSource(stream_7);
}

void ServiceGenerated::initDataSinks(const config::Config& cfg) {

  grpc_client_1_.emplace(
      component_context_
          .FindComponent<userver::ugrpc::client::ClientFactoryComponent>()
          .GetFactory()
          .MakeClient<inventoryserviceapi::InventoryServiceApiClient>(
              "inventory-service-api",
              cfg.dataConnectors.inventoryServiceApi.address));
  grpc_sink_1_ =
      std::make_shared<servicelib::datasink::grpc::UserverDataSink>(
          *this, cfg.dataConnectors.inventoryServiceApi.id);
  grpc_sink_endpoint_9_ = std::make_shared<GrpcSinkEndpoint9>(
      *this, cfg.endpoints.processOrderItem.id, functions::ProcessOrderItem{},
      GrpcClientFunction9{&*grpc_client_1_},
      [binding = sink_binding_9_](
          servicelib::MessageContext context,
          servicelib::Payload<example::model::types::OrderItemResult> result) {
        if (binding->consumeResult) {
          binding->consumeResult(std::move(context), std::move(result));
        }
      },
      typename GrpcSinkEndpoint9::ErrorOutput{}
  );
  sink_binding_9_->consume =
      [endpoint = grpc_sink_endpoint_9_](
          servicelib::MessageContext context, const example::model::types::OrderItem& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::model::types::OrderItem>::make(value));
      };
  grpc_sink_1_->addEndpoint(grpc_sink_endpoint_9_);
  registerDataSink(grpc_sink_1_);



}

void ServiceGenerated::initDataSources(
    const config::Config& cfg) {

  http_source_2_ =
      std::make_shared<servicelib::datasource::http::UserverDataSource>(
          *this, cfg.dataConnectors.orderServiceApi.id);
  http_source_consumer_8_ = HTTPSourceConsumer8::make(
      *this, input_8_, functions::ProcessOrder{});
  http_source_2_->addEndpoint(http_source_consumer_8_->endpoint());
  registerDataSource(http_source_2_);


}


void ServiceGenerated::stop() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (user_lifecycle_started_) {
      user_lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop();
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
  releaseRuntime();
}

void ServiceGenerated::releaseRuntime() noexcept {
  grpc_sink_1_.reset();

  http_source_2_.reset();

  http_source_consumer_8_.reset();

  grpc_sink_endpoint_9_.reset();
  grpc_client_1_.reset();


  sink_binding_9_.reset();



  input_8_.reset();

}

std::shared_ptr<
    servicelib::datasource::http::IUserverEndpoint>
ServiceGenerated::httpDataSourceEndpoint(int endpoint_id) const {
  if (auto endpoint = http_source_2_
          ? http_source_2_->endpoint(endpoint_id) : nullptr) {
    return endpoint;
  }
  throw std::invalid_argument(
      "HTTP datasource endpoint not found: " + std::to_string(endpoint_id));
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return servicelib::telemetry::userver_adapter::UserverLogger::instance();
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return &servicelib::telemetry::userver_adapter::UserverTracing::instance();
}

OrderServiceComponent::OrderServiceComponent(
    const userver::components::ComponentConfig& component_config,
    const userver::components::ComponentContext& context)
    : ComponentBase(component_config, context),
      service_(std::make_unique<Service>(
          context.FindComponent<userver::components::StatisticsStorage>()
              .GetStorage(),
          context)) {
  context.FindComponent<RuntimeConfigComponent>();
  service_->start();
}

OrderServiceComponent::~OrderServiceComponent() { service_->stop(); }

std::shared_ptr<
    servicelib::datasource::http::IUserverEndpoint>
OrderServiceComponent::httpDataSourceEndpoint(int endpoint_id) const {
  return service_->httpDataSourceEndpoint(endpoint_id);
}



userver::yaml_config::Schema OrderServiceComponent::GetStaticConfigSchema() {
  return userver::yaml_config::MergeSchemas<
      userver::components::ComponentBase>(R"(
type: object
description: Config-driven servicelib service.
additionalProperties: false
properties: {}
)");
}

}  // namespace example::order_service::app