// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/components/statistics_storage.hpp>
#include <userver/ugrpc/client/client_factory_component.hpp>


#include "orderservice/config/config.generated.hpp"
#include "runtime/config/component.hpp"
#include "runtime/serviceapp.hpp"
#include "runtime/telemetry/userver/log.hpp"
#include "runtime/telemetry/userver/metrics.hpp"
#include "runtime/telemetry/userver/tracing.hpp"
#include "transformation/streams.hpp"
#include "datasink/grpc/userver.hpp"
#include "datasource/http/userver.hpp"

#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <model/include/example/model/types/order_item.hpp>
#include <model/include/example/model/types/order_item_result.hpp>
#include <orderservice/internal/functions/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/map_to_order_state.hpp>
#include <orderservice/internal/functions/process_order.hpp>
#include <orderservice/internal/functions/process_order_item.hpp>
#include <orderservice/internal/functions/process_order_items.hpp>
#include <orderservice/internal/functions/soft_deadline.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated_client.usrv.pb.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>


namespace example::order_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

using RuntimeConfigComponent =
    servicelib::config::ServicelibRuntimeComponent<config::Config>;

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  explicit ServiceGenerated(
      userver::utils::statistics::Storage& statistics_storage,
      const userver::components::ComponentContext& component_context);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

 protected:
  virtual void customMakersInit() {}
  virtual void customFunctionsInit() {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  void initRuntime();
  void initStreams(const config::Config& config);
  void initDataSinks(const config::Config& config);
  void initDataSources(const config::Config& config);
  void releaseRuntime() noexcept;

  using Input8 =
      servicelib::InputStream<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
                              ServiceGenerated>;
  std::shared_ptr<Input8> input_8_;



  struct SinkBinding9 final {
    std::function<void(servicelib::MessageContext, const example::model::types::OrderItem&)>
        consume;
    std::function<void(servicelib::MessageContext,
                       servicelib::Payload<example::model::types::OrderItemResult>)>
        consumeResult;
    struct Function final {
      std::shared_ptr<SinkBinding9> binding;
      void operator()(servicelib::MessageContext context,
                      const example::model::types::OrderItem& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  std::shared_ptr<SinkBinding9> sink_binding_9_;



  struct GrpcClientFunction9 final {
    inventoryserviceapi::InventoryServiceApiClient* client;
    decltype(auto) operator()(
        const processorderitem::ProcessOrderItemRequest& request,
        userver::ugrpc::client::CallOptions options) const {
      return client->ProcessOrderItem(request, std::move(options));
    }
  };
  using GrpcSinkEndpoint9 =
      servicelib::datasink::grpc::NoStreamingEndpoint<
          processorderitem::ProcessOrderItemRequest, processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItem, GrpcClientFunction9>;
  std::shared_ptr<GrpcSinkEndpoint9> grpc_sink_endpoint_9_;

  std::optional<inventoryserviceapi::InventoryServiceApiClient> grpc_client_1_;
  std::shared_ptr<
      servicelib::datasink::grpc::UserverDataSink> grpc_sink_1_;

  using HTTPSourceConsumer8 =
      servicelib::datasource::http::UserverEndpointConsumer<
          example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
          ServiceGenerated, functions::ProcessOrder>;
  std::shared_ptr<HTTPSourceConsumer8> http_source_consumer_8_;

 public:
  std::shared_ptr<servicelib::datasource::http::IUserverEndpoint>
  httpDataSourceEndpoint(int endpoint_id) const;
 private:


  std::shared_ptr<
      servicelib::datasource::http::UserverDataSource> http_source_2_;






  const userver::components::ComponentContext& component_context_;
  servicelib::telemetry::userver_adapter::UserverMetrics metrics_;
  bool user_lifecycle_started_{false};
};

class Service;

class OrderServiceComponent final : public userver::components::ComponentBase {
 public:
  static constexpr std::string_view kName = "order-service";

  OrderServiceComponent(
      const userver::components::ComponentConfig& config,
      const userver::components::ComponentContext& context);
  ~OrderServiceComponent() override;

  Service& service() noexcept { return *service_; }
  std::shared_ptr<
      servicelib::datasource::http::IUserverEndpoint>
  httpDataSourceEndpoint(int endpoint_id) const;


  static userver::yaml_config::Schema GetStaticConfigSchema();

 private:
  std::unique_ptr<Service> service_;
};

}  // namespace example::order_service::app