// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <memory>
#include <servicelib/datasource/http/userver.hpp>

namespace example::order_service::app {
struct ServiceServers final {
  std::shared_ptr<servicelib::datasource::http::UserverDataSource> order_service_api_source;
};

}  // namespace example::order_service::app