// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <functional>
#include <memory>
#include <optional>
#include <servicelib/transformation/streams.hpp>
#include "orderservice/internal/app/bindings.generated.hpp"
#include "orderservice/config/config.generated.hpp"
#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated_client.usrv.pb.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>

namespace example::order_service::app {
class ServiceGenerated;
  using ProcessOrderInput =
      servicelib::InputStream<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
                              ServiceGenerated>;

struct ServiceFunctions;
struct ServiceStreams final {
  void initStreams(const config::Config& cfg, ServiceGenerated& service);
  void build(const config::Config& cfg, ServiceGenerated& service, ServiceFunctions& functions, ServiceBindings& bindings);
  servicelib::InputStream<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr, ServiceGenerated>* process_order{};
  servicelib::StreamBase* split_pipeline{nullptr};
  servicelib::StreamBase* process_order_items{nullptr};
  servicelib::SinkEndpointStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, example::order_service::types::OrderState> process_order_item;
  servicelib::StreamBase* map_order_item_result_to_order_state{nullptr};
  servicelib::StreamBase* soft_deadline{nullptr};
  servicelib::StreamBase* map_to_order_state{nullptr};
  servicelib::StreamBase* merge_results{nullptr};
  servicelib::StreamBase* split_order_result{nullptr};
  servicelib::StreamBase* map_to_order_processed{nullptr};
  servicelib::SinkEndpointStreamRef<example::model::types::OrderProcessed, std::monostate, std::exception_ptr> publish_order_processed;
};

}  // namespace example::order_service::app