// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/streams.generated.hpp"
#include "orderservice/internal/app/service.generated.hpp"
#include "orderservice/internal/app/functions.generated.hpp"
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>

namespace example::order_service::app {
void ServiceStreams::initStreams(const config::Config& cfg, ServiceGenerated& service) {
  auto& streams_ = *this;
  (void)streams_; (void)cfg; (void)service;
  streams_.process_order = &servicelib::makeInputStreamRef<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr, ServiceGenerated>(cfg.streams.processOrder, nullptr, service);

}

void ServiceStreams::build(const config::Config& cfg, ServiceGenerated& service, ServiceFunctions& functions, ServiceBindings& bindings) {
  auto& streams_ = *this;
  auto& functions_ = functions;
  auto& bindings_ = bindings;
  (void)streams_; (void)functions_; (void)bindings_; (void)cfg; (void)service;

  auto& split_pipeline = (*streams_.process_order).template split<2>(cfg.streams.splitPipeline);
  streams_.split_pipeline = std::addressof(split_pipeline);
  auto& process_order_items = split_pipeline.template get<0>().flatMap(cfg.streams.processOrderItems, servicelib::StreamType<example::model::types::OrderItem>{}, servicelib::StreamFunction(std::ref(*functions_.process_order_items)));
  streams_.process_order_items = std::addressof(process_order_items);
  auto& process_order_item = process_order_items.sinkWithResult(cfg.streams.processOrderItem, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(ProcessOrderItemSinkBinding::Function{&bindings_.process_order_item}));
  streams_.process_order_item = process_order_item;
  auto& map_order_item_result_to_order_state = process_order_item.map(cfg.streams.mapOrderItemResultToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(std::ref(*functions_.map_order_item_result_to_order_state)));
  streams_.map_order_item_result_to_order_state = std::addressof(map_order_item_result_to_order_state);
  auto& soft_deadline = split_pipeline.template get<1>().delay(cfg.streams.softDeadline, servicelib::StreamFunction(std::ref(*functions_.soft_deadline)));
  streams_.soft_deadline = std::addressof(soft_deadline);
  auto& map_to_order_state = soft_deadline.map(cfg.streams.mapToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(std::ref(*functions_.map_to_order_state)));
  streams_.map_to_order_state = std::addressof(map_to_order_state);
  auto& merge_results = map_to_order_state.merge(cfg.streams.mergeResults, map_order_item_result_to_order_state, process_order_item.getErrorStream());
  streams_.merge_results = std::addressof(merge_results);
  auto& split_order_result = merge_results.template split<2>(cfg.streams.splitOrderResult);
  streams_.split_order_result = std::addressof(split_order_result);
  auto& map_to_order_processed = split_order_result.template get<0>().map(cfg.streams.mapToOrderProcessed, servicelib::StreamType<example::model::types::OrderProcessed>{}, servicelib::StreamFunction(std::ref(*functions_.map_to_order_processed)));
  streams_.map_to_order_processed = std::addressof(map_to_order_processed);
  [[maybe_unused]] auto& publish_order_processed = map_to_order_processed.sink(cfg.streams.publishOrderProcessed, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(PublishOrderProcessedSinkBinding::Function{&bindings_.publish_order_processed}));
  streams_.publish_order_processed = publish_order_processed;
  streams_.process_order->setSource(split_order_result.template get<1>());

}

}  // namespace example::order_service::app