// Code generated by servicegen. DO NOT EDIT.
#include <tuple>
#include <functional>

#include "orderservice/internal/app/streams.generated.hpp"
#include "orderservice/internal/app/service.generated.hpp"
#include "orderservice/internal/app/functions.generated.hpp"
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>

namespace example::order_service::app {
void ServiceStreams::initStreams(const config::Config& cfg, ServiceGenerated& service) {
  auto& streams_ = *this;
  (void)streams_; (void)cfg; (void)service;
  streams_.process_order = &servicelib::makeInputStreamRef<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr, ServiceGenerated>(cfg.streams.processOrder, nullptr, service);

}

void ServiceStreams::build(const config::Config& cfg, ServiceGenerated& service, ServiceFunctions& functions, ServiceBindings& bindings) {
  auto& streams_ = *this;
  auto& functions_ = functions;
  auto& bindings_ = bindings;
  (void)streams_; (void)functions_; (void)bindings_; (void)cfg; (void)service;

  using process_order_items_stream = servicelib::Stream<example::order_service::types::Order, servicelib::StreamConsumer<example::order_service::types::Order>, ServiceGenerated>::FlatMapImpl<example::model::types::OrderItem, decltype(std::ref(*functions_.process_order_items)), servicelib::StreamConsumer<example::model::types::OrderItem>>;
  using split_pipeline_branch_0 = servicelib::Stream<example::order_service::types::Order, servicelib::StreamConsumer<example::order_service::types::Order>, ServiceGenerated>::SplitLinkImpl<example::order_service::types::Order, process_order_items_stream, ServiceGenerated>;
  using map_to_order_processed_stream = servicelib::Stream<example::order_service::types::OrderState, servicelib::StreamConsumer<example::order_service::types::OrderState>, ServiceGenerated>::MapImpl<example::model::types::OrderProcessed, decltype(std::ref(*functions_.map_to_order_processed)), servicelib::StreamConsumer<example::model::types::OrderProcessed>>;
  using split_order_result_branch_0 = servicelib::Stream<example::order_service::types::OrderState, servicelib::StreamConsumer<example::order_service::types::OrderState>, ServiceGenerated>::SplitLinkImpl<example::order_service::types::OrderState, map_to_order_processed_stream, ServiceGenerated>;
  using split_order_result_branch_1 = servicelib::Stream<example::order_service::types::OrderState, servicelib::StreamConsumer<example::order_service::types::OrderState>, ServiceGenerated>::SplitLinkImpl<example::order_service::types::OrderState, servicelib::StreamConsumer<example::order_service::types::OrderState>, ServiceGenerated>;
  using split_order_result_stream = servicelib::Stream<example::order_service::types::OrderState, servicelib::StreamConsumer<example::order_service::types::OrderState>, ServiceGenerated>::SplitImpl<std::tuple<split_order_result_branch_0&, split_order_result_branch_1&>>;
  using merge_results_stream = servicelib::Stream<example::order_service::types::OrderState, servicelib::StreamConsumer<example::order_service::types::OrderState>, ServiceGenerated>::MergeImpl<3, split_order_result_stream>;
  using merge_results_owner_link = servicelib::Stream<example::order_service::types::OrderState, servicelib::StreamConsumer<example::order_service::types::OrderState>, ServiceGenerated>::MergeLinkImpl<3, true, merge_results_stream>;
  using merge_results_reference_link = servicelib::Stream<example::order_service::types::OrderState, servicelib::StreamConsumer<example::order_service::types::OrderState>, ServiceGenerated>::MergeLinkImpl<3, false, merge_results_stream>;
  using map_to_order_state_stream = servicelib::Stream<example::order_service::types::Order, servicelib::StreamConsumer<example::order_service::types::Order>, ServiceGenerated>::MapImpl<example::order_service::types::OrderState, decltype(std::ref(*functions_.map_to_order_state)), merge_results_owner_link>;
  using soft_deadline_stream = servicelib::Stream<example::order_service::types::Order, servicelib::StreamConsumer<example::order_service::types::Order>, ServiceGenerated>::DelayImpl<decltype(std::ref(*functions_.soft_deadline)), map_to_order_state_stream>;
  using split_pipeline_branch_1 = servicelib::Stream<example::order_service::types::Order, servicelib::StreamConsumer<example::order_service::types::Order>, ServiceGenerated>::SplitLinkImpl<example::order_service::types::Order, soft_deadline_stream, ServiceGenerated>;
  using split_pipeline_stream = servicelib::Stream<example::order_service::types::Order, servicelib::StreamConsumer<example::order_service::types::Order>, ServiceGenerated>::SplitImpl<std::tuple<split_pipeline_branch_0&, split_pipeline_branch_1&>>;
  using map_order_item_result_to_order_state_stream = servicelib::Stream<example::model::types::OrderItemResult, servicelib::StreamConsumer<example::model::types::OrderItemResult>, ServiceGenerated>::MapImpl<example::order_service::types::OrderState, decltype(std::ref(*functions_.map_order_item_result_to_order_state)), merge_results_reference_link>;
  auto split_pipeline_owner = service.makeStream<split_pipeline_stream>(cfg.streams.splitPipeline, static_cast<servicelib::StreamConsumer<example::order_service::types::Order>&>((*streams_.process_order)).getSerde(), &service, service.makeStream<split_pipeline_branch_0>(), service.makeStream<split_pipeline_branch_1>());
  auto& split_pipeline = *split_pipeline_owner;
  streams_.split_pipeline = std::addressof(split_pipeline);
  auto process_order_items_owner = service.makeStream<process_order_items_stream>(cfg.streams.processOrderItems, static_cast<servicelib::StreamConsumer<example::order_service::types::Order>&>(split_pipeline.template get<0>()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.process_order_items)));
  auto& process_order_items = *process_order_items_owner;
  streams_.process_order_items = std::addressof(process_order_items);
  auto& process_order_item = process_order_items.sinkWithResult(cfg.streams.processOrderItem, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(ProcessOrderItemSinkBinding::Function{&bindings_.process_order_item}));
  streams_.process_order_item = process_order_item;
  auto map_order_item_result_to_order_state_owner = service.makeStream<map_order_item_result_to_order_state_stream>(cfg.streams.mapOrderItemResultToOrderState, static_cast<servicelib::StreamConsumer<example::model::types::OrderItemResult>&>(process_order_item).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.map_order_item_result_to_order_state)));
  auto& map_order_item_result_to_order_state = *map_order_item_result_to_order_state_owner;
  streams_.map_order_item_result_to_order_state = std::addressof(map_order_item_result_to_order_state);
  auto soft_deadline_owner = service.makeStream<soft_deadline_stream>(cfg.streams.softDeadline, static_cast<servicelib::StreamConsumer<example::order_service::types::Order>&>(split_pipeline.template get<1>()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.soft_deadline)));
  auto& soft_deadline = *soft_deadline_owner;
  streams_.soft_deadline = std::addressof(soft_deadline);
  auto map_to_order_state_owner = service.makeStream<map_to_order_state_stream>(cfg.streams.mapToOrderState, static_cast<servicelib::StreamConsumer<example::order_service::types::Order>&>(soft_deadline).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.map_to_order_state)));
  auto& map_to_order_state = *map_to_order_state_owner;
  streams_.map_to_order_state = std::addressof(map_to_order_state);
  auto merge_results_owner = service.makeStream<merge_results_stream>(cfg.streams.mergeResults, static_cast<servicelib::StreamConsumer<example::order_service::types::OrderState>&>(map_to_order_state).getSerde(), &service);
  auto& merge_results = *merge_results_owner;
  streams_.merge_results = std::addressof(merge_results);
  auto split_order_result_owner = service.makeStream<split_order_result_stream>(cfg.streams.splitOrderResult, static_cast<servicelib::StreamConsumer<example::order_service::types::OrderState>&>(merge_results).getSerde(), &service, service.makeStream<split_order_result_branch_0>(), service.makeStream<split_order_result_branch_1>());
  auto& split_order_result = *split_order_result_owner;
  streams_.split_order_result = std::addressof(split_order_result);
  auto map_to_order_processed_owner = service.makeStream<map_to_order_processed_stream>(cfg.streams.mapToOrderProcessed, static_cast<servicelib::StreamConsumer<example::order_service::types::OrderState>&>(split_order_result.template get<0>()).getSerde(), &service, servicelib::StreamFunction(std::ref(*functions_.map_to_order_processed)));
  auto& map_to_order_processed = *map_to_order_processed_owner;
  streams_.map_to_order_processed = std::addressof(map_to_order_processed);
  [[maybe_unused]] auto& publish_order_processed = map_to_order_processed.sink(cfg.streams.publishOrderProcessed, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(PublishOrderProcessedSinkBinding::Function{&bindings_.publish_order_processed}));
  streams_.publish_order_processed = publish_order_processed;
  split_order_result.template get<0>().connect(std::move(map_to_order_processed_owner));
  merge_results.connect(std::move(split_order_result_owner));
  map_to_order_state.connect(service.makeStream<merge_results_owner_link>(std::move(merge_results_owner)));
  map_order_item_result_to_order_state.connect(service.makeStream<merge_results_reference_link>(merge_results));
  process_order_item.getErrorStream().setConsumer(merge_results);
  soft_deadline.connect(std::move(map_to_order_state_owner));
  split_pipeline.template get<1>().connect(std::move(soft_deadline_owner));
  process_order_item.connect(std::move(map_order_item_result_to_order_state_owner));
  split_pipeline.template get<0>().connect(std::move(process_order_items_owner));
  (*streams_.process_order).connect(std::move(split_pipeline_owner));
  streams_.process_order->setSource(split_order_result.template get<1>());

}

}  // namespace example::order_service::app