// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/substreams.generated.hpp"
#include "orderservice/internal/app/streams.generated.hpp"
#include "orderservice/internal/app/service.generated.hpp"

namespace example::order_service::app {
void ServiceSubStreams::bind(ServiceStreams& streams) {
  (void)streams;

}

}  // namespace example::order_service::app