// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <atomic>
#include <memory>
#include <stdexcept>
#include <utility>

#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated_client.usrv.pb.hpp>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>

#include <servicelib/transformation/streams.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>

namespace example::order_service::app {
class ServiceGenerated;
struct ServiceStreams;
struct ServiceSubStreams final {

  void bind(ServiceStreams& streams);
 private:
};

}  // namespace example::order_service::app