// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>

#include <servicelib/runtime/serde/serde.hpp>
#include <servicelib/runtime/serde/serdeimpl.hpp>
#include <model/include/example/model/serdes/order_item_serde.hpp>
#include <model/include/example/model/serdes/order_item_result_serde.hpp>


template <>
struct servicelib::serde::DefaultSerdeFactory<example::model::types::OrderItem> final {
  static std::shared_ptr<const servicelib::serde::Serde<example::model::types::OrderItem>>
  Make(servicelib::serde::SerdeLimits) {
    return std::make_shared<example::model::types::serde::OrderItemSerde>();
  }
};

template <>
struct servicelib::serde::DefaultSerdeFactory<example::model::types::OrderItemResult> final {
  static std::shared_ptr<const servicelib::serde::Serde<example::model::types::OrderItemResult>>
  Make(servicelib::serde::SerdeLimits) {
    return std::make_shared<example::model::types::serde::OrderItemResultSerde>();
  }
};