name: C++ CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Checkout pinned cppservicelib
        run: |
          git clone "https://github.com/gorundebug/cppservicelib.git" .servicelib
          git -C .servicelib checkout "v2.1.6"

      - name: Checkout pinned userver
        run: |
          git clone "https://github.com/userver-framework/userver.git" .userver
          git -C .userver checkout "c9f77729c0edce7e423def2d4a4450aa7fc9d259"

      - name: Build and test
        env:
          SERVICELIB_SOURCE_CONTEXT: .servicelib
          USERVER_SOURCE_CONTEXT: .userver
        run: ./scripts/test.sh

      - name: Integration tests
        env:
          SERVICELIB_SOURCE_CONTEXT: .servicelib
          USERVER_SOURCE_CONTEXT: .userver
        run: ./scripts/integration-test.sh

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Checkout pinned cppservicelib
        run: |
          git clone "https://github.com/gorundebug/cppservicelib.git" .servicelib
          git -C .servicelib checkout "v2.1.6"

      - name: Checkout pinned userver
        run: |
          git clone "https://github.com/userver-framework/userver.git" .userver
          git -C .userver checkout "c9f77729c0edce7e423def2d4a4450aa7fc9d259"

      - name: Lint
        env:
          SERVICELIB_SOURCE_CONTEXT: .servicelib
          USERVER_SOURCE_CONTEXT: .userver
        run: ./scripts/lint.sh
